// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Keys
{
    uint keys[1];
};

struct SortParams
{
    uint4 u_sort;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(512u, 1u, 1u);

kernel void cs(device Keys& _29 [[buffer(6)]], constant SortParams& _56 [[buffer(2)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    threadgroup uint s_keys[1024];
    uint base = gl_WorkGroupID.x * 1024u;
    uint t = gl_LocalInvocationID.x;
    s_keys[t] = _29.keys[base + t];
    s_keys[t + 512u] = _29.keys[(base + t) + 512u];
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint k = _56.u_sort.x; k <= _56.u_sort.y; k = k << 1u)
    {
        uint _74 = min((k >> 1u), 512u);
        for (uint j = _74; j > 0u; j = j >> 1u)
        {
            uint i = (2u * t) - (t & (j - 1u));
            uint l = i + j;
            bool up = ((base + i) & k) == 0u;
            uint a = s_keys[i];
            uint b = s_keys[l];
            if ((a > b) == up)
            {
                s_keys[i] = b;
                s_keys[l] = a;
            }
            threadgroup_barrier(mem_flags::mem_threadgroup);
        }
    }
    _29.keys[base + t] = s_keys[t];
    _29.keys[(base + t) + 512u] = s_keys[t + 512u];
}

