// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SkinPalette
{
    float4 u_skin_rows[3072];
};

struct Items
{
    uint4 items[1];
};

struct SceneCluster
{
    float4 sphere;
    uint4 range;
};

struct SceneCluster_1
{
    float4 sphere;
    uint4 range;
};

struct Clusters
{
    SceneCluster_1 clusters[1];
};

struct SceneInstance
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct SceneInstance_1
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct Movers
{
    SceneInstance_1 movers[1];
};

struct Statics
{
    SceneInstance_1 statics[1];
};

struct Indices
{
    uint vertexAt[1];
};

struct Words
{
    uint words[1];
};

struct Dirty
{
    uint4 dirty[1];
};

struct LightGpu
{
    float4 position_radius;
    float4 color_intensity;
    float4 source;
    float4 flicker;
};

struct LightTableBuffer
{
    LightGpu lights[1];
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float2 v_uv [[user(locn0)]];
    float4 gl_Position [[position]];
    float gl_ClipDistance [[clip_distance]] [4];
    float gl_ClipDistance_0 [[user(clip0)]];
    float gl_ClipDistance_1 [[user(clip1)]];
    float gl_ClipDistance_2 [[user(clip2)]];
    float gl_ClipDistance_3 [[user(clip3)]];
};

static inline __attribute__((always_inline))
float4x4 skin_matrix(thread const uint4& joints, thread const float4& weights, thread const float& base, constant SkinPalette& _84)
{
    uint b = uint(base + 0.5);
    uint4 at = uint4(b) + (joints * uint4(3u));
    float4 r0 = (((_84.u_skin_rows[at.x] * weights.x) + (_84.u_skin_rows[at.y] * weights.y)) + (_84.u_skin_rows[at.z] * weights.z)) + (_84.u_skin_rows[at.w] * weights.w);
    float4 r1 = (((_84.u_skin_rows[at.x + 1u] * weights.x) + (_84.u_skin_rows[at.y + 1u] * weights.y)) + (_84.u_skin_rows[at.z + 1u] * weights.z)) + (_84.u_skin_rows[at.w + 1u] * weights.w);
    float4 r2 = (((_84.u_skin_rows[at.x + 2u] * weights.x) + (_84.u_skin_rows[at.y + 2u] * weights.y)) + (_84.u_skin_rows[at.z + 2u] * weights.z)) + (_84.u_skin_rows[at.w + 2u] * weights.w);
    return float4x4(float4(float4(r0.x, r1.x, r2.x, 0.0)), float4(float4(r0.y, r1.y, r2.y, 0.0)), float4(float4(r0.z, r1.z, r2.z, 0.0)), float4(float4(r0.w, r1.w, r2.w, 1.0)));
}

static inline __attribute__((always_inline))
uint vsm_mip_offset(thread const uint& mip)
{
    if (mip == 0u)
    {
        return 0u;
    }
    if (mip == 1u)
    {
        return 256u;
    }
    if (mip == 2u)
    {
        return 320u;
    }
    if (mip == 3u)
    {
        return 336u;
    }
    return 340u;
}

static inline __attribute__((always_inline))
uint vsm_mip_side(thread const uint& mip)
{
    return 16u >> mip;
}

static inline __attribute__((always_inline))
void vsm_page_of(thread const uint& index, thread uint& face, thread uint& mip, thread uint2& page)
{
    face = index / 341u;
    uint rest = index % 341u;
    mip = 0u;
    if (rest >= 340u)
    {
        mip = 4u;
    }
    else
    {
        if (rest >= 336u)
        {
            mip = 3u;
        }
        else
        {
            if (rest >= 320u)
            {
                mip = 2u;
            }
            else
            {
                if (rest >= 256u)
                {
                    mip = 1u;
                }
            }
        }
    }
    uint param = mip;
    uint local = rest - vsm_mip_offset(param);
    uint param_1 = mip;
    uint side = vsm_mip_side(param_1);
    page = uint2(local % side, local / side);
}

static inline __attribute__((always_inline))
void vsm_basis(thread const uint& face, thread float3& n, thread float3& r, thread float3& u)
{
    if (face == 0u)
    {
        n = float3(1.0, 0.0, 0.0);
        r = float3(0.0, 0.0, -1.0);
        u = float3(0.0, 1.0, 0.0);
    }
    else
    {
        if (face == 1u)
        {
            n = float3(-1.0, 0.0, 0.0);
            r = float3(0.0, 0.0, 1.0);
            u = float3(0.0, 1.0, 0.0);
        }
        else
        {
            if (face == 2u)
            {
                n = float3(0.0, 1.0, 0.0);
                r = float3(1.0, 0.0, 0.0);
                u = float3(0.0, 0.0, -1.0);
            }
            else
            {
                if (face == 3u)
                {
                    n = float3(0.0, -1.0, 0.0);
                    r = float3(1.0, 0.0, 0.0);
                    u = float3(0.0, 0.0, 1.0);
                }
                else
                {
                    if (face == 4u)
                    {
                        n = float3(0.0, 0.0, 1.0);
                        r = float3(1.0, 0.0, 0.0);
                        u = float3(0.0, 1.0, 0.0);
                    }
                    else
                    {
                        n = float3(0.0, 0.0, -1.0);
                        r = float3(-1.0, 0.0, 0.0);
                        u = float3(0.0, 1.0, 0.0);
                    }
                }
            }
        }
    }
}

static inline __attribute__((always_inline))
float3 vsm_view(thread const uint& face, thread const float3& d)
{
    uint param = face;
    float3 param_1;
    float3 param_2;
    float3 param_3;
    vsm_basis(param, param_1, param_2, param_3);
    float3 n = param_1;
    float3 r = param_2;
    float3 u = param_3;
    return float3(dot(d, r), dot(d, u), dot(d, n));
}

static inline __attribute__((always_inline))
float4 vsm_page_rect(thread const uint& mip, thread const uint2& page)
{
    uint param = mip;
    float side = float(vsm_mip_side(param));
    float w = 2.0 / side;
    float g = (w * 1.0) / 64.0;
    float2 lo = (float2(page) * w) - float2(1.0);
    return float4(lo - float2(g), (lo + float2(w)) + float2(g));
}

static inline __attribute__((always_inline))
float4 vsm_scratch_rect(thread const uint& k)
{
    float2 cell = float2(float(k % 16u), float(k / 16u));
    float2 lo = (((cell * 66.0) / float2(1056.0)) * 2.0) - float2(1.0);
    return float4(lo, lo + float2(0.125));
}

static inline __attribute__((always_inline))
float2 vsm_clip_zw(thread const float& z, thread const float& radius)
{
    float f = fast::max(radius, 0.100000001490116119384765625);
    float a = f / (f - 0.0500000007450580596923828125);
    return float2((a * z) - (a * 0.0500000007450580596923828125), z);
}

vertex vs_out vs(const device Words& _576 [[buffer(6)]], const device Indices& _564 [[buffer(7)]], constant SkinPalette& _84 [[buffer(4)]], const device Clusters& _494 [[buffer(8)]], const device Statics& _554 [[buffer(9)]], const device Movers& _541 [[buffer(10)]], const device Items& _477 [[buffer(11)]], const device LightTableBuffer& _673 [[buffer(12)]], const device Dirty& _663 [[buffer(13)]], uint gl_VertexIndex [[vertex_id]])
{
    vs_out out = {};
    uint vertex0 = uint(int(gl_VertexIndex));
    uint4 item = _477.items[vertex0 / 192u];
    uint corner = vertex0 % 192u;
    SceneCluster _500;
    _500.sphere = _494.clusters[item.x].sphere;
    _500.range = _494.clusters[item.x].range;
    SceneCluster c = _500;
    if ((corner / 3u) >= c.range.y)
    {
        out.v_uv = float2(0.0);
        out.gl_Position = float4(2.0, 2.0, 2.0, 1.0);
        out.gl_ClipDistance[0] = -1.0;
        out.gl_ClipDistance[1] = -1.0;
        out.gl_ClipDistance[2] = -1.0;
        out.gl_ClipDistance[3] = -1.0;
        out.gl_ClipDistance_0 = out.gl_ClipDistance[0];
        out.gl_ClipDistance_1 = out.gl_ClipDistance[1];
        out.gl_ClipDistance_2 = out.gl_ClipDistance[2];
        out.gl_ClipDistance_3 = out.gl_ClipDistance[3];
        return out;
    }
    SceneInstance inst;
    if ((item.y & 2147483648u) != 0u)
    {
        uint _545 = item.y & 2147483647u;
        SceneInstance _549;
        _549.world = _541.movers[_545].world;
        _549.lo = _541.movers[_545].lo;
        _549.hi = _541.movers[_545].hi;
        _549.meta = _541.movers[_545].meta;
        inst = _549;
    }
    else
    {
        SceneInstance _559;
        _559.world = _554.statics[item.y].world;
        _559.lo = _554.statics[item.y].lo;
        _559.hi = _554.statics[item.y].hi;
        _559.meta = _554.statics[item.y].meta;
        inst = _559;
    }
    uint at = _564.vertexAt[c.range.x + corner];
    float3 position = float3(as_type<float>(_576.words[at]), as_type<float>(_576.words[at + 1u]), as_type<float>(_576.words[at + 2u]));
    out.v_uv = float2(as_type<float>(_576.words[at + 3u]), as_type<float>(_576.words[at + 4u]));
    float4x4 model = inst.world;
    if ((c.range.w & 1u) != 0u)
    {
        uint j = _576.words[at + 5u];
        uint4 joints = uint4(j & 255u, (j >> 8u) & 255u, (j >> 16u) & 255u, j >> 24u);
        float4 weights = unpack_unorm4x8_to_float(_576.words[at + 6u]);
        uint4 param = joints;
        float4 param_1 = weights;
        float param_2 = inst.hi.w;
        model = model * skin_matrix(param, param_1, param_2, _84);
    }
    float4 world = model * float4(position, 1.0);
    uint4 page = _663.dirty[item.z];
    float4 pr = _673.lights[page.y].position_radius;
    uint param_3 = page.z;
    uint param_4;
    uint param_5;
    uint2 param_6;
    vsm_page_of(param_3, param_4, param_5, param_6);
    uint face = param_4;
    uint mip = param_5;
    uint2 xy = param_6;
    uint param_7 = face;
    float3 param_8 = world.xyz - pr.xyz;
    float3 v = vsm_view(param_7, param_8);
    uint param_9 = mip;
    uint2 param_10 = xy;
    float4 rect = vsm_page_rect(param_9, param_10);
    uint param_11 = item.z;
    float4 cell = vsm_scratch_rect(param_11);
    float2 scale = (cell.zw - cell.xy) / (rect.zw - rect.xy);
    float2 clipXY = (cell.xy * v.z) + ((v.xy - (rect.xy * v.z)) * scale);
    float param_12 = v.z;
    float param_13 = pr.w;
    float2 zw = vsm_clip_zw(param_12, param_13);
    out.gl_Position = float4(clipXY, zw);
    out.gl_ClipDistance[0] = clipXY.x - (cell.x * v.z);
    out.gl_ClipDistance[1] = (cell.z * v.z) - clipXY.x;
    out.gl_ClipDistance[2] = clipXY.y - (cell.y * v.z);
    out.gl_ClipDistance[3] = (cell.w * v.z) - clipXY.y;
    out.gl_ClipDistance_0 = out.gl_ClipDistance[0];
    out.gl_ClipDistance_1 = out.gl_ClipDistance[1];
    out.gl_ClipDistance_2 = out.gl_ClipDistance[2];
    out.gl_ClipDistance_3 = out.gl_ClipDistance[3];
    return out;
}

