// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SkinPalette
{
    float4 u_skin_rows[3072];
};

struct Items
{
    uint4 items[1];
};

struct SceneCluster
{
    float4 sphere;
    uint4 range;
};

struct SceneCluster_1
{
    float4 sphere;
    uint4 range;
};

struct Clusters
{
    SceneCluster_1 clusters[1];
};

struct SceneInstance
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct SceneInstance_1
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct Movers
{
    SceneInstance_1 movers[1];
};

struct Statics
{
    SceneInstance_1 statics[1];
};

struct Indices
{
    uint vertexAt[1];
};

struct Words
{
    uint words[1];
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float2 v_uv [[user(locn0)]];
    float4 gl_Position [[position]];
};

static inline __attribute__((always_inline))
float4x4 skin_matrix(thread const uint4& joints, thread const float4& weights, thread const float& base, constant SkinPalette& _39)
{
    uint b = uint(base + 0.5);
    uint4 at = uint4(b) + (joints * uint4(3u));
    float4 r0 = (((_39.u_skin_rows[at.x] * weights.x) + (_39.u_skin_rows[at.y] * weights.y)) + (_39.u_skin_rows[at.z] * weights.z)) + (_39.u_skin_rows[at.w] * weights.w);
    float4 r1 = (((_39.u_skin_rows[at.x + 1u] * weights.x) + (_39.u_skin_rows[at.y + 1u] * weights.y)) + (_39.u_skin_rows[at.z + 1u] * weights.z)) + (_39.u_skin_rows[at.w + 1u] * weights.w);
    float4 r2 = (((_39.u_skin_rows[at.x + 2u] * weights.x) + (_39.u_skin_rows[at.y + 2u] * weights.y)) + (_39.u_skin_rows[at.z + 2u] * weights.z)) + (_39.u_skin_rows[at.w + 2u] * weights.w);
    return float4x4(float4(float4(r0.x, r1.x, r2.x, 0.0)), float4(float4(r0.y, r1.y, r2.y, 0.0)), float4(float4(r0.z, r1.z, r2.z, 0.0)), float4(float4(r0.w, r1.w, r2.w, 1.0)));
}

vertex vs_out vs(const device Words& _308 [[buffer(6)]], const device Indices& _294 [[buffer(7)]], constant CameraUniforms& _396 [[buffer(3)]], constant SkinPalette& _39 [[buffer(4)]], const device Clusters& _228 [[buffer(8)]], const device Statics& _284 [[buffer(9)]], const device Movers& _271 [[buffer(10)]], const device Items& _211 [[buffer(11)]], uint gl_VertexIndex [[vertex_id]])
{
    vs_out out = {};
    uint vertex0 = uint(int(gl_VertexIndex));
    uint4 item = _211.items[vertex0 / 192u];
    uint corner = vertex0 % 192u;
    SceneCluster _234;
    _234.sphere = _228.clusters[item.x].sphere;
    _234.range = _228.clusters[item.x].range;
    SceneCluster c = _234;
    if ((corner / 3u) >= c.range.y)
    {
        out.v_uv = float2(0.0);
        out.gl_Position = float4(2.0, 2.0, 2.0, 1.0);
        return out;
    }
    SceneInstance inst;
    if ((item.y & 2147483648u) != 0u)
    {
        uint _275 = item.y & 2147483647u;
        SceneInstance _279;
        _279.world = _271.movers[_275].world;
        _279.lo = _271.movers[_275].lo;
        _279.hi = _271.movers[_275].hi;
        _279.meta = _271.movers[_275].meta;
        inst = _279;
    }
    else
    {
        SceneInstance _289;
        _289.world = _284.statics[item.y].world;
        _289.lo = _284.statics[item.y].lo;
        _289.hi = _284.statics[item.y].hi;
        _289.meta = _284.statics[item.y].meta;
        inst = _289;
    }
    uint at = _294.vertexAt[c.range.x + corner];
    float3 position = float3(as_type<float>(_308.words[at]), as_type<float>(_308.words[at + 1u]), as_type<float>(_308.words[at + 2u]));
    out.v_uv = float2(as_type<float>(_308.words[at + 3u]), as_type<float>(_308.words[at + 4u]));
    float4x4 model = inst.world;
    if ((c.range.w & 1u) != 0u)
    {
        uint j = _308.words[at + 5u];
        uint4 joints = uint4(j & 255u, (j >> 8u) & 255u, (j >> 16u) & 255u, j >> 24u);
        float4 weights = unpack_unorm4x8_to_float(_308.words[at + 6u]);
        uint4 param = joints;
        float4 param_1 = weights;
        float param_2 = inst.hi.w;
        model = model * skin_matrix(param, param_1, param_2, _39);
    }
    float4 world = model * float4(position, 1.0);
    out.gl_Position = _396.u_projection_view * world;
    return out;
}

