// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Args
{
    uint args[1];
};

struct Counters
{
    uint counters[1];
};

struct LightCullParams
{
    float4 u_planes[6];
    float4x4 u_view;
    float4 u_eye;
    float4 u_screen;
    float4 u_zparams;
    uint4 u_counts;
    float4 u_shadow;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

kernel void cs(const device Counters& _16 [[buffer(6)]], constant LightCullParams& _28 [[buffer(2)]], device Args& _10 [[buffer(7)]])
{
    _10.args[0] = min(_16.counters[0], _28.u_counts.y);
    _10.args[1] = 1u;
    _10.args[2] = 1u;
    _10.args[3] = 0u;
}

