// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

struct LightCullParams
{
    float4 u_planes[6];
    float4x4 u_view;
    float4 u_eye;
    float4 u_screen;
    float4 u_zparams;
    uint4 u_counts;
    float4 u_shadow;
};

struct LightGpu
{
    float4 position_radius;
    float4 color_intensity;
    float4 source;
    float4 flicker;
    float4 spot;
};

struct LightTableBuffer
{
    LightGpu lights[1];
};

struct Counters
{
    uint counters[1];
};

struct Keys
{
    uint keys[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
bool scene_sphere_behind(thread const float4& p, thread const float3& c, thread const float& r)
{
    return (dot(p.xyz, c) + p.w) < (-r);
}

kernel void cs(constant LightCullParams& _49 [[buffer(2)]], const device LightTableBuffer& _64 [[buffer(6)]], device Keys& _150 [[buffer(7)]], device Counters& _133 [[buffer(8)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint slot = gl_GlobalInvocationID.x;
    if (slot >= _49.u_counts.x)
    {
        return;
    }
    float4 pr = _64.lights[slot].position_radius;
    if (pr.w <= 0.0)
    {
        return;
    }
    for (int i = 0; i < 6; i++)
    {
        float4 param = _49.u_planes[i];
        float3 param_1 = pr.xyz;
        float param_2 = pr.w;
        if (scene_sphere_behind(param, param_1, param_2))
        {
            return;
        }
    }
    float depth = fast::max(-(_49.u_view * float4(pr.xyz, 1.0)).z, 0.0);
    uint key = ((as_type<uint>(depth) >> 13u) << 13u) | slot;
    uint _137 = atomic_fetch_add_explicit((device atomic_uint*)&_133.counters[0], 1u, memory_order_relaxed);
    uint at = _137;
    if (at >= _49.u_counts.y)
    {
        uint _145 = atomic_fetch_add_explicit((device atomic_uint*)&_133.counters[1], 1u, memory_order_relaxed);
        return;
    }
    _150.keys[at] = key;
}

