// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct ModelMaterial
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct ModelMaterial_1
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct MaterialTable
{
    ModelMaterial_1 materials[1];
};

struct spvDescriptorSetBuffer3
{
    array<sampler, 16> u_tableSamplers [[id(0)]];
    array<texture2d<float>, 4096> u_tableTextures [[id(16)]];
};

struct fs_out
{
    float4 gbuffer_out_position [[color(0)]];
    float4 gbuffer_out_normal [[color(1)]];
    float4 gbuffer_out_albedo [[color(2)]];
    float4 gbuffer_out_material [[color(3)]];
    float4 gbuffer_out_emissive [[color(4)]];
    float4 gbuffer_out_id [[color(5)]];
};

struct fs_in
{
    float3 v_position [[user(locn0)]];
    float3 v_normal [[user(locn1)]];
    float4 v_tangent [[user(locn2)]];
    float2 v_uv [[user(locn3)]];
    float4 v_tint [[user(locn4)]];
    uint v_material [[user(locn5)]];
};

static inline __attribute__((always_inline))
float parallax_fade(thread const float& dist, thread const float& fade)
{
    return 1.0 - smoothstep(0.75 * fade, fade, dist);
}

static inline __attribute__((always_inline))
float3 parallax_view(thread const float3& t, thread const float3& b, thread const float3& n, thread const float3& to_eye)
{
    return float3(dot(to_eye, t), dot(to_eye, b), dot(to_eye, n));
}

static inline __attribute__((always_inline))
float4 table_sample_grad(thread const uint& tex, thread const uint& samp, thread const float2& uv, thread const float2& dx, thread const float2& dy, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    uint _108 = tex;
    uint _112 = samp;
    return u_tableTextures[_108].sample(u_tableSamplers[_112], uv, gradient2d(dx, dy));
}

static inline __attribute__((always_inline))
float parallax_height(thread const float2& uv, thread const float2& dx, thread const float2& dy, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers, thread uint& g_height)
{
    uint param = g_height;
    uint param_1 = 0u;
    float2 param_2 = uv;
    float2 param_3 = dx;
    float2 param_4 = dy;
    return table_sample_grad(param, param_1, param_2, param_3, param_4, u_tableTextures, u_tableSamplers).x;
}

static inline __attribute__((always_inline))
float2 parallax_offset(thread const float2& uv, thread const float3& view_ts, thread const float& depth, thread const float& max_steps, thread const float2& dx, thread const float2& dy, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers, thread uint& g_height)
{
    float head_on = fast::clamp(view_ts.z, 0.0, 1.0);
    float top = fast::clamp(max_steps, 1.0, 64.0);
    float steps = floor(mix(top, fast::max(4.0, top * 0.25), head_on));
    float layer = 1.0 / steps;
    float2 step_uv = (view_ts.xy / float2(fast::max(view_ts.z, 0.20000000298023223876953125))) * (depth * layer);
    float2 at = uv;
    float ray = 1.0;
    float2 param = at;
    float2 param_1 = dx;
    float2 param_2 = dy;
    float h = parallax_height(param, param_1, param_2, u_tableTextures, u_tableSamplers, g_height);
    float prev_h = h;
    float prev_ray = ray;
    for (int i = 0; i < 64; i++)
    {
        if ((float(i) >= steps) || (ray <= h))
        {
            break;
        }
        prev_h = h;
        prev_ray = ray;
        at -= step_uv;
        ray -= layer;
        float2 param_3 = at;
        float2 param_4 = dx;
        float2 param_5 = dy;
        h = parallax_height(param_3, param_4, param_5, u_tableTextures, u_tableSamplers, g_height);
    }
    float below = h - ray;
    float above = prev_h - prev_ray;
    float w = below / fast::max(below - above, 9.9999997473787516355514526367188e-06);
    return mix(at, at + step_uv, float2(w));
}

static inline __attribute__((always_inline))
float4 table_sample(thread const uint& tex, thread const uint& samp, thread const float2& uv, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    uint _87 = tex;
    uint _97 = samp;
    return u_tableTextures[_87].sample(u_tableSamplers[_97], uv);
}

static inline __attribute__((always_inline))
float gbuffer_id_encode(thread const uint& id)
{
    return float(id) / 255.0;
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread const uint& id, thread float4& gbuffer_out_position, constant CameraUniforms& _134, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    gbuffer_out_position = float4(position - _134.u_camera_position.xyz, 1.0);
    gbuffer_out_normal = float4(normal, 0.0);
    gbuffer_out_albedo = float4(albedo, 1.0);
    gbuffer_out_material = float4(roughness, metallic, fast::clamp(ao, 0.0, 1.0), 1.0);
    gbuffer_out_emissive = float4(emissive, 1.0);
    uint param = id;
    gbuffer_out_id = float4(gbuffer_id_encode(param), 0.0, 0.0, 1.0);
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread float4& gbuffer_out_position, constant CameraUniforms& _134, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    float3 param = position;
    float3 param_1 = normal;
    float3 param_2 = albedo;
    float param_3 = metallic;
    float param_4 = roughness;
    float3 param_5 = emissive;
    float param_6 = ao;
    uint param_7 = 1u;
    gbuffer_write(param, param_1, param_2, param_3, param_4, param_5, param_6, param_7, gbuffer_out_position, _134, gbuffer_out_normal, gbuffer_out_albedo, gbuffer_out_material, gbuffer_out_emissive, gbuffer_out_id);
}

fragment fs_out fs(fs_in in [[stage_in]], constant spvDescriptorSetBuffer3& spvDescriptorSet3 [[buffer(18)]], constant CameraUniforms& _134 [[buffer(3)]], const device MaterialTable& _355 [[buffer(14)]], bool gl_FrontFacing [[front_facing]])
{
    fs_out out = {};
    ModelMaterial _362;
    _362.base_color = _355.materials[in.v_material].base_color;
    _362.factors = _355.materials[in.v_material].factors;
    _362.uv_scale = _355.materials[in.v_material].uv_scale;
    _362.emissive = _355.materials[in.v_material].emissive;
    _362.maps0 = _355.materials[in.v_material].maps0;
    _362.maps1 = _355.materials[in.v_material].maps1;
    ModelMaterial mat = _362;
    float2 uv = in.v_uv * mat.uv_scale.xy;
    int flags = int(mat.factors.z + 0.5);
    float3 n = fast::normalize(in.v_normal);
    uint g_height;
    if (!gl_FrontFacing)
    {
        n = -n;
    }
    float3 t = fast::normalize(in.v_tangent.xyz);
    t = fast::normalize(t - (n * dot(n, t)));
    float3 b = cross(n, t) * in.v_tangent.w;
    g_height = mat.maps1.w;
    float3 to_eye = _134.u_camera_position.xyz - in.v_position;
    float param = length(to_eye);
    float param_1 = mat.uv_scale.w;
    float depth = mat.factors.w * parallax_fade(param, param_1);
    if (depth > 9.9999997473787516355514526367188e-06)
    {
        float2 dx = dfdx(uv);
        float2 dy = dfdy(uv);
        float3 param_2 = t;
        float3 param_3 = b;
        float3 param_4 = n;
        float3 param_5 = fast::normalize(to_eye);
        float2 param_6 = uv;
        float3 param_7 = parallax_view(param_2, param_3, param_4, param_5);
        float param_8 = depth;
        float param_9 = mat.uv_scale.z;
        float2 param_10 = dx;
        float2 param_11 = dy;
        uv = parallax_offset(param_6, param_7, param_8, param_9, param_10, param_11, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers, g_height);
    }
    float3 albedo = mat.base_color.xyz;
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        uint param_12 = mat.maps0.x;
        uint param_13 = 0u;
        float2 param_14 = uv;
        float4 sampled = table_sample(param_12, param_13, param_14, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers);
        albedo = sampled.xyz;
        alpha = sampled.w;
    }
    if ((flags & 32) != 0)
    {
        uint param_15 = mat.maps1.y;
        uint param_16 = 0u;
        float2 param_17 = uv;
        alpha = table_sample(param_15, param_16, param_17, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    bool _507 = mat.base_color.w > 0.0;
    bool _514;
    if (_507)
    {
        _514 = alpha < mat.base_color.w;
    }
    else
    {
        _514 = _507;
    }
    if (_514)
    {
        discard_fragment();
    }
    albedo *= in.v_tint.xyz;
    if ((flags & 2) != 0)
    {
        uint param_18 = mat.maps0.y;
        uint param_19 = 0u;
        float2 param_20 = uv;
        float3 tn = (table_sample(param_18, param_19, param_20, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).xyz * 2.0) - float3(1.0);
        n = fast::normalize(float3x3(float3(t), float3(b), float3(n)) * tn);
    }
    float roughness = mat.factors.x;
    if ((flags & 4) != 0)
    {
        uint param_21 = mat.maps0.z;
        uint param_22 = 0u;
        float2 param_23 = uv;
        roughness = table_sample(param_21, param_22, param_23, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    float metallic = mat.factors.y;
    if ((flags & 8) != 0)
    {
        uint param_24 = mat.maps0.w;
        uint param_25 = 0u;
        float2 param_26 = uv;
        metallic = table_sample(param_24, param_25, param_26, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    float ao = 1.0;
    if ((flags & 16) != 0)
    {
        uint param_27 = mat.maps1.x;
        uint param_28 = 0u;
        float2 param_29 = uv;
        ao = table_sample(param_27, param_28, param_29, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    float3 emissive = float3(0.0);
    if (dot(mat.emissive.xyz, float3(1.0)) > 0.0)
    {
        uint param_30 = mat.maps1.z;
        uint param_31 = 0u;
        float2 param_32 = uv;
        emissive = mat.emissive.xyz * table_sample(param_30, param_31, param_32, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).xyz;
    }
    float3 param_33 = in.v_position;
    float3 param_34 = n;
    float3 param_35 = albedo;
    float param_36 = metallic;
    float param_37 = roughness;
    float3 param_38 = emissive;
    float param_39 = ao;
    gbuffer_write(param_33, param_34, param_35, param_36, param_37, param_38, param_39, out.gbuffer_out_position, _134, out.gbuffer_out_normal, out.gbuffer_out_albedo, out.gbuffer_out_material, out.gbuffer_out_emissive, out.gbuffer_out_id);
    return out;
}

