// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ModelMaterial
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct ModelMaterial_1
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct MaterialTable
{
    ModelMaterial_1 materials[1];
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct spvDescriptorSetBuffer3
{
    array<sampler, 16> u_tableSamplers [[id(0)]];
    array<texture2d<float>, 4096> u_tableTextures [[id(16)]];
};

struct fs_in
{
    float2 v_uv [[user(locn3)]];
    uint v_material [[user(locn5)]];
};

static inline __attribute__((always_inline))
float4 table_sample(thread const uint& tex, thread const uint& samp, thread const float2& uv, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    uint _33 = tex;
    uint _43 = samp;
    return u_tableTextures[_33].sample(u_tableSamplers[_43], uv);
}

static inline __attribute__((always_inline))
bool table_alpha_cutout(thread const ModelMaterial& mat, thread const float2& meshUv, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    float2 uv = meshUv * mat.uv_scale.xy;
    int flags = int(mat.factors.z + 0.5);
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        uint param = mat.maps0.x;
        uint param_1 = 0u;
        float2 param_2 = uv;
        alpha = table_sample(param, param_1, param_2, u_tableTextures, u_tableSamplers).w;
    }
    if ((flags & 32) != 0)
    {
        uint param_3 = mat.maps1.y;
        uint param_4 = 0u;
        float2 param_5 = uv;
        alpha = table_sample(param_3, param_4, param_5, u_tableTextures, u_tableSamplers).x;
    }
    bool _110 = mat.base_color.w > 0.0;
    bool _117;
    if (_110)
    {
        _117 = alpha < mat.base_color.w;
    }
    else
    {
        _117 = _110;
    }
    return _117;
}

fragment void fs(fs_in in [[stage_in]], constant spvDescriptorSetBuffer3& spvDescriptorSet3 [[buffer(18)]], const device MaterialTable& _124 [[buffer(14)]])
{
    ModelMaterial _134;
    _134.base_color = _124.materials[in.v_material].base_color;
    _134.factors = _124.materials[in.v_material].factors;
    _134.uv_scale = _124.materials[in.v_material].uv_scale;
    _134.emissive = _124.materials[in.v_material].emissive;
    _134.maps0 = _124.materials[in.v_material].maps0;
    _134.maps1 = _124.materials[in.v_material].maps1;
    ModelMaterial param = _134;
    float2 param_1 = in.v_uv;
    if (table_alpha_cutout(param, param_1, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers))
    {
        discard_fragment();
    }
}

