// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct ModelMaterial
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct ModelMaterial_1
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct MaterialTable
{
    ModelMaterial_1 materials[1];
};

struct spvDescriptorSetBuffer3
{
    array<sampler, 16> u_tableSamplers [[id(0)]];
    array<texture2d<float>, 4096> u_tableTextures [[id(16)]];
};

struct fs_out
{
    float4 gbuffer_out_position [[color(0)]];
    float4 gbuffer_out_normal [[color(1)]];
    float4 gbuffer_out_albedo [[color(2)]];
    float4 gbuffer_out_material [[color(3)]];
    float4 gbuffer_out_emissive [[color(4)]];
    float4 gbuffer_out_id [[color(5)]];
};

struct fs_in
{
    float3 v_position [[user(locn0)]];
    float3 v_normal [[user(locn1)]];
    float4 v_tangent [[user(locn2)]];
    float2 v_uv [[user(locn3)]];
    float4 v_tint [[user(locn4)]];
    uint v_material [[user(locn5)]];
};

static inline __attribute__((always_inline))
float4 table_sample(thread const uint& tex, thread const uint& samp, thread const float2& uv, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    uint _52 = tex;
    uint _62 = samp;
    return u_tableTextures[_52].sample(u_tableSamplers[_62], uv);
}

static inline __attribute__((always_inline))
float gbuffer_id_encode(thread const uint& id)
{
    return float(id) / 255.0;
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread const uint& id, thread float4& gbuffer_out_position, constant CameraUniforms& _84, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    gbuffer_out_position = float4(position - _84.u_camera_position.xyz, 1.0);
    gbuffer_out_normal = float4(normal, 0.0);
    gbuffer_out_albedo = float4(albedo, 1.0);
    gbuffer_out_material = float4(roughness, metallic, fast::clamp(ao, 0.0, 1.0), 1.0);
    gbuffer_out_emissive = float4(emissive, 1.0);
    uint param = id;
    gbuffer_out_id = float4(gbuffer_id_encode(param), 0.0, 0.0, 1.0);
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread float4& gbuffer_out_position, constant CameraUniforms& _84, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    float3 param = position;
    float3 param_1 = normal;
    float3 param_2 = albedo;
    float param_3 = metallic;
    float param_4 = roughness;
    float3 param_5 = emissive;
    float param_6 = ao;
    uint param_7 = 1u;
    gbuffer_write(param, param_1, param_2, param_3, param_4, param_5, param_6, param_7, gbuffer_out_position, _84, gbuffer_out_normal, gbuffer_out_albedo, gbuffer_out_material, gbuffer_out_emissive, gbuffer_out_id);
}

fragment fs_out fs(fs_in in [[stage_in]], constant spvDescriptorSetBuffer3& spvDescriptorSet3 [[buffer(18)]], constant CameraUniforms& _84 [[buffer(3)]], const device MaterialTable& _152 [[buffer(14)]], bool gl_FrontFacing [[front_facing]])
{
    fs_out out = {};
    ModelMaterial _160;
    _160.base_color = _152.materials[in.v_material].base_color;
    _160.factors = _152.materials[in.v_material].factors;
    _160.uv_scale = _152.materials[in.v_material].uv_scale;
    _160.emissive = _152.materials[in.v_material].emissive;
    _160.maps0 = _152.materials[in.v_material].maps0;
    _160.maps1 = _152.materials[in.v_material].maps1;
    ModelMaterial mat = _160;
    float2 uv = in.v_uv * mat.uv_scale.xy;
    int flags = int(mat.factors.z + 0.5);
    float3 n = fast::normalize(in.v_normal);
    if (!gl_FrontFacing)
    {
        n = -n;
    }
    float3 t = fast::normalize(in.v_tangent.xyz);
    t = fast::normalize(t - (n * dot(n, t)));
    float3 b = cross(n, t) * in.v_tangent.w;
    float3 albedo = mat.base_color.xyz;
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        uint param = mat.maps0.x;
        uint param_1 = 0u;
        float2 param_2 = uv;
        float4 sampled = table_sample(param, param_1, param_2, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers);
        albedo = sampled.xyz;
        alpha = sampled.w;
    }
    if ((flags & 32) != 0)
    {
        uint param_3 = mat.maps1.y;
        uint param_4 = 0u;
        float2 param_5 = uv;
        alpha = table_sample(param_3, param_4, param_5, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    bool _257 = mat.base_color.w > 0.0;
    bool _264;
    if (_257)
    {
        _264 = alpha < mat.base_color.w;
    }
    else
    {
        _264 = _257;
    }
    if (_264)
    {
        discard_fragment();
    }
    albedo *= in.v_tint.xyz;
    if ((flags & 2) != 0)
    {
        uint param_6 = mat.maps0.y;
        uint param_7 = 0u;
        float2 param_8 = uv;
        float3 tn = (table_sample(param_6, param_7, param_8, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).xyz * 2.0) - float3(1.0);
        n = fast::normalize(float3x3(float3(t), float3(b), float3(n)) * tn);
    }
    float roughness = mat.factors.x;
    if ((flags & 4) != 0)
    {
        uint param_9 = mat.maps0.z;
        uint param_10 = 0u;
        float2 param_11 = uv;
        roughness = table_sample(param_9, param_10, param_11, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    float metallic = mat.factors.y;
    if ((flags & 8) != 0)
    {
        uint param_12 = mat.maps0.w;
        uint param_13 = 0u;
        float2 param_14 = uv;
        metallic = table_sample(param_12, param_13, param_14, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    float ao = 1.0;
    if ((flags & 16) != 0)
    {
        uint param_15 = mat.maps1.x;
        uint param_16 = 0u;
        float2 param_17 = uv;
        ao = table_sample(param_15, param_16, param_17, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).x;
    }
    float3 emissive = float3(0.0);
    if (dot(mat.emissive.xyz, float3(1.0)) > 0.0)
    {
        uint param_18 = mat.maps1.z;
        uint param_19 = 0u;
        float2 param_20 = uv;
        emissive = mat.emissive.xyz * table_sample(param_18, param_19, param_20, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers).xyz;
    }
    float3 param_21 = in.v_position;
    float3 param_22 = n;
    float3 param_23 = albedo;
    float param_24 = metallic;
    float param_25 = roughness;
    float3 param_26 = emissive;
    float param_27 = ao;
    gbuffer_write(param_21, param_22, param_23, param_24, param_25, param_26, param_27, out.gbuffer_out_position, _84, out.gbuffer_out_normal, out.gbuffer_out_albedo, out.gbuffer_out_material, out.gbuffer_out_emissive, out.gbuffer_out_id);
    return out;
}

