// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ScenePose
{
    float4 r0;
    float4 r1;
    float4 r2;
};

struct SkinPalette
{
    float4 u_skin_rows[3072];
};

struct SceneDrawItem
{
    uint4 head;
    uint4 extra;
};

struct SceneDrawItem_1
{
    uint4 head;
    uint4 extra;
};

struct DrawItems
{
    SceneDrawItem_1 drawItems[1];
};

struct Detail
{
    uint detail[1];
};

struct Words
{
    uint words[1];
};

struct ScenePose_1
{
    float4 r0;
    float4 r1;
    float4 r2;
};

struct Poses
{
    ScenePose_1 poses[1];
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float2 v_uv [[user(locn0)]];
    uint v_material [[user(locn1)]];
    float v_style [[user(locn2)]];
    float4 gl_Position [[position]];
};

static inline __attribute__((always_inline))
float4x4 scene_world(thread const ScenePose& p)
{
    return float4x4(float4(float4(p.r0.x, p.r1.x, p.r2.x, 0.0)), float4(float4(p.r0.y, p.r1.y, p.r2.y, 0.0)), float4(float4(p.r0.z, p.r1.z, p.r2.z, 0.0)), float4(float4(p.r0.w, p.r1.w, p.r2.w, 1.0)));
}

static inline __attribute__((always_inline))
float4x4 skin_matrix(thread const uint4& joints, thread const float4& weights, thread const float& base, constant SkinPalette& _45)
{
    uint b = uint(base + 0.5);
    uint4 at = uint4(b) + (joints * uint4(3u));
    float4 r0 = (((_45.u_skin_rows[at.x] * weights.x) + (_45.u_skin_rows[at.y] * weights.y)) + (_45.u_skin_rows[at.z] * weights.z)) + (_45.u_skin_rows[at.w] * weights.w);
    float4 r1 = (((_45.u_skin_rows[at.x + 1u] * weights.x) + (_45.u_skin_rows[at.y + 1u] * weights.y)) + (_45.u_skin_rows[at.z + 1u] * weights.z)) + (_45.u_skin_rows[at.w + 1u] * weights.w);
    float4 r2 = (((_45.u_skin_rows[at.x + 2u] * weights.x) + (_45.u_skin_rows[at.y + 2u] * weights.y)) + (_45.u_skin_rows[at.z + 2u] * weights.z)) + (_45.u_skin_rows[at.w + 2u] * weights.w);
    return float4x4(float4(float4(r0.x, r1.x, r2.x, 0.0)), float4(float4(r0.y, r1.y, r2.y, 0.0)), float4(float4(r0.z, r1.z, r2.z, 0.0)), float4(float4(r0.w, r1.w, r2.w, 1.0)));
}

vertex vs_out vs(const device Words& _301 [[buffer(6)]], const device Detail& _285 [[buffer(7)]], constant CameraUniforms& _413 [[buffer(3)]], constant SkinPalette& _45 [[buffer(4)]], const device Poses& _323 [[buffer(10)]], const device DrawItems& _273 [[buffer(11)]], uint gl_VertexIndex [[vertex_id]])
{
    vs_out out = {};
    uint index = uint(int(gl_VertexIndex));
    uint _276 = index >> 6u;
    SceneDrawItem _280;
    _280.head = _273.drawItems[_276].head;
    _280.extra = _273.drawItems[_276].extra;
    SceneDrawItem item = _280;
    uint at = _285.detail[item.head.x + (index & 63u)];
    float3 position = float3(as_type<float>(_301.words[at]), as_type<float>(_301.words[at + 1u]), as_type<float>(_301.words[at + 2u]));
    ScenePose _330;
    _330.r0 = _323.poses[item.head.y].r0;
    _330.r1 = _323.poses[item.head.y].r1;
    _330.r2 = _323.poses[item.head.y].r2;
    ScenePose param = _330;
    float4x4 model = scene_world(param);
    uint j = _301.words[at + 12u];
    uint4 joints = uint4(j & 255u, (j >> 8u) & 255u, (j >> 16u) & 255u, j >> 24u);
    float4 weights = unpack_unorm4x8_to_float(_301.words[at + 13u]);
    uint4 param_1 = joints;
    float4 param_2 = weights;
    float param_3 = as_type<float>(item.head.w);
    model = model * skin_matrix(param_1, param_2, param_3, _45);
    float4 world = model * float4(position, 1.0);
    out.v_uv = float2(as_type<float>(_301.words[at + 3u]), as_type<float>(_301.words[(at + 3u) + 1u]));
    out.v_material = item.head.z;
    out.v_style = float((item.extra.z >> 8u) & 7u);
    out.gl_Position = _413.u_projection_view * world;
    return out;
}

