// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ScenePose
{
    float4 r0;
    float4 r1;
    float4 r2;
};

struct SceneDrawItem
{
    uint4 head;
    uint4 extra;
};

struct SceneDrawItem_1
{
    uint4 head;
    uint4 extra;
};

struct DrawItems
{
    SceneDrawItem_1 drawItems[1];
};

struct Detail
{
    uint detail[1];
};

struct Words
{
    uint words[1];
};

struct ScenePose_1
{
    float4 r0;
    float4 r1;
    float4 r2;
};

struct Poses
{
    ScenePose_1 poses[1];
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float2 v_uv [[user(locn0)]];
    uint v_material [[user(locn1)]];
    float v_style [[user(locn2)]];
    float4 gl_Position [[position]];
};

static inline __attribute__((always_inline))
float4x4 scene_world(thread const ScenePose& p)
{
    return float4x4(float4(float4(p.r0.x, p.r1.x, p.r2.x, 0.0)), float4(float4(p.r0.y, p.r1.y, p.r2.y, 0.0)), float4(float4(p.r0.z, p.r1.z, p.r2.z, 0.0)), float4(float4(p.r0.w, p.r1.w, p.r2.w, 1.0)));
}

vertex vs_out vs(const device Words& _120 [[buffer(6)]], const device Detail& _104 [[buffer(7)]], constant CameraUniforms& _194 [[buffer(3)]], const device Poses& _142 [[buffer(10)]], const device DrawItems& _92 [[buffer(11)]], uint gl_VertexIndex [[vertex_id]])
{
    vs_out out = {};
    uint index = uint(int(gl_VertexIndex));
    uint _95 = index >> 6u;
    SceneDrawItem _99;
    _99.head = _92.drawItems[_95].head;
    _99.extra = _92.drawItems[_95].extra;
    SceneDrawItem item = _99;
    uint at = _104.detail[item.head.x + (index & 63u)];
    float3 position = float3(as_type<float>(_120.words[at]), as_type<float>(_120.words[at + 1u]), as_type<float>(_120.words[at + 2u]));
    ScenePose _149;
    _149.r0 = _142.poses[item.head.y].r0;
    _149.r1 = _142.poses[item.head.y].r1;
    _149.r2 = _142.poses[item.head.y].r2;
    ScenePose param = _149;
    float4x4 model = scene_world(param);
    float4 world = model * float4(position, 1.0);
    out.v_uv = float2(as_type<float>(_120.words[at + 3u]), as_type<float>(_120.words[(at + 3u) + 1u]));
    out.v_material = item.head.z;
    out.v_style = float((item.extra.z >> 8u) & 7u);
    out.gl_Position = _194.u_projection_view * world;
    return out;
}

