// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ModelMaterial
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct ModelMaterial_1
{
    float4 base_color;
    float4 factors;
    float4 uv_scale;
    float4 emissive;
    uint4 maps0;
    uint4 maps1;
};

struct MaterialTable
{
    ModelMaterial_1 materials[1];
};

struct spvDescriptorSetBuffer3
{
    array<sampler, 16> u_tableSamplers [[id(0)]];
    array<texture2d<float>, 4096> u_tableTextures [[id(16)]];
};

struct fs_out
{
    float4 o_mask [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
    uint v_material [[user(locn1)]];
    float v_style [[user(locn2), flat]];
};

static inline __attribute__((always_inline))
float4 table_sample(thread const uint& tex, thread const uint& samp, thread const float2& uv, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    uint _38 = tex;
    uint _48 = samp;
    return u_tableTextures[_38].sample(u_tableSamplers[_48], uv);
}

static inline __attribute__((always_inline))
bool table_alpha_cutout(thread const ModelMaterial& mat, thread const float2& meshUv, constant array<texture2d<float>, 4096>& u_tableTextures, constant array<sampler, 16>& u_tableSamplers)
{
    float2 uv = meshUv * mat.uv_scale.xy;
    int flags = int(mat.factors.z + 0.5);
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        uint param = mat.maps0.x;
        uint param_1 = 0u;
        float2 param_2 = uv;
        alpha = table_sample(param, param_1, param_2, u_tableTextures, u_tableSamplers).w;
    }
    if ((flags & 32) != 0)
    {
        uint param_3 = mat.maps1.y;
        uint param_4 = 0u;
        float2 param_5 = uv;
        alpha = table_sample(param_3, param_4, param_5, u_tableTextures, u_tableSamplers).x;
    }
    bool _114 = mat.base_color.w > 0.0;
    bool _121;
    if (_114)
    {
        _121 = alpha < mat.base_color.w;
    }
    else
    {
        _121 = _114;
    }
    return _121;
}

static inline __attribute__((always_inline))
float eye_distance(thread const float& depth, constant CameraUniforms& _128)
{
    float4 view = _128.u_inverse_projection * float4(0.0, 0.0, depth, 1.0);
    return (-view.z) / view.w;
}

fragment fs_out fs(fs_in in [[stage_in]], constant spvDescriptorSetBuffer3& spvDescriptorSet3 [[buffer(18)]], constant CameraUniforms& _128 [[buffer(3)]], const device MaterialTable& _148 [[buffer(14)]], texture2d<float> u_scene_depth [[texture(8)]], sampler u_scene_depthSmplr [[sampler(8)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    ModelMaterial _158;
    _158.base_color = _148.materials[in.v_material].base_color;
    _158.factors = _148.materials[in.v_material].factors;
    _158.uv_scale = _148.materials[in.v_material].uv_scale;
    _158.emissive = _148.materials[in.v_material].emissive;
    _158.maps0 = _148.materials[in.v_material].maps0;
    _158.maps1 = _148.materials[in.v_material].maps1;
    ModelMaterial param = _158;
    float2 param_1 = in.v_uv;
    if (table_alpha_cutout(param, param_1, spvDescriptorSet3.u_tableTextures, spvDescriptorSet3.u_tableSamplers))
    {
        discard_fragment();
    }
    float scene = u_scene_depth.read(uint2(int2(gl_FragCoord.xy)), 0).x;
    float param_2 = gl_FragCoord.z;
    float mine = eye_distance(param_2, _128);
    float param_3 = scene;
    float front = eye_distance(param_3, _128);
    float visible = float(mine <= ((front + 0.0500000007450580596923828125) + (front * 0.00999999977648258209228515625)));
    out.o_mask = float4(1.0, visible, (in.v_style + 0.5) / 4.0, 1.0);
    return out;
}

