// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ScanParams
{
    uint4 u_scan;
};

struct Levels
{
    uint levels[1];
};

struct Values
{
    uint values[1];
};

struct Sums
{
    uint sums[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1024u, 1u, 1u);

kernel void cs(constant ScanParams& _28 [[buffer(2)]], device Values& _66 [[buffer(6)]], device Sums& _132 [[buffer(7)]], const device Levels& _46 [[buffer(8)]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]])
{
    threadgroup uint s_scan[1024];
    uint t = gl_LocalInvocationID.x;
    uint i = (gl_WorkGroupID.x * 1024u) + t;
    uint _37;
    if (_28.u_scan.w == 0u)
    {
        _37 = _28.u_scan.x;
    }
    else
    {
        _37 = _46.levels[(12u + _28.u_scan.w) - 1u];
    }
    uint count = _37;
    uint own = 0u;
    if (i < count)
    {
        own = _66.values[_28.u_scan.y + i];
    }
    s_scan[t] = own;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint o = 1u; o < 1024u; o = o << 1u)
    {
        uint add = 0u;
        if (t >= o)
        {
            add = s_scan[t - o];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        s_scan[t] += add;
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (i < count)
    {
        _66.values[_28.u_scan.y + i] = s_scan[t] - own;
    }
    if (t == 1023u)
    {
        _132.sums[_28.u_scan.z + gl_WorkGroupID.x] = s_scan[t];
    }
}

