// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_rows;
    uint4 u_limits;
};

struct Counters
{
    uint counters[1];
};

struct Args
{
    uint args[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1024u, 1u, 1u);

kernel void cs(constant SceneCullParams& _22 [[buffer(2)]], device Counters& _43 [[buffer(6)]], device Args& _142 [[buffer(7)]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    threadgroup uint s_scan[1024];
    uint t = gl_LocalInvocationID.x;
    uint segments = _22.u_limits.w * _22.u_rows.w;
    uint count = 0u;
    if (t < segments)
    {
        count = _43.counters[4u + t];
    }
    s_scan[t] = count;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint o = 1u; o < 1024u; o = o << 1u)
    {
        uint add = 0u;
        if (t >= o)
        {
            add = s_scan[t - o];
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        s_scan[t] += add;
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (t >= segments)
    {
        return;
    }
    uint start = min((s_scan[t] - count), _22.u_limits.y);
    uint end = min(s_scan[t], _22.u_limits.y);
    if ((end - start) < count)
    {
        uint _124 = atomic_fetch_add_explicit((device atomic_uint*)&_43.counters[2], count - (end - start), memory_order_relaxed);
    }
    _43.counters[1028u + t] = start;
    _43.counters[2052u + t] = end;
    uint at = 4u + (t * 4u);
    _142.args[at] = (end - start) * 192u;
    _142.args[at + 1u] = 1u;
    _142.args[at + 2u] = start * 192u;
    _142.args[at + 3u] = 0u;
}

