// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct SceneModel
{
    uint4 head;
    float4 bias0;
    float4 dist0;
    float4 dist1;
    uint4 start0;
    uint4 start1;
};

struct SceneView
{
    spvUnsafeArray<float4, 6> planes;
    uint4 meta;
    float4 clip;
    float4 sphere;
    float4 eye;
};

struct SceneRun
{
    uint4 range;
};

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_counts;
    uint4 u_caps;
    uint4 u_mode;
    uint4 u_debug;
    float4 u_grid;
    uint4 u_local;
};

struct SceneInstance
{
    float4 lo;
    float4 hi;
    uint4 meta;
    uint4 extra;
};

struct SceneInstance_1
{
    float4 lo;
    float4 hi;
    uint4 meta;
    uint4 extra;
};

struct Instances
{
    SceneInstance_1 instances[1];
};

struct SceneModel_1
{
    uint4 head;
    float4 bias0;
    float4 dist0;
    float4 dist1;
    uint4 start0;
    uint4 start1;
};

struct Models
{
    SceneModel_1 models[1];
};

struct ChunkPairs
{
    uint2 chunkPairs[1];
};

struct SceneView_1
{
    float4 planes[6];
    uint4 meta;
    float4 clip;
    float4 sphere;
    float4 eye;
};

struct Views
{
    SceneView_1 views[1];
};

struct SceneChunk
{
    float4 lo;
    float4 hi;
    uint4 range;
};

struct SceneChunk_1
{
    float4 lo;
    float4 hi;
    uint4 range;
};

struct Chunks
{
    SceneChunk_1 chunks[1];
};

struct Counters
{
    uint counters[1];
};

struct Matrix
{
    uint matrix[1];
};

struct Lists
{
    uint lists[1];
};

struct SceneRun_1
{
    uint4 range;
};

struct Runs
{
    SceneRun_1 runs[1];
};

struct Pairs
{
    uint4 pairs[1];
};

struct PairWalk
{
    uint pairWalk[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
uint scene_matrix_at(thread const uint& first, thread const uint& n, thread const uint& k, thread const uint& cp, constant SceneCullParams& _299)
{
    return ((_299.u_counts.w * first) + (k * n)) + (cp - first);
}

static inline __attribute__((always_inline))
bool scene_box_front(thread const float4& p, thread const float3& lo, thread const float3& hi)
{
    float _123;
    if (p.x >= 0.0)
    {
        _123 = hi.x;
    }
    else
    {
        _123 = lo.x;
    }
    float _136;
    if (p.y >= 0.0)
    {
        _136 = hi.y;
    }
    else
    {
        _136 = lo.y;
    }
    float _149;
    if (p.z >= 0.0)
    {
        _149 = hi.z;
    }
    else
    {
        _149 = lo.z;
    }
    float3 corner = float3(_123, _136, _149);
    return ((((p.x * corner.x) + (p.y * corner.y)) + (p.z * corner.z)) + p.w) >= 0.0;
}

static inline __attribute__((always_inline))
bool scene_box_visible(thread const SceneView& v, thread const float3& lo, thread const float3& hi)
{
    for (int i = 0; i < 6; i++)
    {
        float4 param = v.planes[i];
        float3 param_1 = lo;
        float3 param_2 = hi;
        if (!scene_box_front(param, param_1, param_2))
        {
            return false;
        }
    }
    return true;
}

static inline __attribute__((always_inline))
bool scene_box_reached(thread const SceneView& v, thread const float3& lo, thread const float3& hi)
{
    bool _217 = (v.meta.z & 1u) != 0u;
    bool _229;
    if (_217)
    {
        float4 param = v.clip;
        float3 param_1 = lo;
        float3 param_2 = hi;
        _229 = !scene_box_front(param, param_1, param_2);
    }
    else
    {
        _229 = _217;
    }
    if (_229)
    {
        return false;
    }
    if ((v.meta.z & 2u) != 0u)
    {
        float3 c = v.sphere.xyz;
        if (length(fast::clamp(c, lo, hi) - c) > v.sphere.w)
        {
            return false;
        }
    }
    return true;
}

static inline __attribute__((always_inline))
bool scene_too_small(thread const SceneView& v, thread const float3& lo, thread const float3& hi, thread const float& r)
{
    if (v.eye.w <= 0.0)
    {
        return false;
    }
    float3 e = v.eye.xyz;
    return r < (v.eye.w * length(fast::clamp(e, lo, hi) - e));
}

static inline __attribute__((always_inline))
float scene_lod_distance(thread const SceneModel& m, thread const uint& i)
{
    if (i < 4u)
    {
        return m.dist0[i];
    }
    return m.dist1[i - 4u];
}

static inline __attribute__((always_inline))
uint scene_lod_start(thread const SceneModel& m, thread const uint& i)
{
    if (i < 4u)
    {
        return m.start0[i];
    }
    return m.start1[i - 4u];
}

static inline __attribute__((always_inline))
uint scene_depth_bin(thread const float& d)
{
    float b = floor(log2(fast::max(d, 1.0)) * 2.0) - 2.0;
    return uint(fast::clamp(b, 0.0, 15.0));
}

static inline __attribute__((always_inline))
uint3 member_runs(thread const uint& row, thread const SceneView& view, thread const uint& require, thread const bool& fromActive, constant SceneCullParams& _299, const device Instances& _355, const device Models& _456)
{
    SceneInstance _360;
    _360.lo = _355.instances[row].lo;
    _360.hi = _355.instances[row].hi;
    _360.meta = _355.instances[row].meta;
    _360.extra = _355.instances[row].extra;
    SceneInstance inst = _360;
    uint flags = inst.meta.y;
    if ((flags & require) != require)
    {
        return uint3(0u);
    }
    bool listed = (flags & 64u) != 0u;
    if (listed != fromActive)
    {
        return uint3(0u);
    }
    SceneView param = view;
    float3 param_1 = inst.lo.xyz;
    float3 param_2 = inst.hi.xyz;
    bool _395 = !scene_box_visible(param, param_1, param_2);
    bool _411;
    if (!_395)
    {
        SceneView param_3 = view;
        float3 param_4 = inst.lo.xyz;
        float3 param_5 = inst.hi.xyz;
        _411 = !scene_box_reached(param_3, param_4, param_5);
    }
    else
    {
        _411 = _395;
    }
    if (_411)
    {
        return uint3(0u);
    }
    float radius = length(inst.hi.xyz - inst.lo.xyz) * 0.5;
    bool _430 = radius < as_type<float>(view.meta.w);
    bool _447;
    if (!_430)
    {
        SceneView param_6 = view;
        float3 param_7 = inst.lo.xyz;
        float3 param_8 = inst.hi.xyz;
        float param_9 = radius;
        _447 = scene_too_small(param_6, param_7, param_8, param_9);
    }
    else
    {
        _447 = _430;
    }
    if (_447)
    {
        return uint3(0u);
    }
    SceneModel _462;
    _462.head = _456.models[inst.meta.x].head;
    _462.bias0 = _456.models[inst.meta.x].bias0;
    _462.dist0 = _456.models[inst.meta.x].dist0;
    _462.dist1 = _456.models[inst.meta.x].dist1;
    _462.start0 = _456.models[inst.meta.x].start0;
    _462.start1 = _456.models[inst.meta.x].start1;
    SceneModel m = _462;
    float3 eye = _299.u_eye.xyz;
    float dist = length(fast::clamp(eye, inst.lo.xyz, inst.hi.xyz) - eye);
    bool _482 = m.bias0.y > 0.0;
    bool _489;
    if (_482)
    {
        _489 = dist > m.bias0.y;
    }
    else
    {
        _489 = _482;
    }
    if (_489)
    {
        return uint3(0u);
    }
    float d = dist * ((m.bias0.x * inst.lo.w) * _299.u_eye.w);
    uint levels = m.head.x;
    uint level0 = 0u;
    for (uint i = 1u; i < levels; i++)
    {
        SceneModel param_10 = m;
        uint param_11 = i;
        if (d < scene_lod_distance(param_10, param_11))
        {
            break;
        }
        level0 = i;
    }
    SceneModel param_12 = m;
    uint param_13 = level0;
    SceneModel param_14 = m;
    uint param_15 = level0 + 1u;
    float param_16 = dist;
    return uint3(scene_lod_start(param_12, param_13), scene_lod_start(param_14, param_15), scene_depth_bin(param_16));
}

static inline __attribute__((always_inline))
uint run_key(thread const SceneRun& run, thread const uint& bin, constant SceneCullParams& _299)
{
    if (run.range.y == 0u)
    {
        return 4294967295u;
    }
    uint key = 0u;
    if (_299.u_mode.z == 0u)
    {
        key = run.range.w;
    }
    else
    {
        key = (run.range.z * _299.u_mode.z) + bin;
    }
    if (key >= _299.u_counts.w)
    {
        return 4294967295u;
    }
    return key;
}

kernel void cs(constant SceneCullParams& _299 [[buffer(2)]], const device ChunkPairs& _564 [[buffer(6)]], const device Chunks& _618 [[buffer(7)]], const device Lists& _738 [[buffer(8)]], const device Instances& _355 [[buffer(9)]], const device Models& _456 [[buffer(10)]], const device Runs& _774 [[buffer(11)]], const device Views& _578 [[buffer(12)]], device Matrix& _692 [[buffer(13)]], device Pairs& _955 [[buffer(14)]], const device Counters& _656 [[buffer(15)]], device PairWalk& _969 [[buffer(16)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    threadgroup uint s_base[256];
    threadgroup uint s_count[256];
    threadgroup uint s_offset[64];
    threadgroup uint s_keyOf[512];
    uint cp = gl_WorkGroupID.x;
    uint t = gl_LocalInvocationID.x;
    uint2 named = _564.chunkPairs[cp];
    uint v = named.y;
    SceneView _583;
    _583.planes[0] = _578.views[v].planes[0];
    _583.planes[1] = _578.views[v].planes[1];
    _583.planes[2] = _578.views[v].planes[2];
    _583.planes[3] = _578.views[v].planes[3];
    _583.planes[4] = _578.views[v].planes[4];
    _583.planes[5] = _578.views[v].planes[5];
    _583.meta = _578.views[v].meta;
    _583.clip = _578.views[v].clip;
    _583.sphere = _578.views[v].sphere;
    _583.eye = _578.views[v].eye;
    SceneView view = _583;
    uint pass = view.meta.x;
    uint keys = _299.u_counts.w;
    uint require = (_299.u_mode.y | view.meta.y) | 1u;
    bool fromActive = (named.x & 2147483648u) != 0u;
    uint first;
    uint count;
    if (fromActive)
    {
        uint block = named.x & 2147483647u;
        SceneChunk _622;
        _622.lo = _618.chunks[0].lo;
        _622.hi = _618.chunks[0].hi;
        _622.range = _618.chunks[0].range;
        SceneChunk set = _622;
        first = set.range.x + (block * 256u);
        count = min(256u, (_299.u_counts.y - (block * 256u)));
    }
    else
    {
        SceneChunk _643;
        _643.lo = _618.chunks[named.x].lo;
        _643.hi = _618.chunks[named.x].hi;
        _643.range = _618.chunks[named.x].range;
        SceneChunk c = _643;
        first = c.range.x;
        count = c.range.y;
    }
    bool writing = _299.u_mode.x == 1u;
    uint passFirst = _656.counters[265u + pass];
    uint passPairs = _656.counters[(265u + pass) + 1u] - passFirst;
    uint _686;
    for (uint k = t; k < keys; k += 64u)
    {
        if (writing)
        {
            uint param = passFirst;
            uint param_1 = passPairs;
            uint param_2 = k;
            uint param_3 = cp;
            _686 = _692.matrix[scene_matrix_at(param, param_1, param_2, param_3, _299)];
        }
        else
        {
            _686 = 0u;
        }
        s_base[k] = _686;
        s_count[k] = 0u;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    uint _810;
    for (uint i0 = 0u; i0 < count; i0 += 64u)
    {
        uint i = i0 + t;
        uint3 range = uint3(0u);
        uint row = 0u;
        if (i < count)
        {
            row = _738.lists[first + i];
            uint param_4 = row;
            SceneView param_5 = view;
            uint param_6 = require;
            bool param_7 = fromActive;
            range = member_runs(param_4, param_5, param_6, param_7, _299, _355, _456);
        }
        uint mine = 0u;
        for (uint r = range.x; (r < range.y) && (mine < 8u); r++)
        {
            SceneRun _780;
            _780.range = _774.runs[r].range;
            SceneRun param_8 = _780;
            uint param_9 = range.z;
            if (run_key(param_8, param_9, _299) != 4294967295u)
            {
                mine++;
            }
        }
        s_offset[t] = mine;
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint o = 1u; o < 64u; o = o << 1u)
        {
            if (t >= o)
            {
                _810 = s_offset[t - o];
            }
            else
            {
                _810 = 0u;
            }
            uint add = _810;
            threadgroup_barrier(mem_flags::mem_threadgroup);
            s_offset[t] += add;
            threadgroup_barrier(mem_flags::mem_threadgroup);
        }
        uint at = s_offset[t] - mine;
        uint n = 0u;
        for (uint r_1 = range.x; (r_1 < range.y) && (n < mine); r_1++)
        {
            SceneRun _856;
            _856.range = _774.runs[r_1].range;
            SceneRun param_10 = _856;
            uint param_11 = range.z;
            uint key = run_key(param_10, param_11, _299);
            if (key != 4294967295u)
            {
                s_keyOf[at + n] = key;
                uint _876 = atomic_fetch_add_explicit((threadgroup atomic_uint*)&s_count[key], 1u, memory_order_relaxed);
                n++;
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        if (writing)
        {
            n = 0u;
            for (uint r_2 = range.x; (r_2 < range.y) && (n < mine); r_2++)
            {
                SceneRun _904;
                _904.range = _774.runs[r_2].range;
                SceneRun run = _904;
                SceneRun param_12 = run;
                uint param_13 = range.z;
                uint key_1 = run_key(param_12, param_13, _299);
                if (key_1 == 4294967295u)
                {
                    continue;
                }
                uint rank = 0u;
                for (uint e = 0u; e < (at + n); e++)
                {
                    if (s_keyOf[e] == key_1)
                    {
                        rank++;
                    }
                }
                uint slot = s_base[key_1] + rank;
                if (slot < _299.u_caps.y)
                {
                    _955.pairs[slot] = uint4(row, v, run.range.x, run.range.y);
                    _969.pairWalk[slot] = run.range.y;
                }
                n++;
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
        for (uint k_1 = t; k_1 < keys; k_1 += 64u)
        {
            s_base[k_1] += s_count[k_1];
            s_count[k_1] = 0u;
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (!writing)
    {
        for (uint k_2 = t; k_2 < keys; k_2 += 64u)
        {
            uint param_14 = passFirst;
            uint param_15 = passPairs;
            uint param_16 = k_2;
            uint param_17 = cp;
            _692.matrix[scene_matrix_at(param_14, param_15, param_16, param_17, _299)] = s_base[k_2];
        }
    }
}

