// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct SceneModel
{
    uint4 head;
    float4 bias0;
    float4 dist0;
    float4 dist1;
    uint4 start0;
    uint4 start1;
};

struct SceneView
{
    spvUnsafeArray<float4, 6> planes;
    uint4 meta;
};

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_rows;
    uint4 u_limits;
};

struct SceneView_1
{
    float4 planes[6];
    uint4 meta;
};

struct Views
{
    SceneView_1 views[1];
};

struct SceneInstance
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct SceneInstance_1
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct Statics
{
    SceneInstance_1 statics[1];
};

struct Movers
{
    SceneInstance_1 movers[1];
};

struct SceneModel_1
{
    uint4 head;
    float4 bias0;
    float4 dist0;
    float4 dist1;
    uint4 start0;
    uint4 start1;
};

struct Models
{
    SceneModel_1 models[1];
};

struct Counters
{
    uint counters[1];
};

struct Pairs
{
    uint4 pairs[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
bool scene_box_visible(thread const SceneView& v, thread const float3& lo, thread const float3& hi)
{
    float _93;
    float _106;
    float _119;
    for (int i = 0; i < 6; i++)
    {
        float4 p = v.planes[i];
        if (p.x >= 0.0)
        {
            _93 = hi.x;
        }
        else
        {
            _93 = lo.x;
        }
        if (p.y >= 0.0)
        {
            _106 = hi.y;
        }
        else
        {
            _106 = lo.y;
        }
        if (p.z >= 0.0)
        {
            _119 = hi.z;
        }
        else
        {
            _119 = lo.z;
        }
        float3 corner = float3(_93, _106, _119);
        if (((((p.x * corner.x) + (p.y * corner.y)) + (p.z * corner.z)) + p.w) < 0.0)
        {
            return false;
        }
    }
    return true;
}

static inline __attribute__((always_inline))
float scene_lod_distance(thread const SceneModel& m, thread const uint& i)
{
    if (i < 4u)
    {
        return m.dist0[i];
    }
    return m.dist1[i - 4u];
}

static inline __attribute__((always_inline))
uint scene_lod_start(thread const SceneModel& m, thread const uint& i)
{
    if (i < 4u)
    {
        return m.start0[i];
    }
    return m.start1[i - 4u];
}

kernel void cs(constant SceneCullParams& _174 [[buffer(2)]], const device Statics& _222 [[buffer(6)]], const device Movers& _234 [[buffer(7)]], const device Models& _282 [[buffer(8)]], const device Views& _198 [[buffer(9)]], device Pairs& _395 [[buffer(10)]], device Counters& _380 [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint row = gl_GlobalInvocationID.x;
    uint view = gl_GlobalInvocationID.y;
    bool _181 = row >= (_174.u_rows.x + _174.u_rows.y);
    bool _189;
    if (!_181)
    {
        _189 = view >= _174.u_rows.z;
    }
    else
    {
        _189 = _181;
    }
    if (_189)
    {
        return;
    }
    if (((device uint*)&_198.views[view].meta)[0u] == 4294967295u)
    {
        return;
    }
    SceneInstance inst;
    uint id;
    if (row < _174.u_rows.x)
    {
        SceneInstance _227;
        _227.world = _222.statics[row].world;
        _227.lo = _222.statics[row].lo;
        _227.hi = _222.statics[row].hi;
        _227.meta = _222.statics[row].meta;
        inst = _227;
        id = row;
    }
    else
    {
        uint _238 = row - _174.u_rows.x;
        SceneInstance _241;
        _241.world = _234.movers[_238].world;
        _241.lo = _234.movers[_238].lo;
        _241.hi = _234.movers[_238].hi;
        _241.meta = _234.movers[_238].meta;
        inst = _241;
        id = (row - _174.u_rows.x) | 2147483648u;
    }
    uint need = 3u;
    if ((inst.meta.y & need) != need)
    {
        return;
    }
    SceneView _263;
    _263.planes[0] = _198.views[view].planes[0];
    _263.planes[1] = _198.views[view].planes[1];
    _263.planes[2] = _198.views[view].planes[2];
    _263.planes[3] = _198.views[view].planes[3];
    _263.planes[4] = _198.views[view].planes[4];
    _263.planes[5] = _198.views[view].planes[5];
    _263.meta = _198.views[view].meta;
    SceneView param = _263;
    float3 param_1 = inst.lo.xyz;
    float3 param_2 = inst.hi.xyz;
    if (!scene_box_visible(param, param_1, param_2))
    {
        return;
    }
    SceneModel _288;
    _288.head = _282.models[inst.meta.x].head;
    _288.bias0 = _282.models[inst.meta.x].bias0;
    _288.dist0 = _282.models[inst.meta.x].dist0;
    _288.dist1 = _282.models[inst.meta.x].dist1;
    _288.start0 = _282.models[inst.meta.x].start0;
    _288.start1 = _282.models[inst.meta.x].start1;
    SceneModel m = _288;
    float3 eye = _174.u_eye.xyz;
    float dist = length(fast::clamp(eye, inst.lo.xyz, inst.hi.xyz) - eye);
    bool _308 = m.bias0.y > 0.0;
    bool _315;
    if (_308)
    {
        _315 = dist > m.bias0.y;
    }
    else
    {
        _315 = _308;
    }
    if (_315)
    {
        return;
    }
    float d = dist * ((m.bias0.x * inst.lo.w) * _174.u_eye.w);
    uint levels = m.head.x;
    uint level0 = 0u;
    for (uint i = 1u; i < levels; i++)
    {
        SceneModel param_3 = m;
        uint param_4 = i;
        if (d < scene_lod_distance(param_3, param_4))
        {
            break;
        }
        level0 = i;
    }
    SceneModel param_5 = m;
    uint param_6 = level0;
    uint first = scene_lod_start(param_5, param_6);
    SceneModel param_7 = m;
    uint param_8 = level0 + 1u;
    uint end = scene_lod_start(param_7, param_8);
    if (end <= first)
    {
        return;
    }
    uint _382 = atomic_fetch_add_explicit((device atomic_uint*)&_380.counters[0], 1u, memory_order_relaxed);
    uint slot = _382;
    if (slot >= _174.u_limits.x)
    {
        uint _390 = atomic_fetch_add_explicit((device atomic_uint*)&_380.counters[1], 1u, memory_order_relaxed);
        return;
    }
    _395.pairs[slot] = uint4(id, view, first, end - first);
}

