// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_counts;
    uint4 u_caps;
    uint4 u_mode;
    uint4 u_debug;
    float4 u_grid;
    uint4 u_local;
};

struct Args
{
    uint args[1];
};

struct Counters
{
    uint counters[1];
};

struct Tiles
{
    uint tiles[1];
};

struct SceneView
{
    float4 planes[6];
    uint4 meta;
    float4 clip;
    float4 sphere;
    float4 eye;
};

struct Views
{
    SceneView views[1];
};

struct Matrix
{
    uint matrix[1];
};

struct PairWalk
{
    uint pairWalk[1];
};

struct WalkItems
{
    uint walkItems[1];
};

struct WalkTriangles
{
    uint walkTriangles[1];
};

struct PairItems
{
    uint pairItems[1];
};

struct PairTriangles
{
    uint pairTriangles[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(128u, 1u, 1u);

static inline __attribute__((always_inline))
uint scene_spatial_candidates(constant SceneCullParams& _34)
{
    if (_34.u_local.x > 0u)
    {
        return _34.u_local.x * _34.u_local.x;
    }
    return _34.u_counts.x;
}

static inline __attribute__((always_inline))
uint scene_active_blocks(constant SceneCullParams& _34)
{
    return ((_34.u_counts.y + 256u) - 1u) / 256u;
}

static inline __attribute__((always_inline))
uint scene_chunk_tiles(constant SceneCullParams& _34)
{
    return max((((scene_spatial_candidates(_34) + scene_active_blocks(_34)) + 255u) / 256u), 1u);
}

static inline __attribute__((always_inline))
void dispatch_args(thread const uint& at, thread const uint& groups, device Args& _109)
{
    _109.args[at] = groups;
    _109.args[at + 1u] = 1u;
    _109.args[at + 2u] = 1u;
    _109.args[at + 3u] = 0u;
}

static inline __attribute__((always_inline))
uint scene_draw_keys(constant SceneCullParams& _34)
{
    if (_34.u_mode.z == 0u)
    {
        return _34.u_counts.w;
    }
    return _34.u_counts.w / _34.u_mode.z;
}

static inline __attribute__((always_inline))
uint scene_matrix_at(thread const uint& first, thread const uint& n, thread const uint& k, thread const uint& cp, constant SceneCullParams& _34)
{
    return ((_34.u_counts.w * first) + (k * n)) + (cp - first);
}

kernel void cs(constant SceneCullParams& _34 [[buffer(2)]], device Counters& _154 [[buffer(6)]], device Args& _109 [[buffer(7)]], const device Matrix& _285 [[buffer(8)]], const device PairItems& _556 [[buffer(9)]], const device PairTriangles& _593 [[buffer(10)]], const device Tiles& _161 [[buffer(11)]], const device Views& _227 [[buffer(12)]], const device PairWalk& _324 [[buffer(13)]], const device WalkItems& _366 [[buffer(14)]], const device WalkTriangles& _382 [[buffer(15)]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    uint t = gl_LocalInvocationID.x;
    uint _step = _34.u_mode.x;
    if (_step == 0u)
    {
        uint perView = scene_chunk_tiles(_34);
        for (uint v = t; v <= _34.u_counts.z; v += 128u)
        {
            _154.counters[8u + v] = _161.tiles[v * perView];
        }
        if (t == 0u)
        {
            uint total = _161.tiles[_34.u_counts.z * perView];
            uint kept = min(total, _34.u_caps.x);
            _154.counters[0] = kept;
            _154.counters[4] = total - kept;
            uint param = 0u;
            uint param_1 = kept;
            dispatch_args(param, param_1, _109);
            uint v_1 = 0u;
            for (uint p = 0u; p < _34.u_mode.w; p++)
            {
                for (;;)
                {
                    bool _218 = v_1 < _34.u_counts.z;
                    bool _233;
                    if (_218)
                    {
                        _233 = ((device uint*)&_227.views[v_1].meta)[0u] != 4294967295u;
                    }
                    else
                    {
                        _233 = _218;
                    }
                    bool _241;
                    if (_233)
                    {
                        _241 = ((device uint*)&_227.views[v_1].meta)[0u] < p;
                    }
                    else
                    {
                        _241 = _233;
                    }
                    if (_241)
                    {
                        v_1++;
                        continue;
                    }
                    else
                    {
                        break;
                    }
                }
                _154.counters[265u + p] = min(_161.tiles[v_1 * perView], kept);
            }
            _154.counters[265u + _34.u_mode.w] = kept;
            _154.counters[271] = (_34.u_counts.w * kept) + 1u;
        }
        return;
    }
    uint chunkPairs = _154.counters[0];
    if (_step == 1u)
    {
        if (t == 0u)
        {
            uint total_1 = _285.matrix[_34.u_counts.w * chunkPairs];
            uint kept_1 = min(total_1, _34.u_caps.y);
            _154.counters[1] = kept_1;
            _154.counters[5] = total_1 - kept_1;
            _154.counters[272] = kept_1 + 1u;
        }
        return;
    }
    uint pairs = _154.counters[1];
    if (_step == 3u)
    {
        if (t == 0u)
        {
            uint total_2 = _324.pairWalk[pairs];
            uint walk = min(total_2, (_34.u_caps.z * 2u));
            uint groups = (walk + 63u) / 64u;
            _154.counters[273] = walk;
            _154.counters[274] = groups + 1u;
            _154.counters[6] = total_2 - walk;
            uint param_2 = 4u;
            uint param_3 = groups;
            dispatch_args(param_2, param_3, _109);
        }
        return;
    }
    uint groups_1 = (_154.counters[273] + 63u) / 64u;
    uint itemsTotal = min(_366.walkItems[groups_1], _34.u_caps.z);
    uint trianglesTotal = 0u;
    if (_34.u_mode.z != 0u)
    {
        trianglesTotal = min(_382.walkTriangles[groups_1], _34.u_caps.w);
    }
    if (t == 0u)
    {
        uint total_3 = _366.walkItems[groups_1];
        uint kept_2 = itemsTotal;
        _154.counters[2] = kept_2;
        _154.counters[6] += (total_3 - kept_2);
        uint triangles = 0u;
        if (_34.u_mode.z != 0u)
        {
            triangles = _382.walkTriangles[groups_1];
            uint tkept = min(triangles, _34.u_caps.w);
            _154.counters[3] = tkept;
            _154.counters[7] = triangles - tkept;
        }
        uint param_4 = 8u;
        uint param_5 = kept_2;
        dispatch_args(param_4, param_5, _109);
    }
    uint drawKeys = scene_draw_keys(_34);
    uint _439;
    if (_34.u_mode.z == 0u)
    {
        _439 = 1u;
    }
    else
    {
        _439 = _34.u_mode.z;
    }
    uint span = _439;
    uint draws = _34.u_mode.w * drawKeys;
    uint _550;
    uint _565;
    uint _587;
    uint _602;
    for (uint s = t; s < draws; s += 128u)
    {
        uint pass = s / drawKeys;
        uint key = (s - (pass * drawKeys)) * span;
        uint first = _154.counters[265u + pass];
        uint n = _154.counters[(265u + pass) + 1u] - first;
        uint param_6 = first;
        uint param_7 = n;
        uint param_8 = key;
        uint param_9 = first;
        uint m0 = scene_matrix_at(param_6, param_7, param_8, param_9, _34);
        uint param_10 = first;
        uint param_11 = n;
        uint param_12 = key + span;
        uint param_13 = first;
        uint m1 = scene_matrix_at(param_10, param_11, param_12, param_13, _34);
        uint p0 = min(_285.matrix[m0], pairs);
        uint p1 = min(_285.matrix[m1], pairs);
        uint walk_1 = _154.counters[273];
        bool _527 = p0 < pairs;
        bool _535;
        if (_527)
        {
            _535 = _324.pairWalk[p0] < walk_1;
        }
        else
        {
            _535 = _527;
        }
        bool in0 = _535;
        bool _539 = p1 < pairs;
        bool _547;
        if (_539)
        {
            _547 = _324.pairWalk[p1] < walk_1;
        }
        else
        {
            _547 = _539;
        }
        bool in1 = _547;
        if (in0)
        {
            _550 = _556.pairItems[p0];
        }
        else
        {
            _550 = itemsTotal;
        }
        uint i0 = _550;
        if (in1)
        {
            _565 = _556.pairItems[p1];
        }
        else
        {
            _565 = itemsTotal;
        }
        uint i1 = _565;
        uint at = 12u + (s * 5u);
        if (_34.u_mode.z != 0u)
        {
            if (in0)
            {
                _587 = _593.pairTriangles[p0];
            }
            else
            {
                _587 = trianglesTotal;
            }
            uint t0 = _587;
            if (in1)
            {
                _602 = _593.pairTriangles[p1];
            }
            else
            {
                _602 = trianglesTotal;
            }
            uint t1 = _602;
            _109.args[at] = (t1 - t0) * 3u;
            _109.args[at + 1u] = 1u;
            _109.args[at + 2u] = t0 * 3u;
            _109.args[at + 3u] = 0u;
            _109.args[at + 4u] = 0u;
        }
        else
        {
            _109.args[at] = (i1 - i0) * 192u;
            _109.args[at + 1u] = 1u;
            _109.args[at + 2u] = i0 * 192u;
            _109.args[at + 3u] = 0u;
            _109.args[at + 4u] = 0u;
        }
    }
}

