// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Args
{
    uint args[1];
};

struct Counters
{
    uint counters[1];
};

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_rows;
    uint4 u_limits;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

kernel void cs(const device Counters& _16 [[buffer(6)]], constant SceneCullParams& _25 [[buffer(2)]], device Args& _10 [[buffer(7)]])
{
    _10.args[0] = min(_16.counters[0], _25.u_limits.x);
    _10.args[1] = 1u;
    _10.args[2] = 1u;
    _10.args[3] = 0u;
}

