// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ScatterParams
{
    uint4 u_scatter;
};

struct Records
{
    uint records[1];
};

struct Table
{
    uint table[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

kernel void cs(constant ScatterParams& _20 [[buffer(2)]], device Table& _62 [[buffer(6)]], const device Records& _54 [[buffer(7)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint i = gl_GlobalInvocationID.x;
    uint rowWords = _20.u_scatter.x;
    if (i >= (rowWords * _20.u_scatter.y))
    {
        return;
    }
    uint record = i / rowWords;
    uint word = i % rowWords;
    uint base = record * (rowWords + 1u);
    uint row = _54.records[base];
    _62.table[(row * rowWords) + word] = _54.records[(base + 1u) + word];
}

