// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Items
{
    uint4 items[1];
};

struct SceneMeshlet
{
    float4 sphere;
    float4 cone;
    uint4 range;
    uint4 material;
};

struct SceneMeshlet_1
{
    float4 sphere;
    float4 cone;
    uint4 range;
    uint4 material;
};

struct Meshlets
{
    SceneMeshlet_1 meshlets[1];
};

struct SceneInstance
{
    float4 lo;
    float4 hi;
    uint4 meta;
    uint4 extra;
};

struct SceneInstance_1
{
    float4 lo;
    float4 hi;
    uint4 meta;
    uint4 extra;
};

struct Instances
{
    SceneInstance_1 instances[1];
};

struct SceneDrawItem
{
    uint4 head;
    uint4 extra;
};

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_counts;
    uint4 u_caps;
    uint4 u_mode;
    uint4 u_debug;
    float4 u_grid;
    uint4 u_local;
};

struct SceneDrawItem_1
{
    uint4 head;
    uint4 extra;
};

struct DrawItems
{
    SceneDrawItem_1 drawItems[1];
};

struct Detail
{
    uint detail[1];
};

struct Indices
{
    uint indices[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
uint2 debug_tint(thread const uint& id)
{
    uint h = id * 2654435761u;
    h ^= (h >> 15u);
    h *= 2246822519u;
    h ^= (h >> 13u);
    float hue = float(h & 65535u) / 65535.0;
    float3 c = fast::clamp(abs((fract(float3(hue) + float3(0.0, 0.666666686534881591796875, 0.3333333432674407958984375)) * 6.0) - float3(3.0)) - float3(1.0), float3(0.0), float3(1.0));
    c = mix(float3(1.0), c, float3(0.85000002384185791015625)) * 3.0;
    return uint2(as_type<uint>(half2(c.xy)), as_type<uint>(half2(float2(c.z, 1.0))));
}

kernel void cs(const device Items& _98 [[buffer(6)]], constant SceneCullParams& _168 [[buffer(2)]], const device Meshlets& _113 [[buffer(7)]], const device Detail& _217 [[buffer(8)]], device Indices& _232 [[buffer(9)]], const device Instances& _132 [[buffer(10)]], device DrawItems& _188 [[buffer(11)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    uint i = gl_WorkGroupID.x;
    uint t = gl_LocalInvocationID.x;
    uint4 item = _98.items[i];
    SceneMeshlet _119;
    _119.sphere = _113.meshlets[item.x].sphere;
    _119.cone = _113.meshlets[item.x].cone;
    _119.range = _113.meshlets[item.x].range;
    _119.material = _113.meshlets[item.x].material;
    SceneMeshlet m = _119;
    if (t == 0u)
    {
        SceneInstance _139;
        _139.lo = _132.instances[item.y].lo;
        _139.hi = _132.instances[item.y].hi;
        _139.meta = _132.instances[item.y].meta;
        _139.extra = _132.instances[item.y].extra;
        SceneInstance inst = _139;
        SceneDrawItem d;
        d.head = uint4(m.range.x, inst.meta.z, m.material.y, as_type<uint>(inst.hi.w));
        d.extra = uint4(inst.extra.x, inst.extra.y, inst.meta.y, 0u);
        if (_168.u_debug.x == 1u)
        {
            uint param = item.x;
            uint2 _179 = debug_tint(param);
            d.extra.x = _179.x;
            d.extra.y = _179.y;
        }
        SceneDrawItem_1 _193;
        _193.head = d.head;
        _193.extra = d.extra;
        _188.drawItems[i] = _193;
    }
    if (t >= m.range.z)
    {
        return;
    }
    uint at = item.w + t;
    if (at >= _168.u_caps.w)
    {
        return;
    }
    uint tri = _217.detail[m.range.y + t];
    uint name = i << 6u;
    _232.indices[at * 3u] = name | (tri & 255u);
    _232.indices[(at * 3u) + 1u] = name | ((tri >> 8u) & 255u);
    _232.indices[(at * 3u) + 2u] = name | ((tri >> 16u) & 255u);
}

