// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct SceneView
{
    spvUnsafeArray<float4, 6> planes;
    uint4 meta;
};

struct SceneCluster
{
    float4 sphere;
    uint4 range;
};

struct SceneCullParams
{
    float4 u_eye;
    uint4 u_rows;
    uint4 u_limits;
};

struct Pairs
{
    uint4 pairs[1];
};

struct SceneInstance
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct SceneInstance_1
{
    float4x4 world;
    float4 lo;
    float4 hi;
    uint4 meta;
};

struct Movers
{
    SceneInstance_1 movers[1];
};

struct Statics
{
    SceneInstance_1 statics[1];
};

struct SceneView_1
{
    float4 planes[6];
    uint4 meta;
};

struct Views
{
    SceneView_1 views[1];
};

struct SceneCluster_1
{
    float4 sphere;
    uint4 range;
};

struct Clusters
{
    SceneCluster_1 clusters[1];
};

struct Counters
{
    uint counters[1];
};

struct Items
{
    uint4 items[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
bool scene_sphere_behind(thread const float4& p, thread const float3& c, thread const float& r)
{
    return (dot(p.xyz, c) + p.w) < (-r);
}

static inline __attribute__((always_inline))
bool scene_sphere_visible(thread const SceneView& v, thread const float3& c, thread const float& r)
{
    for (int i = 0; i < 6; i++)
    {
        float4 param = v.planes[i];
        float3 param_1 = c;
        float param_2 = r;
        if (scene_sphere_behind(param, param_1, param_2))
        {
            return false;
        }
    }
    return true;
}

static inline __attribute__((always_inline))
bool cluster_kept(thread const SceneCluster& c, thread const SceneView& view, thread const float4x4& world, thread const float& scale, thread const bool& skinned, constant SceneCullParams& _102)
{
    uint bucket = c.range.z;
    bool _95 = bucket == 4294967295u;
    bool _107;
    if (!_95)
    {
        _107 = bucket >= _102.u_rows.w;
    }
    else
    {
        _107 = _95;
    }
    if (_107)
    {
        return false;
    }
    if (skinned)
    {
        return true;
    }
    float3 centre = (world * float4(c.sphere.xyz, 1.0)).xyz;
    SceneView param = view;
    float3 param_1 = centre;
    float param_2 = ((c.sphere.w * scale) * 1.00100004673004150390625) + 0.001000000047497451305389404296875;
    return scene_sphere_visible(param, param_1, param_2);
}

kernel void cs(constant SceneCullParams& _102 [[buffer(2)]], const device Pairs& _184 [[buffer(6)]], const device Clusters& _281 [[buffer(7)]], const device Statics& _216 [[buffer(8)]], const device Movers& _203 [[buffer(9)]], const device Views& _228 [[buffer(10)]], device Counters& _335 [[buffer(11)]], device Items& _447 [[buffer(12)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    threadgroup uint s_count[128];
    threadgroup uint s_base[128];
    uint p = gl_WorkGroupID.x;
    uint t = gl_LocalInvocationID.x;
    uint buckets = _102.u_rows.w;
    for (uint b = t; b < buckets; b += 64u)
    {
        s_count[b] = 0u;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    uint4 pair = _184.pairs[p];
    SceneInstance inst;
    if ((pair.x & 2147483648u) != 0u)
    {
        uint _207 = pair.x & 2147483647u;
        SceneInstance _211;
        _211.world = _203.movers[_207].world;
        _211.lo = _203.movers[_207].lo;
        _211.hi = _203.movers[_207].hi;
        _211.meta = _203.movers[_207].meta;
        inst = _211;
    }
    else
    {
        SceneInstance _221;
        _221.world = _216.statics[pair.x].world;
        _221.lo = _216.statics[pair.x].lo;
        _221.hi = _216.statics[pair.x].hi;
        _221.meta = _216.statics[pair.x].meta;
        inst = _221;
    }
    SceneView _235;
    _235.planes[0] = _228.views[pair.y].planes[0];
    _235.planes[1] = _228.views[pair.y].planes[1];
    _235.planes[2] = _228.views[pair.y].planes[2];
    _235.planes[3] = _228.views[pair.y].planes[3];
    _235.planes[4] = _228.views[pair.y].planes[4];
    _235.planes[5] = _228.views[pair.y].planes[5];
    _235.meta = _228.views[pair.y].meta;
    SceneView view = _235;
    uint pass = view.meta.x;
    float4x4 world = inst.world;
    float scale = fast::max(length(world[0].xyz), fast::max(length(world[1].xyz), length(world[2].xyz)));
    bool skinned = (inst.meta.y & 4u) != 0u;
    for (uint i = t; i < pair.w; i += 64u)
    {
        uint _285 = pair.z + i;
        SceneCluster _289;
        _289.sphere = _281.clusters[_285].sphere;
        _289.range = _281.clusters[_285].range;
        SceneCluster c = _289;
        SceneCluster param = c;
        SceneView param_1 = view;
        float4x4 param_2 = world;
        float param_3 = scale;
        bool param_4 = skinned;
        if (cluster_kept(param, param_1, param_2, param_3, param_4, _102))
        {
            uint _306 = atomic_fetch_add_explicit((threadgroup atomic_uint*)&s_count[c.range.z], 1u, memory_order_relaxed);
        }
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (_102.u_limits.z == 0u)
    {
        for (uint b_1 = t; b_1 < buckets; b_1 += 64u)
        {
            uint n = s_count[b_1];
            if (n > 0u)
            {
                uint _345 = atomic_fetch_add_explicit((device atomic_uint*)&_335.counters[(4u + (pass * buckets)) + b_1], n, memory_order_relaxed);
            }
        }
        return;
    }
    for (uint b_2 = t; b_2 < buckets; b_2 += 64u)
    {
        uint n_1 = s_count[b_2];
        if (n_1 > 0u)
        {
            uint _378 = atomic_fetch_add_explicit((device atomic_uint*)&_335.counters[(1028u + (pass * buckets)) + b_2], n_1, memory_order_relaxed);
            s_base[b_2] = _378;
        }
        s_count[b_2] = 0u;
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint i_1 = t; i_1 < pair.w; i_1 += 64u)
    {
        uint ci = pair.z + i_1;
        SceneCluster _404;
        _404.sphere = _281.clusters[ci].sphere;
        _404.range = _281.clusters[ci].range;
        SceneCluster c_1 = _404;
        SceneCluster param_5 = c_1;
        SceneView param_6 = view;
        float4x4 param_7 = world;
        float param_8 = scale;
        bool param_9 = skinned;
        if (!cluster_kept(param_5, param_6, param_7, param_8, param_9, _102))
        {
            continue;
        }
        uint b_3 = c_1.range.z;
        uint _429 = atomic_fetch_add_explicit((threadgroup atomic_uint*)&s_count[b_3], 1u, memory_order_relaxed);
        uint slot = s_base[b_3] + _429;
        if (slot < _335.counters[(2052u + (pass * buckets)) + b_3])
        {
            _447.items[slot] = uint4(ci, pair.x, pair.y, 0u);
        }
    }
}

