// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wunused-variable"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

// Implementation of the GLSL findLSB() function
template<typename T>
inline T spvFindLSB(T x)
{
    return select(ctz(x), T(-1), x == T(0));
}

struct VsmParams
{
    float4x4 u_vsm_view;
    float4 u_vsm_eye;
    float4 u_vsm_screen;
    float4 u_vsm_cluster_head;
    float4 u_vsm_cluster_z;
    uint4 u_vsm_counts;
    float4 u_vsm_shadow;
};

struct Requests
{
    uint requests[1];
};

struct Generations
{
    uint gens[1];
};

struct PageTable
{
    uint table[1];
};

struct Physical
{
    uint2 phys[1];
};

struct State
{
    uint state[1];
};

struct Misses
{
    uint misses[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
uint vsm_mip_offset(thread const uint& mip)
{
    if (mip == 0u)
    {
        return 0u;
    }
    if (mip == 1u)
    {
        return 256u;
    }
    if (mip == 2u)
    {
        return 320u;
    }
    if (mip == 3u)
    {
        return 336u;
    }
    return 340u;
}

static inline __attribute__((always_inline))
uint vsm_mip_side(thread const uint& mip)
{
    return 16u >> mip;
}

static inline __attribute__((always_inline))
void vsm_page_of(thread const uint& index, thread uint& face, thread uint& mip, thread uint2& page)
{
    face = index / 341u;
    uint rest = index % 341u;
    mip = 0u;
    if (rest >= 340u)
    {
        mip = 4u;
    }
    else
    {
        if (rest >= 336u)
        {
            mip = 3u;
        }
        else
        {
            if (rest >= 320u)
            {
                mip = 2u;
            }
            else
            {
                if (rest >= 256u)
                {
                    mip = 1u;
                }
            }
        }
    }
    uint param = mip;
    uint local = rest - vsm_mip_offset(param);
    uint param_1 = mip;
    uint side = vsm_mip_side(param_1);
    page = uint2(local % side, local / side);
}

kernel void cs(constant VsmParams& _117 [[buffer(2)]], const device Generations& _146 [[buffer(6)]], const device Requests& _133 [[buffer(7)]], const device PageTable& _191 [[buffer(8)]], device Physical& _210 [[buffer(9)]], device Misses& _247 [[buffer(10)]], device State& _234 [[buffer(11)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint word = gl_GlobalInvocationID.x;
    if (word >= (_117.u_vsm_counts.x * 64u))
    {
        return;
    }
    uint bits = _133.requests[word];
    uint slot = word / 64u;
    uint gen = _146.gens[slot] & 32767u;
    uint param_1;
    uint param_2;
    uint2 param_3;
    while (bits != 0u)
    {
        uint b = uint(int(spvFindLSB(bits)));
        bits &= (bits - 1u);
        uint page = ((word - (slot * 64u)) * 32u) + b;
        if (page >= 2046u)
        {
            continue;
        }
        uint key = (slot * 2046u) + page;
        uint entry = _191.table[key];
        bool _197 = entry != 4294967295u;
        bool _204;
        if (_197)
        {
            _204 = (entry >> 16u) == gen;
        }
        else
        {
            _204 = _197;
        }
        if (_204)
        {
            ((device uint*)&_210.phys[entry & 65535u])[1u] = _117.u_vsm_counts.y;
            continue;
        }
        uint param = page;
        vsm_page_of(param, param_1, param_2, param_3);
        uint face = param_1;
        uint mip = param_2;
        uint2 xy = param_3;
        uint _238 = atomic_fetch_add_explicit((device atomic_uint*)&_234.state[4u + mip], 1u, memory_order_relaxed);
        uint at = _238;
        if (at < 16384u)
        {
            _247.misses[(mip * 16384u) + at] = key;
        }
        else
        {
            uint _257 = atomic_fetch_add_explicit((device atomic_uint*)&_234.state[13], 1u, memory_order_relaxed);
        }
    }
}

