// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct PageTable
{
    uint table[1];
};

struct VsmParams
{
    float4x4 u_vsm_view;
    float4 u_vsm_eye;
    float4 u_vsm_screen;
    float4 u_vsm_cluster_head;
    float4 u_vsm_cluster_z;
    uint4 u_vsm_counts;
    float4 u_vsm_shadow;
};

struct ChangedLights
{
    uint changedSlots[1];
};

struct Generations
{
    uint gens[1];
};

struct LightGpu
{
    float4 position_radius;
    float4 color_intensity;
    float4 source;
    float4 flicker;
};

struct LightTableBuffer
{
    LightGpu lights[1];
};

struct Boxes
{
    float4 boxes[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(64u, 1u, 1u);

static inline __attribute__((always_inline))
uint vsm_mip_side(thread const uint& mip)
{
    return 16u >> mip;
}

static inline __attribute__((always_inline))
uint2 vsm_page_xy(thread const float2& f, thread const uint& mip)
{
    uint param = mip;
    uint side = vsm_mip_side(param);
    float2 uv = fast::clamp((f * 0.5) + float2(0.5), float2(0.0), float2(0.999989986419677734375));
    return min(uint2(uv * float(side)), uint2(side - 1u));
}

static inline __attribute__((always_inline))
uint vsm_mip_offset(thread const uint& mip)
{
    if (mip == 0u)
    {
        return 0u;
    }
    if (mip == 1u)
    {
        return 256u;
    }
    if (mip == 2u)
    {
        return 320u;
    }
    if (mip == 3u)
    {
        return 336u;
    }
    return 340u;
}

static inline __attribute__((always_inline))
uint vsm_page_index(thread const uint& face, thread const uint& mip, thread const uint2& page)
{
    uint param = mip;
    uint param_1 = mip;
    return (((face * 341u) + vsm_mip_offset(param)) + (page.y * vsm_mip_side(param_1))) + page.x;
}

static inline __attribute__((always_inline))
void clear_rect(thread const uint& slot, thread const uint& face, thread const float4& r, device PageTable& _242)
{
    for (uint m = 0u; m < 5u; m++)
    {
        float2 param = r.xy;
        uint param_1 = m;
        uint2 lo = vsm_page_xy(param, param_1);
        float2 param_2 = r.zw;
        uint param_3 = m;
        uint2 hi = vsm_page_xy(param_2, param_3);
        for (uint y = lo.y; y <= hi.y; y++)
        {
            for (uint x = lo.x; x <= hi.x; x++)
            {
                uint param_4 = face;
                uint param_5 = m;
                uint2 param_6 = uint2(x, y);
                _242.table[(slot * 2046u) + vsm_page_index(param_4, param_5, param_6)] = 4294967295u;
            }
        }
    }
}

static inline __attribute__((always_inline))
void vsm_basis(thread const uint& face, thread float3& n, thread float3& r, thread float3& u)
{
    if (face == 0u)
    {
        n = float3(1.0, 0.0, 0.0);
        r = float3(0.0, 0.0, -1.0);
        u = float3(0.0, 1.0, 0.0);
    }
    else
    {
        if (face == 1u)
        {
            n = float3(-1.0, 0.0, 0.0);
            r = float3(0.0, 0.0, 1.0);
            u = float3(0.0, 1.0, 0.0);
        }
        else
        {
            if (face == 2u)
            {
                n = float3(0.0, 1.0, 0.0);
                r = float3(1.0, 0.0, 0.0);
                u = float3(0.0, 0.0, -1.0);
            }
            else
            {
                if (face == 3u)
                {
                    n = float3(0.0, -1.0, 0.0);
                    r = float3(1.0, 0.0, 0.0);
                    u = float3(0.0, 0.0, 1.0);
                }
                else
                {
                    if (face == 4u)
                    {
                        n = float3(0.0, 0.0, 1.0);
                        r = float3(1.0, 0.0, 0.0);
                        u = float3(0.0, 1.0, 0.0);
                    }
                    else
                    {
                        n = float3(0.0, 0.0, -1.0);
                        r = float3(-1.0, 0.0, 0.0);
                        u = float3(0.0, 1.0, 0.0);
                    }
                }
            }
        }
    }
}

static inline __attribute__((always_inline))
float3 vsm_view(thread const uint& face, thread const float3& d)
{
    uint param = face;
    float3 param_1;
    float3 param_2;
    float3 param_3;
    vsm_basis(param, param_1, param_2, param_3);
    float3 n = param_1;
    float3 r = param_2;
    float3 u = param_3;
    return float3(dot(d, r), dot(d, u), dot(d, n));
}

kernel void cs(constant VsmParams& _280 [[buffer(2)]], const device LightTableBuffer& _334 [[buffer(6)]], device Generations& _319 [[buffer(7)]], const device Boxes& _360 [[buffer(8)]], device PageTable& _242 [[buffer(9)]], const device ChangedLights& _308 [[buffer(10)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    uint slot = gl_GlobalInvocationID.x;
    if (slot >= _280.u_vsm_counts.x)
    {
        return;
    }
    uint changed = uint(_280.u_vsm_shadow.y + 0.5);
    for (uint i = 0u; i < changed; i++)
    {
        if (_308.changedSlots[i] == slot)
        {
            _319.gens[slot]++;
            return;
        }
    }
    float4 pr = _334.lights[slot].position_radius;
    if (pr.w <= 0.0)
    {
        return;
    }
    float _460;
    float _472;
    float _484;
    for (uint b = 0u; b < _280.u_vsm_counts.w; b++)
    {
        float3 lo = _360.boxes[b * 2u].xyz;
        float3 hi = _360.boxes[(b * 2u) + 1u].xyz;
        float3 closest = fast::clamp(pr.xyz, lo, hi);
        float3 d = closest - pr.xyz;
        if (dot(d, d) > (pr.w * pr.w))
        {
            continue;
        }
        bool _401 = all(pr.xyz >= lo);
        bool _409;
        if (_401)
        {
            _409 = all(pr.xyz <= hi);
        }
        else
        {
            _409 = _401;
        }
        if (_409)
        {
            for (uint face = 0u; face < 6u; face++)
            {
                uint param = slot;
                uint param_1 = face;
                float4 param_2 = float4(-1.0, -1.0, 1.0, 1.0);
                clear_rect(param, param_1, param_2, _242);
            }
            continue;
        }
        for (uint face_1 = 0u; face_1 < 6u; face_1++)
        {
            float4 r = float4(1000000000.0, 1000000000.0, -1000000000.0, -1000000000.0);
            bool front = false;
            bool behind = false;
            for (uint c = 0u; c < 8u; c++)
            {
                if ((c & 1u) != 0u)
                {
                    _460 = hi.x;
                }
                else
                {
                    _460 = lo.x;
                }
                if ((c & 2u) != 0u)
                {
                    _472 = hi.y;
                }
                else
                {
                    _472 = lo.y;
                }
                if ((c & 4u) != 0u)
                {
                    _484 = hi.z;
                }
                else
                {
                    _484 = lo.z;
                }
                float3 corner = float3(_460, _472, _484);
                uint param_3 = face_1;
                float3 param_4 = corner - pr.xyz;
                float3 v = vsm_view(param_3, param_4);
                if (v.z <= 0.0500000007450580596923828125)
                {
                    behind = true;
                    continue;
                }
                front = true;
                float2 f = v.xy / float2(v.z);
                float4 _518 = r;
                float2 _521 = fast::min(_518.xy, f);
                r.x = _521.x;
                r.y = _521.y;
                float4 _526 = r;
                float2 _529 = fast::max(_526.zw, f);
                r.z = _529.x;
                r.w = _529.y;
            }
            if (!front)
            {
                continue;
            }
            if (behind)
            {
                r = float4(-1.0, -1.0, 1.0, 1.0);
            }
            bool _546 = r.x > 1.0;
            bool _553;
            if (!_546)
            {
                _553 = r.y > 1.0;
            }
            else
            {
                _553 = _546;
            }
            bool _560;
            if (!_553)
            {
                _560 = r.z < (-1.0);
            }
            else
            {
                _560 = _553;
            }
            bool _567;
            if (!_560)
            {
                _567 = r.w < (-1.0);
            }
            else
            {
                _567 = _560;
            }
            if (_567)
            {
                continue;
            }
            uint param_5 = slot;
            uint param_6 = face_1;
            float4 param_7 = fast::clamp(r, float4(-1.0), float4(1.0));
            clear_rect(param_5, param_6, param_7, _242);
        }
    }
}

