// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Atlas
{
    float atlas[1];
};

struct Dirty
{
    uint4 dirty[1];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(256u, 1u, 1u);

struct VsmParams
{
    float4x4 u_vsm_view;
    float4 u_vsm_eye;
    float4 u_vsm_screen;
    float4 u_vsm_cluster_head;
    float4 u_vsm_cluster_z;
    uint4 u_vsm_counts;
    float4 u_vsm_shadow;
};

kernel void cs(const device Dirty& _66 [[buffer(6)]], device Atlas& _59 [[buffer(7)]], texture2d<float> scratch [[texture(0)]], sampler scratchSmplr [[sampler(0)]], uint3 gl_WorkGroupID [[threadgroup_position_in_grid]], uint3 gl_LocalInvocationID [[thread_position_in_threadgroup]])
{
    uint k = gl_WorkGroupID.x / 17u;
    uint i = ((gl_WorkGroupID.x % 17u) * 256u) + gl_LocalInvocationID.x;
    if (i >= 4356u)
    {
        return;
    }
    uint2 cell = uint2(k % 16u, k / 16u) * uint2(66u);
    uint2 p = cell + uint2(i % 66u, i / 66u);
    _59.atlas[(((device uint*)&_66.dirty[k])[0u] * 4356u) + i] = scratch.read(uint2(int2(int(p.x), int(1055u - p.y))), 0).x;
}

