// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

// Implementation of the GLSL mod() function, which is slightly different than Metal fmod()
template<typename Tx, typename Ty>
inline Tx mod(Tx x, Ty y)
{
    return x - y * floor(x / y);
}

struct SkyScatter
{
    float3 sun_r;
    float3 sun_m;
    float3 moon_r;
    float3 moon_m;
    float3 transmittance;
    float3 depth;
    float t_ground;
};

struct SkyUniforms
{
    float4 u_sky_sun;
    float4 u_sky_origin;
    float4 u_sky_rayleigh;
    float4 u_sky_mie;
    float4 u_sky_ground;
    float4 u_sky_params;
    float4 u_sky_moon;
    float4 u_sky_moon_params;
    float4 u_sky_moon_color;
    float4 u_sky_ozone;
};

struct fs_out
{
    float4 aerial_light [[color(0)]];
    float4 aerial_sun_m [[color(1)]];
};

static inline __attribute__((always_inline))
float3 aerial_dir(thread const float& v, thread const float& i)
{
    float c = (2.0 * v) - 1.0;
    float y = (sign(c) * c) * c;
    float azimuth = ((((i + 0.5) / 64.0) - 0.5) * 2.0) * 3.1415927410125732421875;
    float ce = sqrt(fast::max(1.0 - (y * y), 0.0));
    return float3(ce * cos(azimuth), y, ce * sin(azimuth));
}

static inline __attribute__((always_inline))
float aerial_slice_distance(thread const float& k)
{
    float x = (k + 1.0) / 32.0;
    return (64000.0 * x) * x;
}

static inline __attribute__((always_inline))
float3 sky_observer(constant SkyUniforms& _104)
{
    return float3(0.0, _104.u_sky_params.z + fast::max(_104.u_sky_origin.y, 1.0), 0.0);
}

static inline __attribute__((always_inline))
float2 sky_ray_sphere(thread const float3& o, thread const float3& d, thread const float& r)
{
    float b = dot(o, d);
    float c = dot(o, o) - (r * r);
    float disc = (b * b) - c;
    if (disc < 0.0)
    {
        return float2(-1.0);
    }
    float s = sqrt(disc);
    return float2((-b) - s, (-b) + s);
}

static inline __attribute__((always_inline))
float3 sky_density(thread const float& h, constant SkyUniforms& _104)
{
    float2 scale = float2(_104.u_sky_rayleigh.w, _104.u_sky_mie.w);
    float2 rm = exp(float2(-h) / scale);
    float ozone = fast::max(1.0 - (abs(h - 25000.0) / 15000.0), 0.0);
    return float3(rm, ozone);
}

static inline __attribute__((always_inline))
float3 sky_optical_depth(thread const float3& p, thread const float3& d, thread const float& len, thread const int& samples, constant SkyUniforms& _104)
{
    float step_len = len / float(samples);
    float3 depth = float3(0.0);
    for (int i = 0; i < samples; i++)
    {
        float3 s = p + (d * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(s) - _104.u_sky_params.z, 0.0);
        float param = h;
        depth += (sky_density(param, _104) * step_len);
    }
    return depth;
}

static inline __attribute__((always_inline))
float3 sky_extinction(thread const float3& depth, constant SkyUniforms& _104)
{
    return exp(-(((_104.u_sky_rayleigh.xyz * depth.x) + (float3(_104.u_sky_mie.y) * depth.y)) + (_104.u_sky_ozone.xyz * depth.z)));
}

static inline __attribute__((always_inline))
SkyScatter sky_scatter_to(thread const float3& dir, thread const float& limit, thread const int& view_samples, thread const int& light_samples, constant SkyUniforms& _104)
{
    float3 o = sky_observer(_104);
    float rg = _104.u_sky_params.z;
    float rt = _104.u_sky_params.w;
    float3 param = o;
    float3 param_1 = dir;
    float param_2 = rt;
    float2 atmo = sky_ray_sphere(param, param_1, param_2);
    float t_max = fast::max(atmo.y, 0.0);
    float3 param_3 = o;
    float3 param_4 = dir;
    float param_5 = rg;
    float2 ground = sky_ray_sphere(param_3, param_4, param_5);
    SkyScatter s;
    s.t_ground = -1.0;
    if (ground.x > 0.0)
    {
        s.t_ground = ground.x;
        t_max = ground.x;
    }
    t_max = fast::min(t_max, limit);
    bool midpoint = _104.u_sky_ozone.w > 0.5;
    float n = float(view_samples);
    float step_len = t_max / n;
    float3 to_sun = _104.u_sky_sun.xyz;
    float3 sum_r = float3(0.0);
    float3 sum_m = float3(0.0);
    float3 depth_view = float3(0.0);
    bool moon_on = _104.u_sky_moon.w > 0.0;
    float3 to_moon = _104.u_sky_moon.xyz;
    float3 moon_r = float3(0.0);
    float3 moon_m = float3(0.0);
    for (int i = 0; i < view_samples; i++)
    {
        float t = (float(i) + 0.5) * step_len;
        float dt = step_len;
        if (midpoint)
        {
            float a = float(i) / n;
            float b = float(i + 1) / n;
            t = (t_max * 0.5) * ((a * a) + (b * b));
            dt = t_max * ((b * b) - (a * a));
        }
        float3 p = o + (dir * t);
        float h = fast::max(length(p) - rg, 0.0);
        float param_6 = h;
        float3 dens = sky_density(param_6, _104) * dt;
        float3 depth_here = depth_view + dens;
        if (midpoint)
        {
            depth_here = depth_view + (dens * 0.5);
        }
        depth_view += dens;
        bool _396;
        if (moon_on)
        {
            float3 param_7 = p;
            float3 param_8 = to_moon;
            float param_9 = rg;
            _396 = sky_ray_sphere(param_7, param_8, param_9).x <= 0.0;
        }
        else
        {
            _396 = moon_on;
        }
        if (_396)
        {
            float3 param_10 = p;
            float3 param_11 = to_moon;
            float param_12 = rt;
            float2 moon_atmo = sky_ray_sphere(param_10, param_11, param_12);
            float3 param_13 = p;
            float3 param_14 = to_moon;
            float param_15 = fast::max(moon_atmo.y, 0.0);
            int param_16 = light_samples;
            float3 moon_depth = sky_optical_depth(param_13, param_14, param_15, param_16, _104);
            float3 param_17 = depth_here + moon_depth;
            float3 tm = sky_extinction(param_17, _104);
            moon_r += (tm * dens.x);
            moon_m += (tm * dens.y);
        }
        float3 param_18 = p;
        float3 param_19 = to_sun;
        float param_20 = rg;
        float2 sun_ground = sky_ray_sphere(param_18, param_19, param_20);
        if (sun_ground.x > 0.0)
        {
            continue;
        }
        float3 param_21 = p;
        float3 param_22 = to_sun;
        float param_23 = rt;
        float2 sun_atmo = sky_ray_sphere(param_21, param_22, param_23);
        float3 param_24 = p;
        float3 param_25 = to_sun;
        float param_26 = fast::max(sun_atmo.y, 0.0);
        int param_27 = light_samples;
        float3 depth_light = sky_optical_depth(param_24, param_25, param_26, param_27, _104);
        float3 param_28 = depth_here + depth_light;
        float3 t_light = sky_extinction(param_28, _104);
        sum_r += (t_light * dens.x);
        sum_m += (t_light * dens.y);
    }
    float3 param_29 = depth_view;
    s.transmittance = sky_extinction(param_29, _104);
    s.depth = depth_view;
    s.sun_r = sum_r * _104.u_sky_rayleigh.xyz;
    s.sun_m = sum_m * float3(_104.u_sky_mie.x);
    s.moon_r = moon_r * _104.u_sky_rayleigh.xyz;
    s.moon_m = moon_m * float3(_104.u_sky_mie.x);
    return s;
}

static inline __attribute__((always_inline))
float sky_phase_rayleigh(thread const float& mu)
{
    return 0.0596831031143665313720703125 * (1.0 + (mu * mu));
}

static inline __attribute__((always_inline))
float sky_phase_mie(thread const float& mu, constant SkyUniforms& _104)
{
    float g = _104.u_sky_mie.z;
    float gg = g * g;
    return (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / ((2.0 + gg) * pow((1.0 + gg) - ((2.0 * g) * mu), 1.5));
}

fragment fs_out fs(constant SkyUniforms& _104 [[buffer(4)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float column = floor(gl_FragCoord.x);
    float k = floor(column / 66.0);
    float local = column - (k * 66.0);
    float i = mod((local - 1.0) + 64.0, 64.0);
    float param = gl_FragCoord.y / 32.0;
    float param_1 = i;
    float3 dir = aerial_dir(param, param_1);
    float param_2 = k;
    float3 param_3 = dir;
    float param_4 = aerial_slice_distance(param_2);
    int param_5 = int(_104.u_sky_params.x);
    int param_6 = int(_104.u_sky_params.y);
    SkyScatter s = sky_scatter_to(param_3, param_4, param_5, param_6, _104);
    float scale = 4.0 * _104.u_sky_ground.w;
    float mu = dot(dir, _104.u_sky_sun.xyz);
    float param_7 = mu;
    float3 light = (s.sun_r * (_104.u_sky_sun.w * scale)) * sky_phase_rayleigh(param_7);
    if (_104.u_sky_moon.w > 0.0)
    {
        float mu_m = dot(dir, _104.u_sky_moon.xyz);
        float param_8 = mu_m;
        float param_9 = mu_m;
        light += ((_104.u_sky_moon_color.xyz * (_104.u_sky_moon.w * scale)) * ((s.moon_r * sky_phase_rayleigh(param_8)) + (s.moon_m * sky_phase_mie(param_9, _104))));
    }
    float rayleigh_depth = s.depth.x;
    float mie_depth = s.depth.y;
    out.aerial_light = float4(fast::min(light, float3(65504.0)), fast::min(rayleigh_depth, 65504.0));
    out.aerial_sun_m = float4(fast::min(s.sun_m * (_104.u_sky_sun.w * scale), float3(65504.0)), fast::min(mie_depth, 65504.0));
    return out;
}

