// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SkyUniforms
{
    float4 u_sky_sun;
    float4 u_sky_origin;
    float4 u_sky_rayleigh;
    float4 u_sky_mie;
    float4 u_sky_ground;
    float4 u_sky_params;
};

struct fs_out
{
    float4 frag_color [[color(0)]];
};

struct fs_in
{
    float3 v_position [[user(locn0)]];
};

static inline __attribute__((always_inline))
float3 sky_observer(constant SkyUniforms& _105)
{
    return float3(0.0, _105.u_sky_params.z + fast::max(_105.u_sky_origin.y, 1.0), 0.0);
}

static inline __attribute__((always_inline))
float2 sky_ray_sphere(thread const float3& o, thread const float3& d, thread const float& r)
{
    float b = dot(o, d);
    float c = dot(o, o) - (r * r);
    float disc = (b * b) - c;
    if (disc < 0.0)
    {
        return float2(-1.0);
    }
    float s = sqrt(disc);
    return float2((-b) - s, (-b) + s);
}

static inline __attribute__((always_inline))
float2 sky_optical_depth(thread const float3& p, thread const float3& d, thread const float& len, thread const int& samples, constant SkyUniforms& _105)
{
    float step_len = len / float(samples);
    float2 depth = float2(0.0);
    float2 scale = float2(_105.u_sky_rayleigh.w, _105.u_sky_mie.w);
    for (int i = 0; i < samples; i++)
    {
        float3 s = p + (d * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(s) - _105.u_sky_params.z, 0.0);
        depth += (exp(float2(-h) / scale) * step_len);
    }
    return depth;
}

static inline __attribute__((always_inline))
float3 sky_extinction(thread const float2& depth, constant SkyUniforms& _105)
{
    return exp(-((_105.u_sky_rayleigh.xyz * depth.x) + (float3(_105.u_sky_mie.y) * depth.y)));
}

static inline __attribute__((always_inline))
float3 sky_inscatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _105)
{
    float3 o = sky_observer(_105);
    float rg = _105.u_sky_params.z;
    float rt = _105.u_sky_params.w;
    float3 param = o;
    float3 param_1 = dir;
    float param_2 = rt;
    float2 atmo = sky_ray_sphere(param, param_1, param_2);
    float t_max = fast::max(atmo.y, 0.0);
    float3 param_3 = o;
    float3 param_4 = dir;
    float param_5 = rg;
    float2 ground = sky_ray_sphere(param_3, param_4, param_5);
    t_ground = -1.0;
    if (ground.x > 0.0)
    {
        t_ground = ground.x;
        t_max = ground.x;
    }
    float step_len = t_max / float(view_samples);
    float3 to_sun = _105.u_sky_sun.xyz;
    float mu = dot(dir, to_sun);
    float g = _105.u_sky_mie.z;
    float gg = g * g;
    float phase_r = 0.0596831031143665313720703125 * (1.0 + (mu * mu));
    float phase_m = (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / ((2.0 + gg) * pow((1.0 + gg) - ((2.0 * g) * mu), 1.5));
    float2 scale = float2(_105.u_sky_rayleigh.w, _105.u_sky_mie.w);
    float3 sum_r = float3(0.0);
    float3 sum_m = float3(0.0);
    float2 depth_view = float2(0.0);
    for (int i = 0; i < view_samples; i++)
    {
        float3 p = o + (dir * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(p) - rg, 0.0);
        float2 dens = exp(float2(-h) / scale) * step_len;
        depth_view += dens;
        float3 param_6 = p;
        float3 param_7 = to_sun;
        float param_8 = rg;
        float2 sun_ground = sky_ray_sphere(param_6, param_7, param_8);
        if (sun_ground.x > 0.0)
        {
            continue;
        }
        float3 param_9 = p;
        float3 param_10 = to_sun;
        float param_11 = rt;
        float2 sun_atmo = sky_ray_sphere(param_9, param_10, param_11);
        float3 param_12 = p;
        float3 param_13 = to_sun;
        float param_14 = fast::max(sun_atmo.y, 0.0);
        int param_15 = light_samples;
        float2 depth_light = sky_optical_depth(param_12, param_13, param_14, param_15, _105);
        float2 param_16 = depth_view + depth_light;
        float3 t = sky_extinction(param_16, _105);
        sum_r += (t * dens.x);
        sum_m += (t * dens.y);
    }
    float2 param_17 = depth_view;
    transmittance = sky_extinction(param_17, _105);
    return (((sum_r * _105.u_sky_rayleigh.xyz) * phase_r) + ((sum_m * float3(_105.u_sky_mie.x)) * phase_m)) * (_105.u_sky_sun.w * 4.0);
}

static inline __attribute__((always_inline))
float3 sky_inscatter(thread const float3& dir, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _105)
{
    float3 param = dir;
    int param_1 = int(_105.u_sky_params.x);
    int param_2 = int(_105.u_sky_params.y);
    float3 param_3;
    float param_4;
    float3 _469 = sky_inscatter_n(param, param_1, param_2, param_3, param_4, _105);
    transmittance = param_3;
    t_ground = param_4;
    return _469;
}

static inline __attribute__((always_inline))
float3 sky_sun_disk(thread const float3& dir, thread const float3& transmittance, constant SkyUniforms& _105)
{
    float3 to_sun = _105.u_sky_sun.xyz;
    if (dot(dir, to_sun) <= 0.0)
    {
        return float3(0.0);
    }
    float angle = length(cross(dir, to_sun));
    float disk = 1.0 - smoothstep(0.0037819999270141124725341796875, 0.004652000032365322113037109375, angle);
    if (disk <= 0.0)
    {
        return float3(0.0);
    }
    float x = fast::min(angle / 0.004652000032365322113037109375, 1.0);
    float limb = 1.0 - (0.60000002384185791015625 * (1.0 - sqrt(fast::max(1.0 - (x * x), 0.0))));
    return transmittance * (((_105.u_sky_sun.w * 500.0) * disk) * limb);
}

static inline __attribute__((always_inline))
float3 sky_transmittance_from(thread const float3& p, thread const float3& to_sun, constant SkyUniforms& _105)
{
    float3 param = p;
    float3 param_1 = to_sun;
    float param_2 = _105.u_sky_params.z;
    float2 ground = sky_ray_sphere(param, param_1, param_2);
    if (ground.x > 0.0)
    {
        return float3(0.0);
    }
    float3 param_3 = p;
    float3 param_4 = to_sun;
    float param_5 = _105.u_sky_params.w;
    float2 atmo = sky_ray_sphere(param_3, param_4, param_5);
    float3 param_6 = p;
    float3 param_7 = to_sun;
    float param_8 = fast::max(atmo.y, 0.0);
    int param_9 = int(_105.u_sky_params.y);
    float2 depth = sky_optical_depth(param_6, param_7, param_8, param_9, _105);
    float2 param_10 = depth;
    return sky_extinction(param_10, _105);
}

static inline __attribute__((always_inline))
float3 sky_radiance(thread const float3& dir, constant SkyUniforms& _105)
{
    float3 param = dir;
    float3 param_1;
    float param_2;
    float3 _535 = sky_inscatter(param, param_1, param_2, _105);
    float3 transmittance = param_1;
    float t_ground = param_2;
    float3 color = _535;
    if (t_ground < 0.0)
    {
        if (_105.u_sky_origin.w > 0.5)
        {
            float3 param_3 = dir;
            float3 param_4 = transmittance;
            color += sky_sun_disk(param_3, param_4, _105);
        }
        return color * _105.u_sky_ground.w;
    }
    float3 p = sky_observer(_105) + (dir * t_ground);
    float3 n = fast::normalize(p);
    float3 to_sun = _105.u_sky_sun.xyz;
    float3 param_5 = p;
    float3 param_6 = to_sun;
    float3 sun = sky_transmittance_from(param_5, param_6, _105) * ((_105.u_sky_sun.w * fast::max(dot(n, to_sun), 0.0)) / 3.1415927410125732421875);
    float3 mirrored = reflect(dir, n);
    float3 param_7 = mirrored;
    float3 param_8;
    float param_9;
    float3 _600 = sky_inscatter(param_7, param_8, param_9, _105);
    float3 up_transmittance = param_8;
    float up_ground = param_9;
    float3 ambient = _600 * 0.5;
    float3 ground = _105.u_sky_ground.xyz * (sun + ambient);
    return (color + (transmittance * ground)) * _105.u_sky_ground.w;
}

fragment fs_out fs(fs_in in [[stage_in]], constant SkyUniforms& _105 [[buffer(4)]])
{
    fs_out out = {};
    float3 param = fast::normalize(in.v_position);
    out.frag_color = float4(fast::min(sky_radiance(param, _105), float3(65504.0)), 1.0);
    return out;
}

