// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CaptureUniforms
{
    float4x4 u_capture_projection;
    float4x4 u_capture_view;
    float4 u_capture_params;
};

struct fs_out
{
    float4 frag_color [[color(0)]];
};

struct fs_in
{
    float3 v_position [[user(locn0)]];
};

static inline __attribute__((always_inline))
float radical_inverse_vdc(thread uint& bits)
{
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 1431655765u) << 1u) | ((bits & 2863311530u) >> 1u);
    bits = ((bits & 858993459u) << 2u) | ((bits & 3435973836u) >> 2u);
    bits = ((bits & 252645135u) << 4u) | ((bits & 4042322160u) >> 4u);
    bits = ((bits & 16711935u) << 8u) | ((bits & 4278255360u) >> 8u);
    return float(bits) * 2.3283064365386962890625e-10;
}

static inline __attribute__((always_inline))
float2 hammersley(thread const uint& i, thread const uint& N)
{
    uint param = i;
    float _78 = radical_inverse_vdc(param);
    return float2(float(i) / float(N), _78);
}

fragment fs_out fs(fs_in in [[stage_in]], constant CaptureUniforms& _109 [[buffer(2)]], texturecube<float> u_env_cubemap [[texture(0)]], sampler u_env_cubemapSmplr [[sampler(0)]])
{
    fs_out out = {};
    float3 N = fast::normalize(in.v_position);
    float3 irradiance = float3(0.0);
    float3 up = float3(0.0, 1.0, 0.0);
    float3 right = fast::normalize(cross(up, N));
    up = fast::normalize(cross(N, right));
    uint sample_count = uint(fast::max(_109.u_capture_params.z, 64.0));
    for (uint i = 0u; i < sample_count; i++)
    {
        uint param = i;
        uint param_1 = sample_count;
        float2 Xi = hammersley(param, param_1);
        float phi = 6.283185482025146484375 * Xi.x;
        float cos_theta = sqrt(1.0 - Xi.y);
        float sin_theta = sqrt(Xi.y);
        float3 tangent = float3(sin_theta * cos(phi), sin_theta * sin(phi), cos_theta);
        float3 dir = ((right * tangent.x) + (up * tangent.y)) + (N * tangent.z);
        irradiance += fast::min(u_env_cubemap.sample(u_env_cubemapSmplr, dir, level(0.0)).xyz, float3(8.0));
    }
    irradiance = (irradiance * 3.1415927410125732421875) / float3(float(sample_count));
    out.frag_color = float4(irradiance, 1.0);
    return out;
}

