// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float3 v_position [[user(locn0)]];
    float4 v_color [[user(locn1)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 a_position [[attribute(0)]];
    float4 a_color [[attribute(1)]];
};

vertex vs_out vs(vs_in in [[stage_in]], constant CameraUniforms& _30 [[buffer(3)]])
{
    vs_out out = {};
    out.v_position = in.a_position;
    out.v_color = in.a_color;
    out.gl_Position = _30.u_projection_view * float4(in.a_position, 1.0);
    return out;
}

