// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct DeferredViewData
{
    float4 u_params;
};

struct fs_out
{
    float4 FragColor [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
};

fragment fs_out fs(fs_in in [[stage_in]], constant DeferredViewData& _12 [[buffer(2)]], texture2d<float> gbuffer_position [[texture(0)]], texture2d<float> gbuffer_normal [[texture(1)]], texture2d<float> gbuffer_albedo [[texture(2)]], texture2d<float> gbuffer_material [[texture(3)]], texture2d<float> gbuffer_emissive [[texture(4)]], texture2d<float> gbuffer_ao [[texture(5)]], sampler gbuffer_positionSmplr [[sampler(0)]], sampler gbuffer_normalSmplr [[sampler(1)]], sampler gbuffer_albedoSmplr [[sampler(2)]], sampler gbuffer_materialSmplr [[sampler(3)]], sampler gbuffer_emissiveSmplr [[sampler(4)]], sampler gbuffer_aoSmplr [[sampler(5)]])
{
    fs_out out = {};
    float mode = _12.u_params.x;
    float4 s = gbuffer_albedo.sample(gbuffer_albedoSmplr, in.v_uv);
    float3 rgb = s.xyz;
    if ((mode > 0.5) && (mode < 1.5))
    {
        s = gbuffer_normal.sample(gbuffer_normalSmplr, in.v_uv);
        rgb = (s.xyz * 0.5) + float3(0.5);
    }
    else
    {
        if ((mode > 1.5) && (mode < 2.5))
        {
            s = gbuffer_material.sample(gbuffer_materialSmplr, in.v_uv);
            float ch = _12.u_params.y;
            float g = s.x;
            if ((ch > 0.5) && (ch < 1.5))
            {
                g = s.y;
            }
            else
            {
                if (ch > 1.5)
                {
                    g = s.z;
                }
            }
            rgb = float3(g);
        }
        else
        {
            if ((mode > 2.5) && (mode < 3.5))
            {
                s = gbuffer_position.sample(gbuffer_positionSmplr, in.v_uv);
                rgb = fract(abs(s.xyz));
            }
            else
            {
                if ((mode > 3.5) && (mode < 4.5))
                {
                    s = gbuffer_emissive.sample(gbuffer_emissiveSmplr, in.v_uv);
                    rgb = s.xyz;
                }
                else
                {
                    if (mode > 4.5)
                    {
                        float g_1 = gbuffer_ao.sample(gbuffer_aoSmplr, in.v_uv).x;
                        rgb = float3(g_1);
                    }
                }
            }
        }
    }
    out.FragColor = float4(fast::clamp(rgb, float3(0.0), float3(1.0)), 1.0);
    return out;
}

