// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SkyScatter
{
    float3 sun_r;
    float3 sun_m;
    float3 moon_r;
    float3 moon_m;
    float3 transmittance;
    float3 depth;
    float t_ground;
};

struct SkyUniforms
{
    float4 u_sky_sun;
    float4 u_sky_origin;
    float4 u_sky_rayleigh;
    float4 u_sky_mie;
    float4 u_sky_ground;
    float4 u_sky_params;
    float4 u_sky_moon;
    float4 u_sky_moon_params;
    float4 u_sky_moon_color;
    float4 u_sky_ozone;
};

struct fs_out
{
    float4 fog_sky [[color(0)]];
};

static inline __attribute__((always_inline))
float3 fog_sky_dir(thread const float2& uv)
{
    float elevation = ((uv.y * uv.y) * 0.5) * 3.1415927410125732421875;
    float azimuth = ((uv.x - 0.5) * 2.0) * 3.1415927410125732421875;
    float c = cos(elevation);
    return float3(c * cos(azimuth), sin(elevation), c * sin(azimuth));
}

static inline __attribute__((always_inline))
float3 sky_observer(constant SkyUniforms& _123)
{
    return float3(0.0, _123.u_sky_params.z + fast::max(_123.u_sky_origin.y, 1.0), 0.0);
}

static inline __attribute__((always_inline))
float2 sky_ray_sphere(thread const float3& o, thread const float3& d, thread const float& r)
{
    float b = dot(o, d);
    float c = dot(o, o) - (r * r);
    float disc = (b * b) - c;
    if (disc < 0.0)
    {
        return float2(-1.0);
    }
    float s = sqrt(disc);
    return float2((-b) - s, (-b) + s);
}

static inline __attribute__((always_inline))
float3 sky_density(thread const float& h, constant SkyUniforms& _123)
{
    float2 scale = float2(_123.u_sky_rayleigh.w, _123.u_sky_mie.w);
    float2 rm = exp(float2(-h) / scale);
    float ozone = fast::max(1.0 - (abs(h - 25000.0) / 15000.0), 0.0);
    return float3(rm, ozone);
}

static inline __attribute__((always_inline))
float3 sky_optical_depth(thread const float3& p, thread const float3& d, thread const float& len, thread const int& samples, constant SkyUniforms& _123)
{
    float step_len = len / float(samples);
    float3 depth = float3(0.0);
    for (int i = 0; i < samples; i++)
    {
        float3 s = p + (d * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(s) - _123.u_sky_params.z, 0.0);
        float param = h;
        depth += (sky_density(param, _123) * step_len);
    }
    return depth;
}

static inline __attribute__((always_inline))
float3 sky_extinction(thread const float3& depth, constant SkyUniforms& _123)
{
    return exp(-(((_123.u_sky_rayleigh.xyz * depth.x) + (float3(_123.u_sky_mie.y) * depth.y)) + (_123.u_sky_ozone.xyz * depth.z)));
}

static inline __attribute__((always_inline))
SkyScatter sky_scatter_to(thread const float3& dir, thread const float& limit, thread const int& view_samples, thread const int& light_samples, constant SkyUniforms& _123)
{
    float3 o = sky_observer(_123);
    float rg = _123.u_sky_params.z;
    float rt = _123.u_sky_params.w;
    float3 param = o;
    float3 param_1 = dir;
    float param_2 = rt;
    float2 atmo = sky_ray_sphere(param, param_1, param_2);
    float t_max = fast::max(atmo.y, 0.0);
    float3 param_3 = o;
    float3 param_4 = dir;
    float param_5 = rg;
    float2 ground = sky_ray_sphere(param_3, param_4, param_5);
    SkyScatter s;
    s.t_ground = -1.0;
    if (ground.x > 0.0)
    {
        s.t_ground = ground.x;
        t_max = ground.x;
    }
    t_max = fast::min(t_max, limit);
    bool midpoint = _123.u_sky_ozone.w > 0.5;
    float n = float(view_samples);
    float step_len = t_max / n;
    float3 to_sun = _123.u_sky_sun.xyz;
    float3 sum_r = float3(0.0);
    float3 sum_m = float3(0.0);
    float3 depth_view = float3(0.0);
    bool moon_on = _123.u_sky_moon.w > 0.0;
    float3 to_moon = _123.u_sky_moon.xyz;
    float3 moon_r = float3(0.0);
    float3 moon_m = float3(0.0);
    for (int i = 0; i < view_samples; i++)
    {
        float t = (float(i) + 0.5) * step_len;
        float dt = step_len;
        if (midpoint)
        {
            float a = float(i) / n;
            float b = float(i + 1) / n;
            t = (t_max * 0.5) * ((a * a) + (b * b));
            dt = t_max * ((b * b) - (a * a));
        }
        float3 p = o + (dir * t);
        float h = fast::max(length(p) - rg, 0.0);
        float param_6 = h;
        float3 dens = sky_density(param_6, _123) * dt;
        float3 depth_here = depth_view + dens;
        if (midpoint)
        {
            depth_here = depth_view + (dens * 0.5);
        }
        depth_view += dens;
        bool _414;
        if (moon_on)
        {
            float3 param_7 = p;
            float3 param_8 = to_moon;
            float param_9 = rg;
            _414 = sky_ray_sphere(param_7, param_8, param_9).x <= 0.0;
        }
        else
        {
            _414 = moon_on;
        }
        if (_414)
        {
            float3 param_10 = p;
            float3 param_11 = to_moon;
            float param_12 = rt;
            float2 moon_atmo = sky_ray_sphere(param_10, param_11, param_12);
            float3 param_13 = p;
            float3 param_14 = to_moon;
            float param_15 = fast::max(moon_atmo.y, 0.0);
            int param_16 = light_samples;
            float3 moon_depth = sky_optical_depth(param_13, param_14, param_15, param_16, _123);
            float3 param_17 = depth_here + moon_depth;
            float3 tm = sky_extinction(param_17, _123);
            moon_r += (tm * dens.x);
            moon_m += (tm * dens.y);
        }
        float3 param_18 = p;
        float3 param_19 = to_sun;
        float param_20 = rg;
        float2 sun_ground = sky_ray_sphere(param_18, param_19, param_20);
        if (sun_ground.x > 0.0)
        {
            continue;
        }
        float3 param_21 = p;
        float3 param_22 = to_sun;
        float param_23 = rt;
        float2 sun_atmo = sky_ray_sphere(param_21, param_22, param_23);
        float3 param_24 = p;
        float3 param_25 = to_sun;
        float param_26 = fast::max(sun_atmo.y, 0.0);
        int param_27 = light_samples;
        float3 depth_light = sky_optical_depth(param_24, param_25, param_26, param_27, _123);
        float3 param_28 = depth_here + depth_light;
        float3 t_light = sky_extinction(param_28, _123);
        sum_r += (t_light * dens.x);
        sum_m += (t_light * dens.y);
    }
    float3 param_29 = depth_view;
    s.transmittance = sky_extinction(param_29, _123);
    s.depth = depth_view;
    s.sun_r = sum_r * _123.u_sky_rayleigh.xyz;
    s.sun_m = sum_m * float3(_123.u_sky_mie.x);
    s.moon_r = moon_r * _123.u_sky_rayleigh.xyz;
    s.moon_m = moon_m * float3(_123.u_sky_mie.x);
    return s;
}

static inline __attribute__((always_inline))
SkyScatter sky_scatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, constant SkyUniforms& _123)
{
    float3 param = dir;
    float param_1 = 1000000015047466219876688855040.0;
    int param_2 = view_samples;
    int param_3 = light_samples;
    return sky_scatter_to(param, param_1, param_2, param_3, _123);
}

static inline __attribute__((always_inline))
float sky_phase_rayleigh(thread const float& mu)
{
    return 0.0596831031143665313720703125 * (1.0 + (mu * mu));
}

static inline __attribute__((always_inline))
float sky_phase_mie(thread const float& mu, constant SkyUniforms& _123)
{
    float g = _123.u_sky_mie.z;
    float gg = g * g;
    return (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / ((2.0 + gg) * pow((1.0 + gg) - ((2.0 * g) * mu), 1.5));
}

static inline __attribute__((always_inline))
float3 sky_scatter_color(thread const float3& dir, thread const float3& sun_r, thread const float3& sun_m, thread const float3& moon_r, thread const float3& moon_m, constant SkyUniforms& _123)
{
    float mu = dot(dir, _123.u_sky_sun.xyz);
    float param = mu;
    float param_1 = mu;
    float3 color = ((sun_r * sky_phase_rayleigh(param)) + (sun_m * sky_phase_mie(param_1, _123))) * (_123.u_sky_sun.w * 4.0);
    if (_123.u_sky_moon.w > 0.0)
    {
        float mu_m = dot(dir, _123.u_sky_moon.xyz);
        float param_2 = mu_m;
        float param_3 = mu_m;
        color += ((_123.u_sky_moon_color.xyz * (_123.u_sky_moon.w * 4.0)) * ((moon_r * sky_phase_rayleigh(param_2)) + (moon_m * sky_phase_mie(param_3, _123))));
    }
    return color;
}

static inline __attribute__((always_inline))
float3 sky_inscatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _123)
{
    float3 param = dir;
    int param_1 = view_samples;
    int param_2 = light_samples;
    SkyScatter s = sky_scatter_n(param, param_1, param_2, _123);
    transmittance = s.transmittance;
    t_ground = s.t_ground;
    float3 param_3 = dir;
    float3 param_4 = s.sun_r;
    float3 param_5 = s.sun_m;
    float3 param_6 = s.moon_r;
    float3 param_7 = s.moon_m;
    return sky_scatter_color(param_3, param_4, param_5, param_6, param_7, _123);
}

fragment fs_out fs(constant SkyUniforms& _123 [[buffer(4)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float2 uv = gl_FragCoord.xy / float2(64.0, 32.0);
    float2 param = uv;
    float3 dir = fog_sky_dir(param);
    float3 param_1 = dir;
    int param_2 = int(_123.u_sky_params.x);
    int param_3 = int(_123.u_sky_params.y);
    float3 param_4;
    float param_5;
    float3 _741 = sky_inscatter_n(param_1, param_2, param_3, param_4, param_5, _123);
    float3 transmittance = param_4;
    float t_ground = param_5;
    float3 radiance = _741;
    out.fog_sky = float4(fast::min(radiance * _123.u_sky_ground.w, float3(65504.0)), 1.0);
    return out;
}

