// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

// Implementation of the GLSL findLSB() function
template<typename T>
inline T spvFindLSB(T x)
{
    return select(ctz(x), T(-1), x == T(0));
}

struct GBuffer
{
    float3 P;
    float3 relative;
    float3 N;
    float3 albedo;
    float metallic;
    float roughness;
    float ao;
    float3 emissive;
    uint id;
    float coverage;
};

struct PBRSurface
{
    float3 P;
    float3 N;
    float3 V;
    float3 albedo;
    float metallic;
    float roughness;
    float ao;
    float3 emissive;
    float3 F0;
};

struct LightGpu
{
    float4 position_radius;
    float4 color_intensity;
    float4 source;
    float4 flicker;
    float4 spot;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct FogUniforms
{
    float4 u_fog_density;
    float4 u_fog_color;
    float4 u_fog_params;
    float4 u_fog_sun;
    float4 u_fog_floor;
    float4 u_fog_moon;
    float4 u_fog_shafts;
    float4 u_fog_shaft_light;
    float4 u_fog_shaft_phase;
    float4 u_fog_model;
    float4 u_fog_to_moon;
    float4 u_fog_sun_light;
    float4 u_fog_moon_light;
    float4 u_fog_ambient;
    float4 u_fog_albedo;
    float4 u_fog_aerial;
    float4 u_fog_aerial_extinction;
};

struct LightZBins
{
    uint2 u_light_zbins[1];
};

struct LightTiles
{
    uint u_light_tiles[1];
};

struct LightKeys
{
    uint u_light_keys[1];
};

struct VsmGenerations
{
    uint u_vsm_gens[1];
};

struct VsmPageTable
{
    uint u_vsm_table[1];
};

struct VsmAtlas
{
    float u_vsm_atlas[1];
};

struct LightUniforms
{
    float4 u_sun_direction;
    float4 u_sun_color;
    float4 u_ibl;
    float4x4 u_light_space[5];
    float4 u_splits;
    float4 u_shadow;
    float4 u_moon_direction;
    float4 u_moon_color;
    float4 u_night_ambient;
    float4 u_cluster_head;
    float4 u_cluster_z;
    float4 u_vsm;
};

struct LightGpu_1
{
    float4 position_radius;
    float4 color_intensity;
    float4 source;
    float4 flicker;
    float4 spot;
};

struct LightTableBuffer
{
    LightGpu_1 u_lights[1];
};

constant spvUnsafeArray<float, 5> _1222 = spvUnsafeArray<float, 5>({ 0.00120000005699694156646728515625, 0.001700000022538006305694580078125, 0.00179999996908009052276611328125, 0.0005000000237487256526947021484375, 0.00120000005699694156646728515625 });

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
};

static inline __attribute__((always_inline))
float4 gbuffer_position_at(thread const float2& uv, texture2d<float> gbuffer_position, sampler gbuffer_positionSmplr)
{
    return gbuffer_position.sample(gbuffer_positionSmplr, uv);
}

static inline __attribute__((always_inline))
uint gbuffer_id_decode(thread const float& t)
{
    return uint((t * 255.0) + 0.5);
}

static inline __attribute__((always_inline))
GBuffer gbuffer_make(thread const float2& uv, thread const float4& position, texture2d<float> gbuffer_normal, sampler gbuffer_normalSmplr, texture2d<float> gbuffer_albedo, sampler gbuffer_albedoSmplr, texture2d<float> gbuffer_material, sampler gbuffer_materialSmplr, constant CameraUniforms& _661, texture2d<float> gbuffer_ao, sampler gbuffer_aoSmplr, texture2d<float> gbuffer_emissive, sampler gbuffer_emissiveSmplr, texture2d<float> gbuffer_id, sampler gbuffer_idSmplr)
{
    float4 normal = gbuffer_normal.sample(gbuffer_normalSmplr, uv);
    float4 albedo = gbuffer_albedo.sample(gbuffer_albedoSmplr, uv);
    float4 material = gbuffer_material.sample(gbuffer_materialSmplr, uv);
    GBuffer gbuffer;
    gbuffer.relative = position.xyz;
    gbuffer.P = position.xyz + _661.u_camera_position.xyz;
    gbuffer.N = normal.xyz;
    gbuffer.albedo = albedo.xyz;
    gbuffer.roughness = material.x;
    gbuffer.metallic = material.y;
    gbuffer.ao = material.z * gbuffer_ao.sample(gbuffer_aoSmplr, uv).x;
    gbuffer.emissive = gbuffer_emissive.sample(gbuffer_emissiveSmplr, uv).xyz;
    float param = gbuffer_id.sample(gbuffer_idSmplr, uv).x;
    gbuffer.id = gbuffer_id_decode(param);
    gbuffer.coverage = position.w;
    return gbuffer;
}

static inline __attribute__((always_inline))
PBRSurface pbr_surface_make(thread const GBuffer& gbuffer, thread const float3& camera_position)
{
    PBRSurface s;
    s.P = gbuffer.P;
    s.N = fast::normalize(gbuffer.N);
    s.V = fast::normalize(camera_position - s.P);
    s.albedo = fast::max(gbuffer.albedo, float3(0.0));
    s.metallic = fast::clamp(gbuffer.metallic, 0.0, 1.0);
    s.roughness = fast::clamp(gbuffer.roughness, 0.039999999105930328369140625, 1.0);
    s.ao = fast::clamp(gbuffer.ao, 0.0, 1.0);
    s.emissive = gbuffer.emissive;
    s.F0 = mix(float3(0.039999999105930328369140625), s.albedo, float3(s.metallic));
    return s;
}

static inline __attribute__((always_inline))
float fog_integral(thread const float& dy, thread const float& len, constant FogUniforms& _1420)
{
    float k = _1420.u_fog_density.y;
    float d0 = _1420.u_fog_density.x;
    float x = fast::max((k * dy) * len, -60.0);
    if (abs(x) < 9.9999997473787516355514526367188e-05)
    {
        return (d0 * len) * (1.0 - (0.5 * x));
    }
    return (d0 * (1.0 - exp(-x))) / (k * dy);
}

static inline __attribute__((always_inline))
float3 fog_sky_horizon(thread const float3& dir, thread const float3& fallback)
{
    float2 xz = dir.xz;
    float horiz = length(xz);
    if (horiz < 9.9999997473787516355514526367188e-05)
    {
        xz = fallback.xz;
        horiz = length(xz);
        if (horiz < 9.9999997473787516355514526367188e-05)
        {
            xz = float2(1.0, 0.0);
            horiz = 1.0;
        }
    }
    xz /= float2(horiz);
    return fast::normalize(float3(xz.x, fast::max(dir.y, 0.0199999995529651641845703125), xz.y));
}

static inline __attribute__((always_inline))
float2 fog_sky_uv(thread const float3& dir)
{
    float elevation = asin(fast::clamp(dir.y, 0.0, 1.0));
    float v = sqrt(elevation / 1.57079637050628662109375);
    float half_texel = 0.015625;
    float u = (precise::atan2(dir.z, dir.x) / 6.283185482025146484375) + 0.5;
    return float2(u, fast::clamp(v, half_texel, 1.0 - half_texel));
}

static inline __attribute__((always_inline))
float3 fog_color(thread const float3& dir, constant FogUniforms& _1420, texture2d<float> u_fog_sky, sampler u_fog_skySmplr)
{
    float3 tint = _1420.u_fog_color.xyz;
    if (_1420.u_fog_color.w < 0.5)
    {
        return tint;
    }
    float3 param = dir;
    float3 param_1 = _1420.u_fog_model.xyz;
    float3 param_2 = fog_sky_horizon(param, param_1);
    float2 uv = fog_sky_uv(param_2);
    return tint * (u_fog_sky.sample(u_fog_skySmplr, uv, level(0.0)).xyz + _1420.u_fog_floor.xyz);
}

static inline __attribute__((always_inline))
float3 fog_apply_legacy(thread const float3& color, thread const float3& relative, constant FogUniforms& _1420, texture2d<float> u_fog_sky, sampler u_fog_skySmplr)
{
    if (_1420.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _1420.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _1420.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _1420);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _1420))), 1.0 - _1420.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _1420.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _1420)));
    float sun = pow(fast::max(dot(dir, _1420.u_fog_model.xyz), 0.0), _1420.u_fog_sun.w);
    float moon = pow(fast::max(dot(dir, _1420.u_fog_to_moon.xyz), 0.0), fast::max(_1420.u_fog_moon.w, 1.0));
    float3 glow = (_1420.u_fog_sun.xyz * sun) + (_1420.u_fog_moon.xyz * moon);
    float3 param_6 = dir;
    float3 fog = (fog_color(param_6, _1420, u_fog_sky, u_fog_skySmplr) * (1.0 - t)) + (glow * (1.0 - td));
    return (color * t) + fog;
}

static inline __attribute__((always_inline))
float phase_hg(thread const float& g, thread const float& mu)
{
    float gg = g * g;
    float base = fast::max((1.0 + gg) - ((2.0 * g) * mu), 9.9999997473787516355514526367188e-05);
    return (1.0 - gg) / ((12.56637096405029296875 * base) * sqrt(base));
}

static inline __attribute__((always_inline))
float fog_phase(thread const float& mu, constant FogUniforms& _1420)
{
    float param = _1420.u_fog_sun_light.w;
    float param_1 = mu;
    float forward = phase_hg(param, param_1);
    return mix(0.079577468335628509521484375, forward, _1420.u_fog_to_moon.w);
}

static inline __attribute__((always_inline))
float3 fog_medium(thread const float3& dir, thread const float& lit_sun, thread const float& lit_moon, constant FogUniforms& _1420)
{
    float param = dot(dir, _1420.u_fog_model.xyz);
    float3 light = _1420.u_fog_ambient.xyz + (_1420.u_fog_sun_light.xyz * (fog_phase(param, _1420) * lit_sun));
    if (_1420.u_fog_moon_light.w > 0.5)
    {
        float param_1 = dot(dir, _1420.u_fog_to_moon.xyz);
        light += (_1420.u_fog_moon_light.xyz * (fog_phase(param_1, _1420) * lit_moon));
    }
    return _1420.u_fog_albedo.xyz * (light * _1420.u_fog_albedo.w);
}

static inline __attribute__((always_inline))
float3 fog_height(thread const float3& color, thread const float3& dir, thread const float& len, thread const float& lit_sun, thread const float& lit_moon, thread const float3& rays, constant FogUniforms& _1420)
{
    if (_1420.u_fog_density.w < 0.5)
    {
        return color;
    }
    float cutoff = _1420.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float dy = dir.y;
    float start = _1420.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _1420);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _1420))), 1.0 - _1420.u_fog_density.z);
    float3 param_4 = dir;
    float param_5 = lit_sun;
    float param_6 = lit_moon;
    return ((color * t) + (fog_medium(param_4, param_5, param_6, _1420) * (1.0 - t))) + rays;
}

static inline __attribute__((always_inline))
float aerial_slice(thread const float& d)
{
    return (sqrt(fast::max(d, 0.0) / 64000.0) * 32.0) - 1.0;
}

static inline __attribute__((always_inline))
float2 aerial_uv(thread const float3& dir)
{
    float y = fast::clamp(dir.y, -1.0, 1.0);
    float v = 0.5 + ((0.5 * sign(y)) * sqrt(abs(y)));
    float half_texel = 0.015625;
    float u = ((precise::atan2(dir.z, dir.x) / 6.283185482025146484375) + 0.5) * 64.0;
    return float2(u, fast::clamp(v, half_texel, 1.0 - half_texel));
}

static inline __attribute__((always_inline))
float phase_mie(thread const float& g, thread const float& mu)
{
    float gg = g * g;
    float base = (1.0 + gg) - ((2.0 * g) * mu);
    return (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / (((2.0 + gg) * base) * sqrt(base));
}

static inline __attribute__((always_inline))
float2 aerial_atlas(thread const float2& uv, thread const float& k)
{
    return float2((((k * 66.0) + 1.0) + uv.x) / 2112.0, uv.y);
}

static inline __attribute__((always_inline))
float3 aerial_fetch(thread const float2& uv, thread const float& k, thread const float& mie_sun, thread float2& depth, texture2d_array<float> u_aerial, sampler u_aerialSmplr)
{
    float2 param = uv;
    float param_1 = k;
    float2 at = aerial_atlas(param, param_1);
    float3 _1769 = float3(at, 0.0);
    float4 light = u_aerial.sample(u_aerialSmplr, _1769.xy, uint(rint(_1769.z)), level(0.0));
    float3 _1776 = float3(at, 1.0);
    float4 sun_m = u_aerial.sample(u_aerialSmplr, _1776.xy, uint(rint(_1776.z)), level(0.0));
    depth = float2(light.w, sun_m.w);
    return light.xyz + (sun_m.xyz * mie_sun);
}

static inline __attribute__((always_inline))
float3 aerial_apply(thread const float3& color, thread const float3& dir, thread const float& len, constant FogUniforms& _1420, texture2d_array<float> u_aerial, sampler u_aerialSmplr)
{
    if (_1420.u_fog_aerial.w <= 0.0)
    {
        return color;
    }
    float param = len * _1420.u_fog_aerial.w;
    float s = fast::min(aerial_slice(param), 31.0);
    float k = floor(s);
    float f = s - k;
    float3 param_1 = dir;
    float2 uv = aerial_uv(param_1);
    float param_2 = _1420.u_fog_aerial.z;
    float param_3 = dot(dir, _1420.u_fog_model.xyz);
    float mie_sun = phase_mie(param_2, param_3);
    float2 param_4 = uv;
    float param_5 = fast::min(k + 1.0, 31.0);
    float param_6 = mie_sun;
    float2 param_7;
    float3 _1842 = aerial_fetch(param_4, param_5, param_6, param_7, u_aerial, u_aerialSmplr);
    float2 d_far = param_7;
    float3 far = _1842;
    float2 d_near = float2(0.0);
    float3 near = float3(0.0);
    if (k >= 0.0)
    {
        float2 param_8 = uv;
        float param_9 = k;
        float param_10 = mie_sun;
        float2 param_11;
        float3 _1858 = aerial_fetch(param_8, param_9, param_10, param_11, u_aerial, u_aerialSmplr);
        d_near = param_11;
        near = _1858;
    }
    float2 depth = mix(d_near, d_far, float2(f));
    float3 transmittance = exp(-((_1420.u_fog_aerial_extinction.xyz * depth.x) + (float3(_1420.u_fog_aerial_extinction.w) * depth.y)));
    return (color * transmittance) + mix(near, far, float3(f));
}

static inline __attribute__((always_inline))
float3 fog_surface(thread float3& color, thread const float3& relative, thread const float& lit_sun, thread const float& lit_moon, thread const float3& rays, constant FogUniforms& _1420, texture2d_array<float> u_aerial, sampler u_aerialSmplr)
{
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float3 param = color;
    float3 param_1 = dir;
    float param_2 = len;
    float param_3 = lit_sun;
    float param_4 = lit_moon;
    float3 param_5 = rays;
    color = fog_height(param, param_1, param_2, param_3, param_4, param_5, _1420);
    float3 param_6 = color;
    float3 param_7 = dir;
    float param_8 = len;
    return aerial_apply(param_6, param_7, param_8, _1420, u_aerial, u_aerialSmplr);
}

static inline __attribute__((always_inline))
float3 fog_apply(thread const float3& color, thread const float3& relative, constant FogUniforms& _1420, texture2d<float> u_fog_sky, sampler u_fog_skySmplr, texture2d_array<float> u_aerial, sampler u_aerialSmplr)
{
    if (_1420.u_fog_model.w < 0.5)
    {
        float3 param = color;
        float3 param_1 = relative;
        return fog_apply_legacy(param, param_1, _1420, u_fog_sky, u_fog_skySmplr);
    }
    float3 param_2 = color;
    float3 param_3 = relative;
    float param_4 = 1.0;
    float param_5 = 1.0;
    float3 param_6 = float3(0.0);
    float3 _1948 = fog_surface(param_2, param_3, param_4, param_5, param_6, _1420, u_aerial, u_aerialSmplr);
    return _1948;
}

static inline __attribute__((always_inline))
float2 godrays_fetch(thread const float2& uv, thread const float& dist, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    float2 size = float2(int2(godrays_resolved.get_width(), godrays_resolved.get_height()));
    float2 st = (uv * size) - float2(0.5);
    float2 cell = floor(st);
    float2 f = st - cell;
    int2 base = int2(cell);
    int2 top = int2(size) - int2(1);
    float d = fast::min(dist, 60000.0);
    float2 sum = float2(0.0);
    float weight = 0.0;
    float _2017;
    float _2030;
    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 2; i++)
        {
            float4 s = godrays_resolved.read(uint2(clamp(base + int2(i, j), int2(0), top)), 0);
            if (i == 0)
            {
                _2017 = 1.0 - f.x;
            }
            else
            {
                _2017 = f.x;
            }
            float bx = _2017;
            if (j == 0)
            {
                _2030 = 1.0 - f.y;
            }
            else
            {
                _2030 = f.y;
            }
            float by = _2030;
            float rel = abs(s.z - d) / fast::max(d, 1.0);
            float w = ((bx * by) / (0.001000000047497451305389404296875 + rel)) + 9.9999999747524270787835121154785e-07;
            sum += (s.xy * w);
            weight += w;
        }
    }
    return sum / float2(weight);
}

static inline __attribute__((always_inline))
float godrays_phase(thread const float& cosTheta, thread const float& g)
{
    float g2 = g * g;
    float denom = fast::max((1.0 + g2) - ((2.0 * g) * cosTheta), 9.9999997473787516355514526367188e-05);
    return (1.0 - g2) / ((12.56637096405029296875 * denom) * sqrt(denom));
}

static inline __attribute__((always_inline))
float godrays_phase2(thread const float& cosTheta, thread const float3& lobes)
{
    float param = cosTheta;
    float param_1 = lobes.x;
    float param_2 = cosTheta;
    float param_3 = lobes.y;
    return godrays_phase(param, param_1) + (godrays_phase(param_2, param_3) * lobes.z);
}

static inline __attribute__((always_inline))
float3 fog_apply_rays_legacy(thread const float3& color, thread const float3& relative, thread const float2& uv, thread const float& fetchDist, constant FogUniforms& _1420, texture2d<float> u_fog_sky, sampler u_fog_skySmplr, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    if (_1420.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _1420.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _1420.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _1420);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _1420))), 1.0 - _1420.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _1420.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _1420)));
    float2 param_6 = uv;
    float param_7 = fetchDist;
    float2 shaft = godrays_fetch(param_6, param_7, godrays_resolved, godrays_resolvedSmplr);
    float occlude = mix(1.0, shaft.y, _1420.u_fog_shafts.y);
    float sun = pow(fast::max(dot(dir, _1420.u_fog_model.xyz), 0.0), _1420.u_fog_sun.w);
    float moon = pow(fast::max(dot(dir, _1420.u_fog_to_moon.xyz), 0.0), fast::max(_1420.u_fog_moon.w, 1.0));
    float3 glow = ((_1420.u_fog_sun.xyz * sun) + (_1420.u_fog_moon.xyz * moon)) * occlude;
    float3 param_8 = dir;
    float3 fog = (fog_color(param_8, _1420, u_fog_sky, u_fog_skySmplr) * (1.0 - t)) + (glow * (1.0 - td));
    float3 _2335;
    if (_1420.u_fog_shaft_light.w > 0.5)
    {
        _2335 = _1420.u_fog_to_moon.xyz;
    }
    else
    {
        _2335 = _1420.u_fog_model.xyz;
    }
    float3 toLight = _2335;
    float param_9 = dot(dir, toLight);
    float3 param_10 = _1420.u_fog_shaft_phase.xyz;
    float phase = godrays_phase2(param_9, param_10);
    float3 rays = _1420.u_fog_shaft_light.xyz * ((phase * shaft.x) * _1420.u_fog_shafts.x);
    return ((color * t) + fog) + rays;
}

static inline __attribute__((always_inline))
float4 fog_shafts(thread const float3& dir, thread const float2& uv, thread const float& fetchDist, constant FogUniforms& _1420, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    float2 param = uv;
    float param_1 = fetchDist;
    float2 shaft = godrays_fetch(param, param_1, godrays_resolved, godrays_resolvedSmplr);
    float lit = mix(1.0, shaft.y, _1420.u_fog_shafts.y);
    float3 _2133;
    if (_1420.u_fog_shaft_light.w > 0.5)
    {
        _2133 = _1420.u_fog_to_moon.xyz;
    }
    else
    {
        _2133 = _1420.u_fog_model.xyz;
    }
    float3 toLight = _2133;
    float param_2 = dot(dir, toLight);
    float3 param_3 = _1420.u_fog_shaft_phase.xyz;
    float phase = godrays_phase2(param_2, param_3);
    return float4(lit, _1420.u_fog_shaft_light.xyz * ((phase * shaft.x) * _1420.u_fog_shafts.x));
}

static inline __attribute__((always_inline))
float3 fog_apply_rays_at(thread const float3& color, thread const float3& relative, thread const float2& uv, thread const float& fetchDist, constant FogUniforms& _1420, texture2d<float> u_fog_sky, sampler u_fog_skySmplr, texture2d_array<float> u_aerial, sampler u_aerialSmplr, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    if (_1420.u_fog_model.w < 0.5)
    {
        float3 param = color;
        float3 param_1 = relative;
        float2 param_2 = uv;
        float param_3 = fetchDist;
        return fog_apply_rays_legacy(param, param_1, param_2, param_3, _1420, u_fog_sky, u_fog_skySmplr, godrays_resolved, godrays_resolvedSmplr);
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float3 param_4 = dir;
    float2 param_5 = uv;
    float param_6 = fetchDist;
    float4 shafts = fog_shafts(param_4, param_5, param_6, _1420, godrays_resolved, godrays_resolvedSmplr);
    bool moonKey = _1420.u_fog_shaft_light.w > 0.5;
    float _2421;
    if (moonKey)
    {
        _2421 = 1.0;
    }
    else
    {
        _2421 = shafts.x;
    }
    float lit_sun = _2421;
    float _2430;
    if (moonKey)
    {
        _2430 = shafts.x;
    }
    else
    {
        _2430 = 1.0;
    }
    float lit_moon = _2430;
    float3 param_7 = color;
    float3 param_8 = relative;
    float param_9 = lit_sun;
    float param_10 = lit_moon;
    float3 param_11 = shafts.yzw;
    float3 _2448 = fog_surface(param_7, param_8, param_9, param_10, param_11, _1420, u_aerial, u_aerialSmplr);
    return _2448;
}

static inline __attribute__((always_inline))
float3 fog_apply_rays(thread const float3& color, thread const float3& relative, thread const float2& uv, constant FogUniforms& _1420, texture2d<float> u_fog_sky, sampler u_fog_skySmplr, texture2d_array<float> u_aerial, sampler u_aerialSmplr, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    if (_1420.u_fog_shafts.w < 0.5)
    {
        float3 param = color;
        float3 param_1 = relative;
        return fog_apply(param, param_1, _1420, u_fog_sky, u_fog_skySmplr, u_aerial, u_aerialSmplr);
    }
    float3 param_2 = color;
    float3 param_3 = relative;
    float2 param_4 = uv;
    float param_5 = length(relative);
    return fog_apply_rays_at(param_2, param_3, param_4, param_5, _1420, u_fog_sky, u_fog_skySmplr, u_aerial, u_aerialSmplr, godrays_resolved, godrays_resolvedSmplr);
}

static inline __attribute__((always_inline))
float2 uv_from_ndc(thread const float2& ndc)
{
    return float2((ndc.x * 0.5) + 0.5, 0.5 - (ndc.y * 0.5));
}

static inline __attribute__((always_inline))
int csm_index_world(thread const float3& world, thread const spvUnsafeArray<float4x4, 5>& light_space)
{
    for (int i = 0; i < 5; i++)
    {
        float4 clip = light_space[i] * float4(world, 1.0);
        if (clip.w <= 0.0)
        {
            continue;
        }
        float3 proj = clip.xyz / float3(clip.w);
        float2 param = proj.xy;
        float2 uv = uv_from_ndc(param);
        bool _999 = proj.z < 0.0;
        bool _1006;
        if (!_999)
        {
            _1006 = proj.z > 1.0;
        }
        else
        {
            _1006 = _999;
        }
        if (_1006)
        {
            continue;
        }
        bool _1012 = uv.x < 0.0;
        bool _1019;
        if (!_1012)
        {
            _1019 = uv.x > 1.0;
        }
        else
        {
            _1019 = _1012;
        }
        bool _1026;
        if (!_1019)
        {
            _1026 = uv.y < 0.0;
        }
        else
        {
            _1026 = _1019;
        }
        bool _1033;
        if (!_1026)
        {
            _1033 = uv.y > 1.0;
        }
        else
        {
            _1033 = _1026;
        }
        if (_1033)
        {
            continue;
        }
        return i;
    }
    return 4;
}

static inline __attribute__((always_inline))
int csm_index(thread const float& depth, thread const float4& splits)
{
    int shadow_index = 0;
    if (depth < splits.x)
    {
        shadow_index = 1;
    }
    if (depth < splits.y)
    {
        shadow_index = 2;
    }
    if (depth < splits.z)
    {
        shadow_index = 3;
    }
    if (depth < splits.w)
    {
        shadow_index = 4;
    }
    return shadow_index;
}

static inline __attribute__((always_inline))
int csm_pick(thread const float3& world, constant CameraUniforms& _661, constant LightUniforms& _3184)
{
    if (_3184.u_shadow.w > 0.5)
    {
        float3 param = world;
        spvUnsafeArray<float4x4, 5> _3196;
        _3196[0] = _3184.u_light_space[0];
        _3196[1] = _3184.u_light_space[1];
        _3196[2] = _3184.u_light_space[2];
        _3196[3] = _3184.u_light_space[3];
        _3196[4] = _3184.u_light_space[4];
        spvUnsafeArray<float4x4, 5> param_1 = _3196;
        return csm_index_world(param, param_1);
    }
    float view_z = (_661.u_view * float4(world, 1.0)).z;
    float param_2 = view_z;
    float4 param_3 = _3184.u_splits;
    return csm_index(param_2, param_3);
}

static inline __attribute__((always_inline))
float shadow_gather(texture2d_array<float> shadowmap, sampler shadowmapSmplr, thread const float3& world_position, thread const float3& normal, thread const float3& light_dir, thread const float4x4& light_space, thread const int& shadow_index, thread const float& min_bias)
{
    float4 clip = light_space * float4(world_position, 1.0);
    if (clip.w <= 0.0)
    {
        return 0.0;
    }
    float3 proj = clip.xyz / float3(clip.w);
    float2 param = proj.xy;
    float2 uv = uv_from_ndc(param);
    float current_depth = proj.z;
    if (current_depth > 1.0)
    {
        return 0.0;
    }
    float bias0 = fast::max(min_bias * (1.0 - dot(normal, light_dir)), min_bias);
    float shadow = 0.0;
    int taps = 0;
    float3 texel = float3(1.0) / float3(int3(shadowmap.get_width(), shadowmap.get_height(), shadowmap.get_array_size()));
    for (int x = -1; x <= 1; x++)
    {
        for (int y = -1; y <= 1; y++)
        {
            float2 sample_uv = uv + (float2(float(x), float(y)) * texel.xy);
            bool _1154 = sample_uv.x < 0.0;
            bool _1161;
            if (!_1154)
            {
                _1161 = sample_uv.x > 1.0;
            }
            else
            {
                _1161 = _1154;
            }
            bool _1168;
            if (!_1161)
            {
                _1168 = sample_uv.y < 0.0;
            }
            else
            {
                _1168 = _1161;
            }
            bool _1175;
            if (!_1168)
            {
                _1175 = sample_uv.y > 1.0;
            }
            else
            {
                _1175 = _1168;
            }
            if (_1175)
            {
                continue;
            }
            float3 _1186 = float3(sample_uv, float(shadow_index));
            float closest = shadowmap.sample(shadowmapSmplr, _1186.xy, uint(rint(_1186.z))).x;
            shadow += float((current_depth - bias0) > closest);
            taps++;
        }
    }
    if (taps == 0)
    {
        return 0.0;
    }
    return fast::clamp(shadow / float(taps), 0.0, 1.0);
}

static inline __attribute__((always_inline))
float shadow_sample(texture2d_array<float> shadowmap, sampler shadowmapSmplr, thread const float3& world_position, thread const float3& normal, thread const float3& light_dir, thread const float4x4& light_space, thread const int& shadow_index)
{
    float3 param = world_position;
    float3 param_1 = normal;
    float3 param_2 = light_dir;
    float4x4 param_3 = light_space;
    int param_4 = shadow_index;
    float param_5 = _1222[shadow_index];
    return shadow_gather(shadowmap, shadowmapSmplr, param, param_1, param_2, param_3, param_4, param_5);
}

static inline __attribute__((always_inline))
float gbuffer_id_wrap(thread const uint& id)
{
    if (id == 3u)
    {
        return 0.550000011920928955078125;
    }
    if (id == 4u)
    {
        return 0.20000000298023223876953125;
    }
    return 0.0;
}

static inline __attribute__((always_inline))
float distribution_GGX(thread const float& NdotH, thread const float& roughness)
{
    float alpha = roughness * roughness;
    float alphaSqr = alpha * alpha;
    float denom = ((NdotH * NdotH) * (alphaSqr - 1.0)) + 1.0;
    float D = alphaSqr / ((3.1415927410125732421875 * denom) * denom);
    return D;
}

static inline __attribute__((always_inline))
float geometry_smith_ggx_correlated(thread const float& NdotL, thread const float& NdotV, thread const float& roughness)
{
    float a = roughness * roughness;
    float a2 = a * a;
    float gv = NdotL * sqrt(a2 + (((1.0 - a2) * NdotV) * NdotV));
    float gl = NdotV * sqrt(a2 + (((1.0 - a2) * NdotL) * NdotL));
    return ((2.0 * NdotL) * NdotV) / fast::max(gv + gl, 9.9999999747524270787835121154785e-07);
}

static inline __attribute__((always_inline))
float3 fresnel_schlick(thread const float3& F0, thread const float& cosTheta)
{
    return F0 + ((float3(1.0) - F0) * pow(1.0 - cosTheta, 5.0));
}

static inline __attribute__((always_inline))
float3 pbr_specular(thread const float3& N, thread const float3& V, thread const float3& H, thread const float3& L, thread const float3& F0, thread const float& roughness, thread float3& fresnel)
{
    float NdotH = fast::max(9.9999997473787516355514526367188e-06, dot(N, H));
    float NdotV = fast::max(dot(N, V), 0.0);
    float NdotL = fast::max(dot(N, L), 0.0);
    float VdotH = fast::max(9.9999997473787516355514526367188e-06, dot(V, H));
    if ((NdotV <= 0.0) || (NdotL <= 0.0))
    {
        fresnel = float3(0.0);
        return float3(0.0);
    }
    float param = NdotH;
    float param_1 = roughness;
    float D = distribution_GGX(param, param_1);
    float param_2 = NdotL;
    float param_3 = NdotV;
    float param_4 = roughness;
    float G = geometry_smith_ggx_correlated(param_2, param_3, param_4);
    float3 param_5 = F0;
    float param_6 = VdotH;
    fresnel = fresnel_schlick(param_5, param_6);
    float denom = fast::max((4.0 * NdotV) * NdotL, 9.9999999747524270787835121154785e-07);
    return ((fresnel * D) * G) / float3(denom);
}

static inline __attribute__((always_inline))
float pbr_peak(thread const float3& c)
{
    return fast::max(c.x, fast::max(c.y, c.z));
}

static inline __attribute__((always_inline))
float3 pbr_dielectric_spec_limit(thread const float3& spec, thread const float3& diffuse, thread const float& metallic, thread const float& roughness)
{
    float3 param = spec;
    float specL = pbr_peak(param);
    float3 param_1 = diffuse;
    float cap = fast::max(pbr_peak(param_1), 0.0199999995529651641845703125);
    float scale = fast::min(1.0, cap / fast::max(specL, 9.9999997473787516355514526367188e-06));
    return spec * mix(1.0, scale, (1.0 - metallic) * roughness);
}

static inline __attribute__((always_inline))
float3 pbr_lit(thread const PBRSurface& s, thread const float3& L, thread const float3& radiance, thread const float& NdotL)
{
    float3 H = fast::normalize(s.V + L);
    float3 param = s.N;
    float3 param_1 = s.V;
    float3 param_2 = H;
    float3 param_3 = L;
    float3 param_4 = s.F0;
    float param_5 = s.roughness;
    float3 param_6;
    float3 _826 = pbr_specular(param, param_1, param_2, param_3, param_4, param_5, param_6);
    float3 F = param_6;
    float3 spec = _826;
    float3 kD = (float3(1.0) - F) * (1.0 - s.metallic);
    float3 diff = (kD * s.albedo) / float3(3.1415927410125732421875);
    float3 param_7 = spec;
    float3 param_8 = diff;
    float param_9 = s.metallic;
    float param_10 = s.roughness;
    spec = pbr_dielectric_spec_limit(param_7, param_8, param_9, param_10);
    return ((diff + spec) * radiance) * NdotL;
}

static inline __attribute__((always_inline))
float3 pbr_shade_wrapped(thread const PBRSurface& s, thread const float3& L, thread const float3& radiance, thread const float& wrap)
{
    float NdotL = fast::max(dot(s.N, L), 0.0) + (wrap * fast::max(dot(-s.N, L), 0.0));
    PBRSurface param = s;
    float3 param_1 = L;
    float3 param_2 = radiance;
    float param_3 = NdotL;
    return pbr_lit(param, param_1, param_2, param_3);
}

static inline __attribute__((always_inline))
float gbuffer_id_thickness(thread const uint& id)
{
    if (id == 3u)
    {
        return 0.550000011920928955078125;
    }
    if (id == 4u)
    {
        return 0.25;
    }
    return 0.0;
}

static inline __attribute__((always_inline))
uint light_zslice(thread const float& viewDepth, thread const float4& clusterZ)
{
    float z = fast::max(viewDepth, clusterZ.x);
    float s = log2(z / clusterZ.x) * clusterZ.y;
    return uint(fast::clamp(s, 0.0, clusterZ.z - 1.0));
}

static inline __attribute__((always_inline))
uint2 light_range(thread const float& viewDepth, thread const float4& clusterHead, thread const float4& clusterZ, const device LightZBins& _2553)
{
    if (clusterHead.x < 0.5)
    {
        return uint2(1u, 0u);
    }
    float param = viewDepth;
    float4 param_1 = clusterZ;
    uint2 bin = _2553.u_light_zbins[light_zslice(param, param_1)];
    return uint2(bin.x, ~bin.y);
}

static inline __attribute__((always_inline))
uint light_tile_base(thread const uint2& pixel, thread const float4& clusterHead)
{
    uint tilePx = uint(clusterHead.y + 0.5);
    uint tilesX = max(uint(clusterHead.z + 0.5), 1u);
    uint2 tile = pixel / uint2(max(tilePx, 1u));
    tile.x = min(tile.x, (tilesX - 1u));
    return ((tile.y * tilesX) + tile.x) * uint(clusterHead.w + 0.5);
}

static inline __attribute__((always_inline))
uint light_tile_base(thread const float2& pixel, thread const float4& clusterHead)
{
    uint2 param = uint2(pixel);
    float4 param_1 = clusterHead;
    return light_tile_base(param, param_1);
}

static inline __attribute__((always_inline))
float vsm_footprint(thread const float& viewDepth, thread const float& projectionY, thread const float& height)
{
    return (2.0 * viewDepth) / (projectionY * height);
}

static inline __attribute__((always_inline))
uint light_word(thread const uint& base, thread const uint& w, thread const uint2& range, const device LightTiles& _2619)
{
    uint m = _2619.u_light_tiles[base + w];
    uint first = w * 32u;
    if (range.x > first)
    {
        m &= (4294967295u << (range.x - first));
    }
    if (range.y < (first + 31u))
    {
        m &= (4294967295u >> (31u - (range.y - first)));
    }
    return m;
}

static inline __attribute__((always_inline))
uint light_slot(thread const uint& index, const device LightKeys& _2666)
{
    return _2666.u_light_keys[index] & 8191u;
}

static inline __attribute__((always_inline))
float light_intensity(thread const LightGpu& l, thread const float& seconds)
{
    if (l.flicker.x <= 0.0)
    {
        return l.color_intensity.w;
    }
    return l.color_intensity.w + (l.flicker.x * sin((l.flicker.y * seconds) + l.flicker.z));
}

static inline __attribute__((always_inline))
float point_atten(thread const float& dist, thread const float& radius)
{
    float d = fast::clamp(dist / fast::max(radius, 9.9999997473787516355514526367188e-05), 0.0, 1.0);
    float window = fast::clamp(1.0 - (((d * d) * d) * d), 0.0, 1.0);
    window *= window;
    return window / ((dist * dist) + 1.0);
}

static inline __attribute__((always_inline))
float3 light_radiance(thread const LightGpu& l, thread const float& dist, thread const float& seconds)
{
    LightGpu param = l;
    float param_1 = seconds;
    float param_2 = dist;
    float param_3 = l.position_radius.w;
    return (l.color_intensity.xyz * light_intensity(param, param_1)) * point_atten(param_2, param_3);
}

static inline __attribute__((always_inline))
float3 pbr_sphere_l(thread const float3& toLight, thread const float3& V, thread const float3& N, thread const float& sourceRadius)
{
    float3 R = reflect(-V, N);
    float3 centerToRay = (R * dot(toLight, R)) - toLight;
    float rayDist = length(centerToRay);
    float3 closest = toLight;
    if (rayDist > 9.9999997473787516355514526367188e-05)
    {
        closest = toLight + (centerToRay * fast::clamp(sourceRadius / rayDist, 0.0, 1.0));
    }
    return fast::normalize(closest);
}

static inline __attribute__((always_inline))
float vsm_fade(thread const float3& L, thread const float3& eye, thread const float& limit)
{
    float d = distance(L, eye);
    return fast::clamp((limit - d) / fast::max(limit * 0.1500000059604644775390625, 1.0), 0.0, 1.0);
}

static inline __attribute__((always_inline))
float vsm_light_fade(thread const LightGpu& l, thread const float3& eye, thread const float4& vsm)
{
    bool _3157 = l.source.y > 0.5;
    bool _3163;
    if (_3157)
    {
        _3163 = vsm.x > 0.5;
    }
    else
    {
        _3163 = _3157;
    }
    float _3164;
    if (_3163)
    {
        float3 param = l.position_radius.xyz;
        float3 param_1 = eye;
        float param_2 = vsm.w;
        _3164 = vsm_fade(param, param_1, param_2);
    }
    else
    {
        _3164 = 0.0;
    }
    return _3164;
}

static inline __attribute__((always_inline))
uint vsm_face(thread const float3& d)
{
    float3 a = abs(d);
    bool _2743 = a.x >= a.y;
    bool _2751;
    if (_2743)
    {
        _2751 = a.x >= a.z;
    }
    else
    {
        _2751 = _2743;
    }
    if (_2751)
    {
        return (d.x >= 0.0) ? 0u : 1u;
    }
    if (a.y >= a.z)
    {
        return (d.y >= 0.0) ? 2u : 3u;
    }
    return (d.z >= 0.0) ? 4u : 5u;
}

static inline __attribute__((always_inline))
void vsm_basis(thread const uint& face, thread float3& n, thread float3& r, thread float3& u)
{
    if (face == 0u)
    {
        n = float3(1.0, 0.0, 0.0);
        r = float3(0.0, 0.0, -1.0);
        u = float3(0.0, 1.0, 0.0);
    }
    else
    {
        if (face == 1u)
        {
            n = float3(-1.0, 0.0, 0.0);
            r = float3(0.0, 0.0, 1.0);
            u = float3(0.0, 1.0, 0.0);
        }
        else
        {
            if (face == 2u)
            {
                n = float3(0.0, 1.0, 0.0);
                r = float3(1.0, 0.0, 0.0);
                u = float3(0.0, 0.0, -1.0);
            }
            else
            {
                if (face == 3u)
                {
                    n = float3(0.0, -1.0, 0.0);
                    r = float3(1.0, 0.0, 0.0);
                    u = float3(0.0, 0.0, 1.0);
                }
                else
                {
                    if (face == 4u)
                    {
                        n = float3(0.0, 0.0, 1.0);
                        r = float3(1.0, 0.0, 0.0);
                        u = float3(0.0, 1.0, 0.0);
                    }
                    else
                    {
                        n = float3(0.0, 0.0, -1.0);
                        r = float3(-1.0, 0.0, 0.0);
                        u = float3(0.0, 1.0, 0.0);
                    }
                }
            }
        }
    }
}

static inline __attribute__((always_inline))
float3 vsm_view(thread const uint& face, thread const float3& d)
{
    uint param = face;
    float3 param_1;
    float3 param_2;
    float3 param_3;
    vsm_basis(param, param_1, param_2, param_3);
    float3 n = param_1;
    float3 r = param_2;
    float3 u = param_3;
    return float3(dot(d, r), dot(d, u), dot(d, n));
}

static inline __attribute__((always_inline))
uint vsm_mip(thread const float& footprint, thread const float& z, thread const float& bias0)
{
    float texel = (2.0 * fast::max(z, 0.0500000007450580596923828125)) / 1024.0;
    float m = floor(log2(fast::max(footprint / texel, 1.0)) + bias0);
    return uint(fast::clamp(m, 0.0, 4.0));
}

static inline __attribute__((always_inline))
uint vsm_mip_side(thread const uint& mip)
{
    return 16u >> mip;
}

static inline __attribute__((always_inline))
uint2 vsm_page_xy(thread const float2& f, thread const uint& mip)
{
    uint param = mip;
    uint side = vsm_mip_side(param);
    float2 uv = fast::clamp((f * 0.5) + float2(0.5), float2(0.0), float2(0.999989986419677734375));
    return min(uint2(uv * float(side)), uint2(side - 1u));
}

static inline __attribute__((always_inline))
uint vsm_mip_offset(thread const uint& mip)
{
    if (mip == 0u)
    {
        return 0u;
    }
    if (mip == 1u)
    {
        return 256u;
    }
    if (mip == 2u)
    {
        return 320u;
    }
    if (mip == 3u)
    {
        return 336u;
    }
    return 340u;
}

static inline __attribute__((always_inline))
uint vsm_page_index(thread const uint& face, thread const uint& mip, thread const uint2& page)
{
    uint param = mip;
    uint param_1 = mip;
    return (((face * 341u) + vsm_mip_offset(param)) + (page.y * vsm_mip_side(param_1))) + page.x;
}

static inline __attribute__((always_inline))
float4 vsm_page_rect(thread const uint& mip, thread const uint2& page)
{
    uint param = mip;
    float side = float(vsm_mip_side(param));
    float w = 2.0 / side;
    float g = (w * 1.0) / 64.0;
    float2 lo = (float2(page) * w) - float2(1.0);
    return float4(lo - float2(g), (lo + float2(w)) + float2(g));
}

static inline __attribute__((always_inline))
float2 vsm_cell_texel(thread const float2& f, thread const float4& rect)
{
    return ((f - rect.xy) / (rect.zw - rect.xy)) * 66.0;
}

static inline __attribute__((always_inline))
float vsm_linear(thread const float& depth, thread const float& radius)
{
    float f = fast::max(radius, 0.100000001490116119384765625);
    float a = f / (f - 0.0500000007450580596923828125);
    return (a * 0.0500000007450580596923828125) / fast::max(a - depth, 9.9999999747524270787835121154785e-07);
}

static inline __attribute__((always_inline))
float vsm_lookup(thread const uint& slot, thread const float3& L, thread const float& radius, thread const float3& P, thread const float& footprint, thread const float& mipBias, const device VsmGenerations& _2972, const device VsmPageTable& _3009, const device VsmAtlas& _3100)
{
    float3 d = P - L;
    float3 param = d;
    uint face = vsm_face(param);
    uint param_1 = face;
    float3 param_2 = d;
    float3 v = vsm_view(param_1, param_2);
    if (v.z <= 0.0500000007450580596923828125)
    {
        return 1.0;
    }
    float2 f = v.xy / float2(v.z);
    uint gen = _2972.u_vsm_gens[slot] & 32767u;
    uint base = slot * 2046u;
    float missing = -1.0;
    float param_3 = footprint;
    float param_4 = v.z;
    float param_5 = mipBias;
    uint _2991 = vsm_mip(param_3, param_4, param_5);
    for (uint m = _2991; m < 5u; m++)
    {
        float2 param_6 = f;
        uint param_7 = m;
        uint2 xy = vsm_page_xy(param_6, param_7);
        uint param_8 = face;
        uint param_9 = m;
        uint2 param_10 = xy;
        uint entry = _3009.u_vsm_table[base + vsm_page_index(param_8, param_9, param_10)];
        if (entry == 4294967295u)
        {
            continue;
        }
        if ((entry >> 16u) != gen)
        {
            missing = -2.0;
            continue;
        }
        uint param_11 = m;
        uint2 param_12 = xy;
        float4 rect = vsm_page_rect(param_11, param_12);
        float2 param_13 = f;
        float4 param_14 = rect;
        int2 t = int2(floor(vsm_cell_texel(param_13, param_14)));
        uint cell = (entry & 65535u) * 4356u;
        float texel = (2.0 * v.z) / (1024.0 / float(1u << m));
        float receiver = v.z - (texel * 1.5);
        float shadow = 0.0;
        for (int x = -1; x <= 1; x++)
        {
            for (int y = -1; y <= 1; y++)
            {
                int2 at = clamp(t + int2(x, y), int2(0), int2(65));
                float stored = _3100.u_vsm_atlas[(cell + (uint(at.y) * 66u)) + uint(at.x)];
                float param_15 = stored;
                float param_16 = radius;
                shadow += float(receiver > vsm_linear(param_15, param_16));
            }
        }
        return fast::clamp(1.0 - (shadow / 9.0), 0.0, 1.0);
    }
    return missing;
}

static inline __attribute__((always_inline))
float3 pbr_shade_sphere(thread const PBRSurface& s, thread const float3& centerDir, thread const float3& specDir, thread const float3& radiance, thread const float& wrap)
{
    float NdotL = fast::max(dot(s.N, centerDir), 0.0) + (wrap * fast::max(dot(-s.N, centerDir), 0.0));
    PBRSurface param = s;
    float3 param_1 = specDir;
    float3 param_2 = radiance;
    float param_3 = NdotL;
    return pbr_lit(param, param_1, param_2, param_3);
}

static inline __attribute__((always_inline))
float3 fresnel_schlick_roughness(thread const float3& F0, thread const float& cosTheta, thread const float& roughness)
{
    return F0 + ((fast::max(float3(1.0 - roughness), F0) - F0) * pow(1.0 - cosTheta, 5.0));
}

static inline __attribute__((always_inline))
float3 display_linear(thread const float3& display)
{
    return pow(fast::max(display, float3(0.0)), float3(2.2000000476837158203125));
}

fragment fs_out fs(fs_in in [[stage_in]], const device LightTableBuffer& _3567 [[buffer(6)]], constant CameraUniforms& _661 [[buffer(3)]], const device LightKeys& _2666 [[buffer(7)]], const device LightZBins& _2553 [[buffer(8)]], constant LightUniforms& _3184 [[buffer(4)]], constant FogUniforms& _1420 [[buffer(5)]], const device LightTiles& _2619 [[buffer(9)]], const device VsmPageTable& _3009 [[buffer(10)]], const device VsmGenerations& _2972 [[buffer(11)]], const device VsmAtlas& _3100 [[buffer(12)]], texture2d<float> gbuffer_position [[texture(0)]], texture2d<float> gbuffer_normal [[texture(1)]], texture2d<float> gbuffer_albedo [[texture(2)]], texture2d<float> gbuffer_material [[texture(3)]], texture2d<float> gbuffer_emissive [[texture(4)]], texture2d<float> gbuffer_id [[texture(5)]], texture2d_array<float> shadowmap [[texture(11)]], texture2d<float> gbuffer_ao [[texture(12)]], texture2d<float> u_fog_sky [[texture(13)]], texture2d_array<float> u_aerial [[texture(14)]], texture2d<float> godrays_resolved [[texture(15)]], sampler gbuffer_positionSmplr [[sampler(0)]], sampler gbuffer_normalSmplr [[sampler(1)]], sampler gbuffer_albedoSmplr [[sampler(2)]], sampler gbuffer_materialSmplr [[sampler(3)]], sampler gbuffer_emissiveSmplr [[sampler(4)]], sampler gbuffer_idSmplr [[sampler(5)]], sampler shadowmapSmplr [[sampler(11)]], sampler gbuffer_aoSmplr [[sampler(12)]], sampler u_fog_skySmplr [[sampler(13)]], sampler u_aerialSmplr [[sampler(14)]], sampler godrays_resolvedSmplr [[sampler(15)]])
{
    fs_out out = {};
    float2 param = in.v_uv;
    float4 position = gbuffer_position_at(param, gbuffer_position, gbuffer_positionSmplr);
    if (position.w < 0.5)
    {
        discard_fragment();
    }
    float2 param_1 = in.v_uv;
    float4 param_2 = position;
    GBuffer gbuffer = gbuffer_make(param_1, param_2, gbuffer_normal, gbuffer_normalSmplr, gbuffer_albedo, gbuffer_albedoSmplr, gbuffer_material, gbuffer_materialSmplr, _661, gbuffer_ao, gbuffer_aoSmplr, gbuffer_emissive, gbuffer_emissiveSmplr, gbuffer_id, gbuffer_idSmplr);
    GBuffer param_3 = gbuffer;
    float3 param_4 = _661.u_camera_position.xyz;
    PBRSurface s = pbr_surface_make(param_3, param_4);
    float3 Lo = float3(0.0);
    float3 transmitted = float3(0.0);
    if (gbuffer.id == 5u)
    {
        float3 param_5 = s.emissive;
        float3 param_6 = gbuffer.relative;
        float2 param_7 = in.v_uv;
        out.fragment_color = float4(fog_apply_rays(param_5, param_6, param_7, _1420, u_fog_sky, u_fog_skySmplr, u_aerial, u_aerialSmplr, godrays_resolved, godrays_resolvedSmplr), 1.0);
        return out;
    }
    bool moonKey = _3184.u_moon_color.w > 0.5;
    float keyVis = 1.0;
    if (_3184.u_shadow.y > 0.5)
    {
        float3 param_8 = s.P;
        int cascade = csm_pick(param_8, _661, _3184);
        float3 _3284;
        if (moonKey)
        {
            _3284 = _3184.u_moon_direction.xyz;
        }
        else
        {
            _3284 = _3184.u_sun_direction.xyz;
        }
        float3 keyDir = _3284;
        float3 param_9 = s.P;
        float3 param_10 = s.N;
        float3 param_11 = fast::normalize(keyDir);
        float4x4 param_12 = _3184.u_light_space[cascade];
        int param_13 = cascade;
        keyVis = 1.0 - shadow_sample(shadowmap, shadowmapSmplr, param_9, param_10, param_11, param_12, param_13);
    }
    if (_3184.u_sun_direction.w > 0.0)
    {
        float3 L = fast::normalize(-_3184.u_sun_direction.xyz);
        float3 radiance = _3184.u_sun_color.xyz * _3184.u_sun_direction.w;
        float vis = moonKey ? 1.0 : keyVis;
        uint param_14 = gbuffer.id;
        float wrap = gbuffer_id_wrap(param_14);
        PBRSurface param_15 = s;
        float3 param_16 = L;
        float3 param_17 = radiance;
        float param_18 = wrap;
        Lo += (pbr_shade_wrapped(param_15, param_16, param_17, param_18) * vis);
        uint param_19 = gbuffer.id;
        float thickness = gbuffer_id_thickness(param_19);
        if (thickness > 0.0)
        {
            float t = pow(fast::clamp(dot(s.V, -L), 0.0, 1.0), 2.0);
            transmitted = (((s.albedo * radiance) * t) * thickness) * vis;
        }
    }
    if (_3184.u_moon_direction.w > 0.0)
    {
        float3 L_1 = fast::normalize(-_3184.u_moon_direction.xyz);
        float3 radiance_1 = _3184.u_moon_color.xyz * _3184.u_moon_direction.w;
        float vis_1 = moonKey ? keyVis : 1.0;
        uint param_20 = gbuffer.id;
        float wrap_1 = gbuffer_id_wrap(param_20);
        PBRSurface param_21 = s;
        float3 param_22 = L_1;
        float3 param_23 = radiance_1;
        float param_24 = wrap_1;
        Lo += (pbr_shade_wrapped(param_21, param_22, param_23, param_24) * vis_1);
        uint param_25 = gbuffer.id;
        float thickness_1 = gbuffer_id_thickness(param_25);
        if (thickness_1 > 0.0)
        {
            float t_1 = pow(fast::clamp(dot(s.V, -L_1), 0.0, 1.0), 2.0);
            transmitted += ((((s.albedo * radiance_1) * t_1) * thickness_1) * vis_1);
        }
    }
    float3 vsmDebug = float3(0.0);
    float viewDepth = -(_661.u_view * float4(s.P, 1.0)).z;
    float param_26 = viewDepth;
    float4 param_27 = _3184.u_cluster_head;
    float4 param_28 = _3184.u_cluster_z;
    uint2 range = light_range(param_26, param_27, param_28, _2553);
    if (range.x <= range.y)
    {
        float2 pixel = fast::min(in.v_uv * _661.u_resolution.xy, _661.u_resolution.xy - float2(1.0));
        float2 param_29 = pixel;
        float4 param_30 = _3184.u_cluster_head;
        uint base = light_tile_base(param_29, param_30);
        float param_31 = viewDepth;
        float param_32 = _661.u_projection[1].y;
        float param_33 = _661.u_resolution.y;
        float footprint = vsm_footprint(param_31, param_32, param_33);
        uint param_34 = gbuffer.id;
        float wrap_2 = gbuffer_id_wrap(param_34);
        uint param_35 = gbuffer.id;
        float thickness_2 = gbuffer_id_thickness(param_35);
        uint _3521 = range.x >> 5u;
        float3 _3675;
        float3 _3682;
        for (uint w = _3521; w <= (range.y >> 5u); w++)
        {
            uint param_36 = base;
            uint param_37 = w;
            uint2 param_38 = range;
            uint bits = light_word(param_36, param_37, param_38, _2619);
            while (bits != 0u)
            {
                uint b = uint(int(spvFindLSB(bits)));
                bits &= (bits - 1u);
                uint param_39 = (w * 32u) + b;
                uint slot = light_slot(param_39, _2666);
                LightGpu _3572;
                _3572.position_radius = _3567.u_lights[slot].position_radius;
                _3572.color_intensity = _3567.u_lights[slot].color_intensity;
                _3572.source = _3567.u_lights[slot].source;
                _3572.flicker = _3567.u_lights[slot].flicker;
                _3572.spot = _3567.u_lights[slot].spot;
                LightGpu l = _3572;
                float4 pr = l.position_radius;
                float3 toLight = pr.xyz - s.P;
                float dist = length(toLight);
                if (dist >= pr.w)
                {
                    continue;
                }
                float3 Lc = toLight / float3(fast::max(dist, 9.9999997473787516355514526367188e-05));
                LightGpu param_40 = l;
                float param_41 = dist;
                float param_42 = _3184.u_cluster_z.w;
                float3 radiance_2 = light_radiance(param_40, param_41, param_42);
                float3 param_43 = toLight;
                float3 param_44 = s.V;
                float3 param_45 = s.N;
                float param_46 = l.source.x;
                float3 Ls = pbr_sphere_l(param_43, param_44, param_45, param_46);
                float vis_2 = 1.0;
                LightGpu param_47 = l;
                float3 param_48 = _661.u_camera_position.xyz;
                float4 param_49 = _3184.u_vsm;
                float fade = vsm_light_fade(param_47, param_48, param_49);
                if (fade > 0.0)
                {
                    uint param_50 = slot;
                    float3 param_51 = pr.xyz;
                    float param_52 = pr.w;
                    float3 param_53 = s.P + (s.N * l.source.z);
                    float param_54 = footprint;
                    float param_55 = _3184.u_vsm.y;
                    float seen = vsm_lookup(param_50, param_51, param_52, param_53, param_54, param_55, _2972, _3009, _3100);
                    vis_2 = mix(1.0, (seen < (-0.5)) ? 1.0 : seen, fade);
                    if (_3184.u_vsm.z > 0.5)
                    {
                        if (seen < (-1.5))
                        {
                            _3675 = float3(1.0, 0.0, 1.0);
                        }
                        else
                        {
                            if (seen < (-0.5))
                            {
                                _3682 = float3(1.0, 0.0, 0.0);
                            }
                            else
                            {
                                _3682 = float3(0.0, seen, 1.0 - seen);
                            }
                            _3675 = _3682;
                        }
                        vsmDebug += _3675;
                    }
                }
                PBRSurface param_56 = s;
                float3 param_57 = Lc;
                float3 param_58 = Ls;
                float3 param_59 = radiance_2;
                float param_60 = wrap_2;
                Lo += (pbr_shade_sphere(param_56, param_57, param_58, param_59, param_60) * vis_2);
                if (thickness_2 > 0.0)
                {
                    float t_2 = pow(fast::clamp(dot(s.V, -Lc), 0.0, 1.0), 2.0);
                    transmitted += ((((s.albedo * radiance_2) * t_2) * thickness_2) * vis_2);
                }
            }
        }
    }
    float3 ambient = float3(0.0);
    float NdotV = fast::max(dot(s.N, s.V), 0.0);
    float3 R = fast::normalize(reflect(-s.V, s.N));
    float3 param_61 = s.F0;
    float param_62 = NdotV;
    float param_63 = s.roughness;
    float3 F = fresnel_schlick_roughness(param_61, param_62, param_63);
    float3 kD = (float3(1.0) - F) * (1.0 - s.metallic);
    float3 diffuseIBL = float3(0.0);
    diffuseIBL = float3(0.02999999932944774627685546875) * s.albedo;
    float3 specIBL = float3(0.0);
    float3 night = _3184.u_night_ambient.xyz * mix(_3184.u_night_ambient.w, 1.0, (s.N.y * 0.5) + 0.5);
    diffuseIBL += (night * s.albedo);
    float3 diffuse = kD * diffuseIBL;
    float3 param_64 = specIBL;
    float3 param_65 = diffuse;
    float param_66 = s.metallic;
    float param_67 = s.roughness;
    specIBL = pbr_dielectric_spec_limit(param_64, param_65, param_66, param_67);
    ambient = diffuse + specIBL;
    float3 color = (((Lo + ambient) * s.ao) + transmitted) + s.emissive;
    float3 param_68 = color;
    float3 param_69 = gbuffer.relative;
    float2 param_70 = in.v_uv;
    color = fog_apply_rays(param_68, param_69, param_70, _1420, u_fog_sky, u_fog_skySmplr, u_aerial, u_aerialSmplr, godrays_resolved, godrays_resolvedSmplr);
    bool _3833 = _3184.u_shadow.z > 0.5;
    bool _3839;
    if (_3833)
    {
        _3839 = _3184.u_shadow.y > 0.5;
    }
    else
    {
        _3839 = _3833;
    }
    if (_3839)
    {
        float3 param_71 = s.P;
        int cascade_1 = csm_pick(param_71, _661, _3184);
        float3 tint = float3(1.0, 0.0, 0.0);
        if (cascade_1 == 1)
        {
            tint = float3(0.0, 1.0, 0.0);
        }
        else
        {
            if (cascade_1 == 2)
            {
                tint = float3(0.0, 0.0, 1.0);
            }
            else
            {
                if (cascade_1 == 3)
                {
                    tint = float3(1.0, 0.0, 1.0);
                }
                else
                {
                    if (cascade_1 == 4)
                    {
                        tint = float3(0.0, 1.0, 1.0);
                    }
                }
            }
        }
        float3 param_72 = tint * 0.1500000059604644775390625;
        color += display_linear(param_72);
    }
    bool _3876 = _3184.u_vsm.z > 0.5;
    bool _3883;
    if (_3876)
    {
        _3883 = dot(vsmDebug, vsmDebug) > 0.0;
    }
    else
    {
        _3883 = _3876;
    }
    if (_3883)
    {
        float3 param_73 = fast::clamp(vsmDebug, float3(0.0), float3(1.0));
        color = display_linear(param_73);
    }
    out.fragment_color = float4(color, 1.0);
    return out;
}

