// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct GBuffer
{
    float3 P;
    float3 relative;
    float3 N;
    float3 albedo;
    float metallic;
    float roughness;
    float ao;
    float3 emissive;
    uint id;
    float coverage;
};

struct PBRSurface
{
    float3 P;
    float3 N;
    float3 V;
    float3 albedo;
    float metallic;
    float roughness;
    float ao;
    float3 emissive;
    float3 F0;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct SkyUniforms
{
    float4 u_sky_sun;
    float4 u_sky_origin;
    float4 u_sky_rayleigh;
    float4 u_sky_mie;
    float4 u_sky_ground;
    float4 u_sky_params;
};

struct FogUniforms
{
    float4 u_fog_density;
    float4 u_fog_color;
    float4 u_fog_params;
    float4 u_fog_sun;
    float4 u_fog_samples;
};

struct LightUniforms
{
    float4 u_sun_direction;
    float4 u_sun_color;
    float4 u_ibl;
    float4x4 u_light_space[5];
    float4 u_splits;
    float4 u_shadow;
};

constant spvUnsafeArray<float, 5> _826 = spvUnsafeArray<float, 5>({ 0.00120000005699694156646728515625, 0.001700000022538006305694580078125, 0.00179999996908009052276611328125, 0.0005000000237487256526947021484375, 0.00120000005699694156646728515625 });

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
};

static inline __attribute__((always_inline))
uint gbuffer_id_decode(thread const float& t)
{
    return uint((t * 255.0) + 0.5);
}

static inline __attribute__((always_inline))
GBuffer gbuffer_make(thread const float2& uv, texture2d<float> gbuffer_position, sampler gbuffer_positionSmplr, texture2d<float> gbuffer_normal, sampler gbuffer_normalSmplr, texture2d<float> gbuffer_albedo, sampler gbuffer_albedoSmplr, texture2d<float> gbuffer_material, sampler gbuffer_materialSmplr, constant CameraUniforms& _502, texture2d<float> gbuffer_ao, sampler gbuffer_aoSmplr, texture2d<float> gbuffer_emissive, sampler gbuffer_emissiveSmplr, texture2d<float> gbuffer_id, sampler gbuffer_idSmplr)
{
    float4 position = gbuffer_position.sample(gbuffer_positionSmplr, uv);
    float4 normal = gbuffer_normal.sample(gbuffer_normalSmplr, uv);
    float4 albedo = gbuffer_albedo.sample(gbuffer_albedoSmplr, uv);
    float4 material = gbuffer_material.sample(gbuffer_materialSmplr, uv);
    GBuffer gbuffer;
    gbuffer.relative = position.xyz;
    gbuffer.P = position.xyz + _502.u_camera_position.xyz;
    gbuffer.N = normal.xyz;
    gbuffer.albedo = albedo.xyz;
    gbuffer.roughness = material.x;
    gbuffer.metallic = material.y;
    gbuffer.ao = material.z * gbuffer_ao.sample(gbuffer_aoSmplr, uv).x;
    gbuffer.emissive = gbuffer_emissive.sample(gbuffer_emissiveSmplr, uv).xyz;
    float param = gbuffer_id.sample(gbuffer_idSmplr, uv).x;
    gbuffer.id = gbuffer_id_decode(param);
    gbuffer.coverage = position.w;
    return gbuffer;
}

static inline __attribute__((always_inline))
PBRSurface pbr_surface_make(thread const GBuffer& gbuffer, thread const float3& camera_position)
{
    PBRSurface s;
    s.P = gbuffer.P;
    s.N = fast::normalize(gbuffer.N);
    s.V = fast::normalize(camera_position - s.P);
    s.albedo = fast::max(gbuffer.albedo, float3(0.0));
    s.metallic = fast::clamp(gbuffer.metallic, 0.0, 1.0);
    s.roughness = fast::clamp(gbuffer.roughness, 0.039999999105930328369140625, 1.0);
    s.ao = fast::clamp(gbuffer.ao, 0.0, 1.0);
    s.emissive = gbuffer.emissive;
    s.F0 = mix(float3(0.039999999105930328369140625), s.albedo, float3(s.metallic));
    return s;
}

static inline __attribute__((always_inline))
float fog_integral(thread const float& dy, thread const float& len, constant FogUniforms& _1269)
{
    float k = _1269.u_fog_density.y;
    float d0 = _1269.u_fog_density.x;
    float x = fast::max((k * dy) * len, -60.0);
    if (abs(x) < 9.9999997473787516355514526367188e-05)
    {
        return (d0 * len) * (1.0 - (0.5 * x));
    }
    return (d0 * (1.0 - exp(-x))) / (k * dy);
}

static inline __attribute__((always_inline))
float3 fog_horizon_dir(thread const float3& dir, constant SkyUniforms& _973)
{
    float2 xz = dir.xz;
    float horiz = length(xz);
    if (horiz < 9.9999997473787516355514526367188e-05)
    {
        xz = _973.u_sky_sun.xz;
        horiz = length(xz);
        if (horiz < 9.9999997473787516355514526367188e-05)
        {
            xz = float2(1.0, 0.0);
            horiz = 1.0;
        }
    }
    xz /= float2(horiz);
    return fast::normalize(float3(xz.x, fast::max(dir.y, 0.0199999995529651641845703125), xz.y));
}

static inline __attribute__((always_inline))
float3 sky_observer(constant SkyUniforms& _973)
{
    return float3(0.0, _973.u_sky_params.z + fast::max(_973.u_sky_origin.y, 1.0), 0.0);
}

static inline __attribute__((always_inline))
float2 sky_ray_sphere(thread const float3& o, thread const float3& d, thread const float& r)
{
    float b = dot(o, d);
    float c = dot(o, o) - (r * r);
    float disc = (b * b) - c;
    if (disc < 0.0)
    {
        return float2(-1.0);
    }
    float s = sqrt(disc);
    return float2((-b) - s, (-b) + s);
}

static inline __attribute__((always_inline))
float2 sky_optical_depth(thread const float3& p, thread const float3& d, thread const float& len, thread const int& samples, constant SkyUniforms& _973)
{
    float step_len = len / float(samples);
    float2 depth = float2(0.0);
    float2 scale = float2(_973.u_sky_rayleigh.w, _973.u_sky_mie.w);
    for (int i = 0; i < samples; i++)
    {
        float3 s = p + (d * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(s) - _973.u_sky_params.z, 0.0);
        depth += (exp(float2(-h) / scale) * step_len);
    }
    return depth;
}

static inline __attribute__((always_inline))
float3 sky_extinction(thread const float2& depth, constant SkyUniforms& _973)
{
    return exp(-((_973.u_sky_rayleigh.xyz * depth.x) + (float3(_973.u_sky_mie.y) * depth.y)));
}

static inline __attribute__((always_inline))
float3 sky_inscatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _973)
{
    float3 o = sky_observer(_973);
    float rg = _973.u_sky_params.z;
    float rt = _973.u_sky_params.w;
    float3 param = o;
    float3 param_1 = dir;
    float param_2 = rt;
    float2 atmo = sky_ray_sphere(param, param_1, param_2);
    float t_max = fast::max(atmo.y, 0.0);
    float3 param_3 = o;
    float3 param_4 = dir;
    float param_5 = rg;
    float2 ground = sky_ray_sphere(param_3, param_4, param_5);
    t_ground = -1.0;
    if (ground.x > 0.0)
    {
        t_ground = ground.x;
        t_max = ground.x;
    }
    float step_len = t_max / float(view_samples);
    float3 to_sun = _973.u_sky_sun.xyz;
    float mu = dot(dir, to_sun);
    float g = _973.u_sky_mie.z;
    float gg = g * g;
    float phase_r = 0.0596831031143665313720703125 * (1.0 + (mu * mu));
    float phase_m = (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / ((2.0 + gg) * pow((1.0 + gg) - ((2.0 * g) * mu), 1.5));
    float2 scale = float2(_973.u_sky_rayleigh.w, _973.u_sky_mie.w);
    float3 sum_r = float3(0.0);
    float3 sum_m = float3(0.0);
    float2 depth_view = float2(0.0);
    for (int i = 0; i < view_samples; i++)
    {
        float3 p = o + (dir * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(p) - rg, 0.0);
        float2 dens = exp(float2(-h) / scale) * step_len;
        depth_view += dens;
        float3 param_6 = p;
        float3 param_7 = to_sun;
        float param_8 = rg;
        float2 sun_ground = sky_ray_sphere(param_6, param_7, param_8);
        if (sun_ground.x > 0.0)
        {
            continue;
        }
        float3 param_9 = p;
        float3 param_10 = to_sun;
        float param_11 = rt;
        float2 sun_atmo = sky_ray_sphere(param_9, param_10, param_11);
        float3 param_12 = p;
        float3 param_13 = to_sun;
        float param_14 = fast::max(sun_atmo.y, 0.0);
        int param_15 = light_samples;
        float2 depth_light = sky_optical_depth(param_12, param_13, param_14, param_15, _973);
        float2 param_16 = depth_view + depth_light;
        float3 t = sky_extinction(param_16, _973);
        sum_r += (t * dens.x);
        sum_m += (t * dens.y);
    }
    float2 param_17 = depth_view;
    transmittance = sky_extinction(param_17, _973);
    return (((sum_r * _973.u_sky_rayleigh.xyz) * phase_r) + ((sum_m * float3(_973.u_sky_mie.x)) * phase_m)) * (_973.u_sky_sun.w * 4.0);
}

static inline __attribute__((always_inline))
float3 fog_color(thread const float3& dir, constant SkyUniforms& _973, constant FogUniforms& _1269)
{
    float3 tint = _1269.u_fog_color.xyz;
    if (_1269.u_fog_color.w < 0.5)
    {
        return tint;
    }
    float3 param = dir;
    float3 param_1 = fog_horizon_dir(param, _973);
    int param_2 = int(_1269.u_fog_samples.x);
    int param_3 = int(_1269.u_fog_samples.y);
    float3 param_4;
    float param_5;
    float3 _1372 = sky_inscatter_n(param_1, param_2, param_3, param_4, param_5, _973);
    float3 transmittance = param_4;
    float t_ground = param_5;
    float3 radiance = _1372;
    return (tint * _973.u_sky_ground.w) * radiance;
}

static inline __attribute__((always_inline))
float3 fog_apply(thread const float3& color, thread const float3& relative, constant SkyUniforms& _973, constant FogUniforms& _1269)
{
    if (_1269.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _1269.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _1269.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _1269);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _1269))), 1.0 - _1269.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _1269.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _1269)));
    float sun = pow(fast::max(dot(dir, _973.u_sky_sun.xyz), 0.0), _1269.u_fog_sun.w);
    float3 param_6 = dir;
    float3 fog = (fog_color(param_6, _973, _1269) * (1.0 - t)) + ((_1269.u_fog_sun.xyz * sun) * (1.0 - td));
    return (color * t) + fog;
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _197;
    if (x < 0.07999999821186065673828125)
    {
        _197 = x - ((6.25 * x) * x);
    }
    else
    {
        _197 = 0.039999999105930328369140625;
    }
    float offset = _197;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _263 = tonemap_neutral(param);
    return _263;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

static inline __attribute__((always_inline))
int csm_index(thread const float& depth, thread const float4& splits)
{
    int shadow_index = 0;
    if (depth < splits.x)
    {
        shadow_index = 1;
    }
    if (depth < splits.y)
    {
        shadow_index = 2;
    }
    if (depth < splits.z)
    {
        shadow_index = 3;
    }
    if (depth < splits.w)
    {
        shadow_index = 4;
    }
    return shadow_index;
}

static inline __attribute__((always_inline))
float2 uv_from_ndc(thread const float2& ndc)
{
    return float2((ndc.x * 0.5) + 0.5, 0.5 - (ndc.y * 0.5));
}

static inline __attribute__((always_inline))
float shadow_sample(texture2d_array<float> shadowmap, sampler shadowmapSmplr, thread const float3& world_position, thread const float3& normal, thread const float3& light_dir, thread const float4x4& light_space, thread const int& shadow_index)
{
    float4 clip = light_space * float4(world_position, 1.0);
    float3 proj = clip.xyz / float3(clip.w);
    float2 param = proj.xy;
    float2 uv = uv_from_ndc(param);
    float current_depth = proj.z;
    bool _790 = uv.x < 0.0;
    bool _797;
    if (!_790)
    {
        _797 = uv.x > 1.0;
    }
    else
    {
        _797 = _790;
    }
    bool _804;
    if (!_797)
    {
        _804 = uv.y < 0.0;
    }
    else
    {
        _804 = _797;
    }
    bool _811;
    if (!_804)
    {
        _811 = uv.y > 1.0;
    }
    else
    {
        _811 = _804;
    }
    if (_811 || (current_depth > 1.0))
    {
        return 0.0;
    }
    float min_bias = _826[shadow_index];
    float bias0 = fast::max(min_bias * (1.0 - dot(normal, light_dir)), min_bias);
    float shadow = 0.0;
    float3 texel = float3(1.0) / float3(int3(shadowmap.get_width(), shadowmap.get_height(), shadowmap.get_array_size()));
    for (int x = -1; x <= 1; x++)
    {
        for (int y = -1; y <= 1; y++)
        {
            float2 sample_uv = uv + (float2(float(x), float(y)) * texel.xy);
            bool _879 = sample_uv.x < 0.0;
            bool _886;
            if (!_879)
            {
                _886 = sample_uv.x > 1.0;
            }
            else
            {
                _886 = _879;
            }
            bool _893;
            if (!_886)
            {
                _893 = sample_uv.y < 0.0;
            }
            else
            {
                _893 = _886;
            }
            bool _900;
            if (!_893)
            {
                _900 = sample_uv.y > 1.0;
            }
            else
            {
                _900 = _893;
            }
            if (_900)
            {
                continue;
            }
            float3 _911 = float3(sample_uv, float(shadow_index));
            float closest = shadowmap.sample(shadowmapSmplr, _911.xy, uint(rint(_911.z))).x;
            shadow += float((current_depth - bias0) > closest);
        }
    }
    return fast::clamp(shadow / 9.0, 0.0, 1.0);
}

static inline __attribute__((always_inline))
float gbuffer_id_wrap(thread const uint& id)
{
    if (id == 3u)
    {
        return 0.550000011920928955078125;
    }
    if (id == 4u)
    {
        return 0.20000000298023223876953125;
    }
    return 0.0;
}

static inline __attribute__((always_inline))
float distribution_GGX(thread const float& NdotH, thread const float& roughness)
{
    float alpha = roughness * roughness;
    float alphaSqr = alpha * alpha;
    float denom = ((NdotH * NdotH) * (alphaSqr - 1.0)) + 1.0;
    float D = alphaSqr / ((3.1415927410125732421875 * denom) * denom);
    return D;
}

static inline __attribute__((always_inline))
float geometry_smith_ggx_correlated(thread const float& NdotL, thread const float& NdotV, thread const float& roughness)
{
    float a = roughness * roughness;
    float a2 = a * a;
    float gv = NdotL * sqrt(a2 + (((1.0 - a2) * NdotV) * NdotV));
    float gl = NdotV * sqrt(a2 + (((1.0 - a2) * NdotL) * NdotL));
    return ((2.0 * NdotL) * NdotV) / fast::max(gv + gl, 9.9999999747524270787835121154785e-07);
}

static inline __attribute__((always_inline))
float3 fresnel_schlick(thread const float3& F0, thread const float& cosTheta)
{
    return F0 + ((float3(1.0) - F0) * pow(1.0 - cosTheta, 5.0));
}

static inline __attribute__((always_inline))
float3 pbr_specular(thread const float3& N, thread const float3& V, thread const float3& H, thread const float3& L, thread const float3& F0, thread const float& roughness, thread float3& fresnel)
{
    float NdotH = fast::max(9.9999997473787516355514526367188e-06, dot(N, H));
    float NdotV = fast::max(dot(N, V), 0.0);
    float NdotL = fast::max(dot(N, L), 0.0);
    float VdotH = fast::max(9.9999997473787516355514526367188e-06, dot(V, H));
    if ((NdotV <= 0.0) || (NdotL <= 0.0))
    {
        fresnel = float3(0.0);
        return float3(0.0);
    }
    float param = NdotH;
    float param_1 = roughness;
    float D = distribution_GGX(param, param_1);
    float param_2 = NdotL;
    float param_3 = NdotV;
    float param_4 = roughness;
    float G = geometry_smith_ggx_correlated(param_2, param_3, param_4);
    float3 param_5 = F0;
    float param_6 = VdotH;
    fresnel = fresnel_schlick(param_5, param_6);
    float denom = fast::max((4.0 * NdotV) * NdotL, 9.9999999747524270787835121154785e-07);
    return ((fresnel * D) * G) / float3(denom);
}

static inline __attribute__((always_inline))
float pbr_peak(thread const float3& c)
{
    return fast::max(c.x, fast::max(c.y, c.z));
}

static inline __attribute__((always_inline))
float3 pbr_dielectric_spec_limit(thread const float3& spec, thread const float3& diffuse, thread const float& metallic, thread const float& roughness)
{
    float3 param = spec;
    float specL = pbr_peak(param);
    float3 param_1 = diffuse;
    float cap = fast::max(pbr_peak(param_1), 0.0199999995529651641845703125);
    float scale = fast::min(1.0, cap / fast::max(specL, 9.9999997473787516355514526367188e-06));
    return spec * mix(1.0, scale, (1.0 - metallic) * roughness);
}

static inline __attribute__((always_inline))
float3 pbr_lit(thread const PBRSurface& s, thread const float3& L, thread const float3& radiance, thread const float& NdotL)
{
    float3 H = fast::normalize(s.V + L);
    float3 param = s.N;
    float3 param_1 = s.V;
    float3 param_2 = H;
    float3 param_3 = L;
    float3 param_4 = s.F0;
    float param_5 = s.roughness;
    float3 param_6;
    float3 _663 = pbr_specular(param, param_1, param_2, param_3, param_4, param_5, param_6);
    float3 F = param_6;
    float3 spec = _663;
    float3 kD = (float3(1.0) - F) * (1.0 - s.metallic);
    float3 diff = (kD * s.albedo) / float3(3.1415927410125732421875);
    float3 param_7 = spec;
    float3 param_8 = diff;
    float param_9 = s.metallic;
    float param_10 = s.roughness;
    spec = pbr_dielectric_spec_limit(param_7, param_8, param_9, param_10);
    return ((diff + spec) * radiance) * NdotL;
}

static inline __attribute__((always_inline))
float3 pbr_shade_wrapped(thread const PBRSurface& s, thread const float3& L, thread const float3& radiance, thread const float& wrap)
{
    float NdotL = fast::max(dot(s.N, L), 0.0) + (wrap * fast::max(dot(-s.N, L), 0.0));
    PBRSurface param = s;
    float3 param_1 = L;
    float3 param_2 = radiance;
    float param_3 = NdotL;
    return pbr_lit(param, param_1, param_2, param_3);
}

static inline __attribute__((always_inline))
float gbuffer_id_thickness(thread const uint& id)
{
    if (id == 3u)
    {
        return 0.550000011920928955078125;
    }
    if (id == 4u)
    {
        return 0.25;
    }
    return 0.0;
}

static inline __attribute__((always_inline))
float3 fresnel_schlick_roughness(thread const float3& F0, thread const float& cosTheta, thread const float& roughness)
{
    return F0 + ((fast::max(float3(1.0 - roughness), F0) - F0) * pow(1.0 - cosTheta, 5.0));
}

fragment fs_out fs(fs_in in [[stage_in]], constant SkyUniforms& _973 [[buffer(2)]], constant CameraUniforms& _502 [[buffer(3)]], constant LightUniforms& _1547 [[buffer(4)]], constant FogUniforms& _1269 [[buffer(5)]], texture2d<float> gbuffer_position [[texture(0)]], texture2d<float> gbuffer_normal [[texture(1)]], texture2d<float> gbuffer_albedo [[texture(2)]], texture2d<float> gbuffer_material [[texture(3)]], texture2d<float> gbuffer_emissive [[texture(4)]], texture2d<float> gbuffer_id [[texture(5)]], texturecube<float> environment_cubemap [[texture(6)]], texture2d_array<float> shadowmap [[texture(11)]], texture2d<float> gbuffer_ao [[texture(12)]], sampler gbuffer_positionSmplr [[sampler(0)]], sampler gbuffer_normalSmplr [[sampler(1)]], sampler gbuffer_albedoSmplr [[sampler(2)]], sampler gbuffer_materialSmplr [[sampler(3)]], sampler gbuffer_emissiveSmplr [[sampler(4)]], sampler gbuffer_idSmplr [[sampler(5)]], sampler environment_cubemapSmplr [[sampler(6)]], sampler shadowmapSmplr [[sampler(11)]], sampler gbuffer_aoSmplr [[sampler(12)]])
{
    fs_out out = {};
    float2 param = in.v_uv;
    GBuffer gbuffer = gbuffer_make(param, gbuffer_position, gbuffer_positionSmplr, gbuffer_normal, gbuffer_normalSmplr, gbuffer_albedo, gbuffer_albedoSmplr, gbuffer_material, gbuffer_materialSmplr, _502, gbuffer_ao, gbuffer_aoSmplr, gbuffer_emissive, gbuffer_emissiveSmplr, gbuffer_id, gbuffer_idSmplr);
    if (gbuffer.coverage < 0.5)
    {
        discard_fragment();
    }
    GBuffer param_1 = gbuffer;
    float3 param_2 = _502.u_camera_position.xyz;
    PBRSurface s = pbr_surface_make(param_1, param_2);
    float3 Lo = float3(0.0);
    float3 transmitted = float3(0.0);
    if (gbuffer.id == 5u)
    {
        float3 param_3 = s.emissive;
        float3 param_4 = gbuffer.relative;
        float3 unlit = fog_apply(param_3, param_4, _973, _1269);
        float3 param_5 = unlit;
        unlit = apply_tonemap(param_5);
        float3 param_6 = unlit;
        unlit = gamma_correct(param_6);
        out.fragment_color = float4(unlit, 1.0);
        return out;
    }
    float3 L = fast::normalize(-_1547.u_sun_direction.xyz);
    float3 radiance = _1547.u_sun_color.xyz * _1547.u_sun_direction.w;
    float vis = 1.0;
    if (_1547.u_shadow.y > 0.5)
    {
        float view_z = (_502.u_view * float4(s.P, 1.0)).z;
        float param_7 = view_z;
        float4 param_8 = _1547.u_splits;
        int cascade = csm_index(param_7, param_8);
        float3 param_9 = s.P;
        float3 param_10 = s.N;
        float3 param_11 = fast::normalize(_1547.u_sun_direction.xyz);
        float4x4 param_12 = _1547.u_light_space[cascade];
        int param_13 = cascade;
        vis = 1.0 - shadow_sample(shadowmap, shadowmapSmplr, param_9, param_10, param_11, param_12, param_13);
    }
    uint param_14 = gbuffer.id;
    float wrap = gbuffer_id_wrap(param_14);
    PBRSurface param_15 = s;
    float3 param_16 = L;
    float3 param_17 = radiance;
    float param_18 = wrap;
    Lo += (pbr_shade_wrapped(param_15, param_16, param_17, param_18) * vis);
    uint param_19 = gbuffer.id;
    float thickness = gbuffer_id_thickness(param_19);
    if (thickness > 0.0)
    {
        float t = pow(fast::clamp(dot(s.V, -L), 0.0, 1.0), 2.0);
        transmitted = (((s.albedo * radiance) * t) * thickness) * vis;
    }
    float3 ambient = float3(0.0);
    float NdotV = fast::max(dot(s.N, s.V), 0.0);
    float3 R = fast::normalize(reflect(-s.V, s.N));
    float3 param_20 = s.F0;
    float param_21 = NdotV;
    float param_22 = s.roughness;
    float3 F = fresnel_schlick_roughness(param_20, param_21, param_22);
    float3 kD = (float3(1.0) - F) * (1.0 - s.metallic);
    float3 diffuseIBL = float3(0.0);
    diffuseIBL = float3(0.02999999932944774627685546875) * s.albedo;
    float3 specIBL = float3(0.0);
    float maxLod = fast::max(_1547.u_ibl.y - 2.0, 0.0);
    float3 env = environment_cubemap.sample(environment_cubemapSmplr, R, level(s.roughness * maxLod)).xyz;
    specIBL = env * F;
    float3 diffuse = kD * diffuseIBL;
    float3 param_23 = specIBL;
    float3 param_24 = diffuse;
    float param_25 = s.metallic;
    float param_26 = s.roughness;
    specIBL = pbr_dielectric_spec_limit(param_23, param_24, param_25, param_26);
    ambient = diffuse + specIBL;
    float3 color = (((Lo + ambient) * s.ao) + transmitted) + s.emissive;
    float3 param_27 = color;
    float3 param_28 = gbuffer.relative;
    color = fog_apply(param_27, param_28, _973, _1269);
    float3 param_29 = color;
    color = apply_tonemap(param_29);
    float3 param_30 = color;
    color = gamma_correct(param_30);
    bool _1755 = _1547.u_shadow.z > 0.5;
    bool _1761;
    if (_1755)
    {
        _1761 = _1547.u_shadow.y > 0.5;
    }
    else
    {
        _1761 = _1755;
    }
    if (_1761)
    {
        float view_z_1 = (_502.u_view * float4(s.P, 1.0)).z;
        float param_31 = view_z_1;
        float4 param_32 = _1547.u_splits;
        int cascade_1 = csm_index(param_31, param_32);
        float3 tint = float3(1.0, 0.0, 0.0);
        if (cascade_1 == 1)
        {
            tint = float3(0.0, 1.0, 0.0);
        }
        else
        {
            if (cascade_1 == 2)
            {
                tint = float3(0.0, 0.0, 1.0);
            }
            else
            {
                if (cascade_1 == 3)
                {
                    tint = float3(1.0, 0.0, 1.0);
                }
                else
                {
                    if (cascade_1 == 4)
                    {
                        tint = float3(0.0, 1.0, 1.0);
                    }
                }
            }
        }
        color += (tint * 0.1500000059604644775390625);
    }
    out.fragment_color = float4(color, 1.0);
    return out;
}

