// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct GBuffer
{
    float3 P;
    float3 N;
    float3 albedo;
    float metallic;
    float roughness;
    float ao;
    float3 emissive;
    float coverage;
};

struct PBRSurface
{
    float3 P;
    float3 N;
    float3 V;
    float3 albedo;
    float metallic;
    float roughness;
    float ao;
    float3 emissive;
    float3 F0;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct LightUniforms
{
    float4 u_sun_direction;
    float4 u_sun_color;
    float4 u_ibl;
};

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
};

static inline __attribute__((always_inline))
GBuffer gbuffer_make(thread const float2& uv, texture2d<float> gbuffer_position, sampler gbuffer_positionSmplr, texture2d<float> gbuffer_normal, sampler gbuffer_normalSmplr, texture2d<float> gbuffer_albedo, sampler gbuffer_albedoSmplr, texture2d<float> gbuffer_material, sampler gbuffer_materialSmplr, constant CameraUniforms& _365, texture2d<float> gbuffer_ao, sampler gbuffer_aoSmplr, texture2d<float> gbuffer_emissive, sampler gbuffer_emissiveSmplr)
{
    float4 position = gbuffer_position.sample(gbuffer_positionSmplr, uv);
    float4 normal = gbuffer_normal.sample(gbuffer_normalSmplr, uv);
    float4 albedo = gbuffer_albedo.sample(gbuffer_albedoSmplr, uv);
    float4 material = gbuffer_material.sample(gbuffer_materialSmplr, uv);
    GBuffer gbuffer;
    gbuffer.P = position.xyz + _365.u_camera_position.xyz;
    gbuffer.N = normal.xyz;
    gbuffer.albedo = albedo.xyz;
    gbuffer.roughness = material.x;
    gbuffer.metallic = material.y;
    gbuffer.ao = material.z * gbuffer_ao.sample(gbuffer_aoSmplr, uv).x;
    gbuffer.emissive = gbuffer_emissive.sample(gbuffer_emissiveSmplr, uv).xyz;
    gbuffer.coverage = position.w;
    return gbuffer;
}

static inline __attribute__((always_inline))
PBRSurface pbr_surface_make(thread const GBuffer& gbuffer, thread const float3& camera_position)
{
    PBRSurface s;
    s.P = gbuffer.P;
    s.N = fast::normalize(gbuffer.N);
    s.V = fast::normalize(camera_position - s.P);
    s.albedo = fast::max(gbuffer.albedo, float3(0.0));
    s.metallic = fast::clamp(gbuffer.metallic, 0.0, 1.0);
    s.roughness = fast::clamp(gbuffer.roughness, 0.039999999105930328369140625, 1.0);
    s.ao = fast::clamp(gbuffer.ao, 0.0, 1.0);
    s.emissive = gbuffer.emissive;
    s.F0 = mix(float3(0.039999999105930328369140625), s.albedo, float3(s.metallic));
    return s;
}

static inline __attribute__((always_inline))
float distribution_GGX(thread const float& NdotH, thread const float& roughness)
{
    float alpha = roughness * roughness;
    float alphaSqr = alpha * alpha;
    float denom = ((NdotH * NdotH) * (alphaSqr - 1.0)) + 1.0;
    float D = alphaSqr / ((3.1415927410125732421875 * denom) * denom);
    return D;
}

static inline __attribute__((always_inline))
float geometry_smith_ggx_correlated(thread const float& NdotL, thread const float& NdotV, thread const float& roughness)
{
    float a = roughness * roughness;
    float a2 = a * a;
    float gv = NdotL * sqrt(a2 + (((1.0 - a2) * NdotV) * NdotV));
    float gl = NdotV * sqrt(a2 + (((1.0 - a2) * NdotL) * NdotL));
    return ((2.0 * NdotL) * NdotV) / fast::max(gv + gl, 9.9999999747524270787835121154785e-07);
}

static inline __attribute__((always_inline))
float3 fresnel_schlick(thread const float3& F0, thread const float& cosTheta)
{
    return F0 + ((float3(1.0) - F0) * pow(1.0 - cosTheta, 5.0));
}

static inline __attribute__((always_inline))
float3 pbr_specular(thread const float3& N, thread const float3& V, thread const float3& H, thread const float3& L, thread const float3& F0, thread const float& roughness, thread float3& fresnel)
{
    float NdotH = fast::max(9.9999997473787516355514526367188e-06, dot(N, H));
    float NdotV = fast::max(dot(N, V), 0.0);
    float NdotL = fast::max(dot(N, L), 0.0);
    float VdotH = fast::max(9.9999997473787516355514526367188e-06, dot(V, H));
    if ((NdotV <= 0.0) || (NdotL <= 0.0))
    {
        fresnel = float3(0.0);
        return float3(0.0);
    }
    float param = NdotH;
    float param_1 = roughness;
    float D = distribution_GGX(param, param_1);
    float param_2 = NdotL;
    float param_3 = NdotV;
    float param_4 = roughness;
    float G = geometry_smith_ggx_correlated(param_2, param_3, param_4);
    float3 param_5 = F0;
    float param_6 = VdotH;
    fresnel = fresnel_schlick(param_5, param_6);
    float denom = fast::max((4.0 * NdotV) * NdotL, 9.9999999747524270787835121154785e-07);
    return ((fresnel * D) * G) / float3(denom);
}

static inline __attribute__((always_inline))
float3 pbr_shade(thread const PBRSurface& s, thread const float3& L, thread const float3& radiance)
{
    float NdotL = fast::max(dot(s.N, L), 0.0);
    float3 H = fast::normalize(s.V + L);
    float VdotH = fast::max(dot(s.V, H), 0.0);
    float3 param = s.N;
    float3 param_1 = s.V;
    float3 param_2 = H;
    float3 param_3 = L;
    float3 param_4 = s.F0;
    float param_5 = s.roughness;
    float3 param_6;
    float3 _495 = pbr_specular(param, param_1, param_2, param_3, param_4, param_5, param_6);
    float3 F = param_6;
    float3 spec = _495;
    float3 kS = F;
    float3 kD = (float3(1.0) - kS) * (1.0 - s.metallic);
    float3 diff = (kD * s.albedo) / float3(3.1415927410125732421875);
    return ((diff + spec) * radiance) * NdotL;
}

static inline __attribute__((always_inline))
float3 fresnel_schlick_roughness(thread const float3& F0, thread const float& cosTheta, thread const float& roughness)
{
    return F0 + ((fast::max(float3(1.0 - roughness), F0) - F0) * pow(1.0 - cosTheta, 5.0));
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _97;
    if (x < 0.07999999821186065673828125)
    {
        _97 = x - ((6.25 * x) * x);
    }
    else
    {
        _97 = 0.039999999105930328369140625;
    }
    float offset = _97;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _163 = tonemap_neutral(param);
    return _163;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(fs_in in [[stage_in]], constant CameraUniforms& _365 [[buffer(3)]], constant LightUniforms& _548 [[buffer(4)]], texture2d<float> gbuffer_position [[texture(0)]], texture2d<float> gbuffer_normal [[texture(1)]], texture2d<float> gbuffer_albedo [[texture(2)]], texture2d<float> gbuffer_material [[texture(3)]], texture2d<float> gbuffer_emissive [[texture(4)]], texture2d<float> gbuffer_ao [[texture(5)]], texturecube<float> ibl_irradiance_map [[texture(6)]], texturecube<float> ibl_prefilter_map [[texture(7)]], texture2d<float> ibl_brdf_lut [[texture(8)]], sampler gbuffer_positionSmplr [[sampler(0)]], sampler gbuffer_normalSmplr [[sampler(1)]], sampler gbuffer_albedoSmplr [[sampler(2)]], sampler gbuffer_materialSmplr [[sampler(3)]], sampler gbuffer_emissiveSmplr [[sampler(4)]], sampler gbuffer_aoSmplr [[sampler(5)]], sampler ibl_irradiance_mapSmplr [[sampler(6)]], sampler ibl_prefilter_mapSmplr [[sampler(7)]], sampler ibl_brdf_lutSmplr [[sampler(8)]])
{
    fs_out out = {};
    float2 param = in.v_uv;
    GBuffer gbuffer = gbuffer_make(param, gbuffer_position, gbuffer_positionSmplr, gbuffer_normal, gbuffer_normalSmplr, gbuffer_albedo, gbuffer_albedoSmplr, gbuffer_material, gbuffer_materialSmplr, _365, gbuffer_ao, gbuffer_aoSmplr, gbuffer_emissive, gbuffer_emissiveSmplr);
    if (gbuffer.coverage < 0.5)
    {
        discard_fragment();
    }
    GBuffer param_1 = gbuffer;
    float3 param_2 = _365.u_camera_position.xyz;
    PBRSurface s = pbr_surface_make(param_1, param_2);
    float3 Lo = float3(0.0);
    float3 L = fast::normalize(-_548.u_sun_direction.xyz);
    float3 radiance = _548.u_sun_color.xyz * _548.u_sun_direction.w;
    PBRSurface param_3 = s;
    float3 param_4 = L;
    float3 param_5 = radiance;
    Lo += pbr_shade(param_3, param_4, param_5);
    float3 ambient = float3(0.0);
    float NdotV = fast::max(dot(s.N, s.V), 0.0);
    float3 R = fast::normalize(reflect(-s.V, s.N));
    float3 param_6 = s.F0;
    float param_7 = NdotV;
    float param_8 = s.roughness;
    float3 F = fresnel_schlick_roughness(param_6, param_7, param_8);
    float3 kS = F;
    float3 kD = (float3(1.0) - kS) * (1.0 - s.metallic);
    float3 diffuseIBL = float3(0.0);
    float3 irradiance = ibl_irradiance_map.sample(ibl_irradiance_mapSmplr, s.N, level(0.0)).xyz;
    diffuseIBL = (irradiance * s.albedo) / float3(3.1415927410125732421875);
    float3 specIBL = float3(0.0);
    float maxLod = fast::max(_548.u_ibl.x - 1.0, 0.0);
    float3 prefiltered = ibl_prefilter_map.sample(ibl_prefilter_mapSmplr, R, level(s.roughness * maxLod)).xyz;
    float2 brdf = ibl_brdf_lut.sample(ibl_brdf_lutSmplr, float2(NdotV, s.roughness)).xy;
    specIBL = prefiltered * ((s.F0 * brdf.x) + float3(brdf.y));
    ambient = ((kD * diffuseIBL) * s.ao) + (specIBL * s.ao);
    float3 color = (Lo + ambient) + s.emissive;
    float3 param_9 = color;
    color = apply_tonemap(param_9);
    float3 param_10 = color;
    color = gamma_correct(param_10);
    out.fragment_color = float4(color, 1.0);
    return out;
}

