// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct ModelMaterialData
{
    float4 u_base_color;
    float4 u_factors;
    float4 u_uv_scale;
};

struct fs_out
{
    float4 gbuffer_out_position [[color(0)]];
    float4 gbuffer_out_normal [[color(1)]];
    float4 gbuffer_out_albedo [[color(2)]];
    float4 gbuffer_out_material [[color(3)]];
    float4 gbuffer_out_emissive [[color(4)]];
    float4 gbuffer_out_id [[color(5)]];
};

struct fs_in
{
    float3 v_position [[user(locn0)]];
    float3 v_normal [[user(locn1)]];
    float4 v_tangent [[user(locn2)]];
    float2 v_uv [[user(locn3)]];
    float4 v_tint [[user(locn4)]];
};

static inline __attribute__((always_inline))
float gbuffer_id_encode(thread const uint& id)
{
    return float(id) / 255.0;
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread const uint& id, thread float4& gbuffer_out_position, constant CameraUniforms& _50, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    gbuffer_out_position = float4(position - _50.u_camera_position.xyz, 1.0);
    gbuffer_out_normal = float4(normal, 0.0);
    gbuffer_out_albedo = float4(albedo, 1.0);
    gbuffer_out_material = float4(roughness, metallic, fast::clamp(ao, 0.0, 1.0), 1.0);
    gbuffer_out_emissive = float4(emissive, 1.0);
    uint param = id;
    gbuffer_out_id = float4(gbuffer_id_encode(param), 0.0, 0.0, 1.0);
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread float4& gbuffer_out_position, constant CameraUniforms& _50, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    float3 param = position;
    float3 param_1 = normal;
    float3 param_2 = albedo;
    float param_3 = metallic;
    float param_4 = roughness;
    float3 param_5 = emissive;
    float param_6 = ao;
    uint param_7 = 1u;
    gbuffer_write(param, param_1, param_2, param_3, param_4, param_5, param_6, param_7, gbuffer_out_position, _50, gbuffer_out_normal, gbuffer_out_albedo, gbuffer_out_material, gbuffer_out_emissive, gbuffer_out_id);
}

fragment fs_out fs(fs_in in [[stage_in]], constant ModelMaterialData& _118 [[buffer(2)]], constant CameraUniforms& _50 [[buffer(3)]], texture2d<float> map_albedo [[texture(0)]], texture2d<float> map_normal [[texture(1)]], texture2d<float> map_roughness [[texture(2)]], texture2d<float> map_metallic [[texture(3)]], texture2d<float> map_ao [[texture(4)]], texture2d<float> map_alpha [[texture(5)]], sampler map_albedoSmplr [[sampler(0)]], sampler map_normalSmplr [[sampler(1)]], sampler map_roughnessSmplr [[sampler(2)]], sampler map_metallicSmplr [[sampler(3)]], sampler map_aoSmplr [[sampler(4)]], sampler map_alphaSmplr [[sampler(5)]], bool gl_FrontFacing [[front_facing]])
{
    fs_out out = {};
    float2 uv = in.v_uv * _118.u_uv_scale.xy;
    int flags = int(_118.u_factors.z + 0.5);
    float3 albedo = _118.u_base_color.xyz;
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        float4 sampled = map_albedo.sample(map_albedoSmplr, uv);
        albedo = sampled.xyz;
        alpha = sampled.w;
    }
    if ((flags & 32) != 0)
    {
        alpha = map_alpha.sample(map_alphaSmplr, uv).x;
    }
    bool _174 = _118.u_base_color.w > 0.0;
    bool _181;
    if (_174)
    {
        _181 = alpha < _118.u_base_color.w;
    }
    else
    {
        _181 = _174;
    }
    if (_181)
    {
        discard_fragment();
    }
    albedo *= in.v_tint.xyz;
    float3 n = fast::normalize(in.v_normal);
    if (!gl_FrontFacing)
    {
        n = -n;
    }
    if ((flags & 2) != 0)
    {
        float3 t = fast::normalize(in.v_tangent.xyz);
        t = fast::normalize(t - (n * dot(n, t)));
        float3 b = cross(n, t) * in.v_tangent.w;
        float3 tn = (map_normal.sample(map_normalSmplr, uv).xyz * 2.0) - float3(1.0);
        n = fast::normalize(float3x3(float3(t), float3(b), float3(n)) * tn);
    }
    float roughness = _118.u_factors.x;
    if ((flags & 4) != 0)
    {
        roughness = map_roughness.sample(map_roughnessSmplr, uv).x;
    }
    float metallic = _118.u_factors.y;
    if ((flags & 8) != 0)
    {
        metallic = map_metallic.sample(map_metallicSmplr, uv).x;
    }
    float ao = 1.0;
    if ((flags & 16) != 0)
    {
        ao = map_ao.sample(map_aoSmplr, uv).x;
    }
    float3 param = in.v_position;
    float3 param_1 = n;
    float3 param_2 = albedo;
    float param_3 = metallic;
    float param_4 = roughness;
    float3 param_5 = float3(0.0);
    float param_6 = ao;
    gbuffer_write(param, param_1, param_2, param_3, param_4, param_5, param_6, out.gbuffer_out_position, _50, out.gbuffer_out_normal, out.gbuffer_out_albedo, out.gbuffer_out_material, out.gbuffer_out_emissive, out.gbuffer_out_id);
    return out;
}

