// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float3 v_position [[user(locn0)]];
    float3 v_normal [[user(locn1)]];
    float4 v_tangent [[user(locn2)]];
    float2 v_uv [[user(locn3)]];
    float4 v_tint [[user(locn4)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 a_position [[attribute(0)]];
    float3 a_normal [[attribute(1)]];
    float4 a_tangent [[attribute(2)]];
    float2 a_uv [[attribute(3)]];
    float4 a_model0 [[attribute(4)]];
    float4 a_model1 [[attribute(5)]];
    float4 a_model2 [[attribute(6)]];
    float4 a_model3 [[attribute(7)]];
    float4 a_tint [[attribute(8)]];
};

vertex vs_out vs(vs_in in [[stage_in]], constant CameraUniforms& _111 [[buffer(3)]])
{
    vs_out out = {};
    float4x4 model = float4x4(float4(in.a_model0), float4(in.a_model1), float4(in.a_model2), float4(in.a_model3));
    float4 world = model * float4(in.a_position, 1.0);
    float3x3 rotation = float3x3(model[0].xyz, model[1].xyz, model[2].xyz);
    out.v_position = world.xyz;
    out.v_normal = fast::normalize(rotation * in.a_normal);
    out.v_tangent = float4(fast::normalize(rotation * in.a_tangent.xyz), in.a_tangent.w);
    out.v_uv = in.a_uv;
    out.v_tint = in.a_tint;
    out.gl_Position = _111.u_projection_view * world;
    return out;
}

