// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct ModelMaterialData
{
    float4 u_base_color;
    float4 u_factors;
    float4 u_uv_scale;
    float4 u_emissive;
};

struct fs_out
{
    float4 gbuffer_out_position [[color(0)]];
    float4 gbuffer_out_normal [[color(1)]];
    float4 gbuffer_out_albedo [[color(2)]];
    float4 gbuffer_out_material [[color(3)]];
    float4 gbuffer_out_emissive [[color(4)]];
    float4 gbuffer_out_id [[color(5)]];
};

struct fs_in
{
    float3 v_position [[user(locn0)]];
    float3 v_normal [[user(locn1)]];
    float4 v_tangent [[user(locn2)]];
    float2 v_uv [[user(locn3)]];
    float4 v_tint [[user(locn4)]];
};

static inline __attribute__((always_inline))
float parallax_fade(thread const float& dist, thread const float& fade)
{
    return 1.0 - smoothstep(0.75 * fade, fade, dist);
}

static inline __attribute__((always_inline))
float3 parallax_view(thread const float3& t, thread const float3& b, thread const float3& n, thread const float3& to_eye)
{
    return float3(dot(to_eye, t), dot(to_eye, b), dot(to_eye, n));
}

static inline __attribute__((always_inline))
float parallax_height(thread const float2& uv, thread const float2& dx, thread const float2& dy, texture2d<float> map_height, sampler map_heightSmplr)
{
    return map_height.sample(map_heightSmplr, uv, gradient2d(dx, dy)).x;
}

static inline __attribute__((always_inline))
float2 parallax_offset(thread const float2& uv, thread const float3& view_ts, thread const float& depth, thread const float& max_steps, thread const float2& dx, thread const float2& dy, texture2d<float> map_height, sampler map_heightSmplr)
{
    float head_on = fast::clamp(view_ts.z, 0.0, 1.0);
    float top = fast::clamp(max_steps, 1.0, 64.0);
    float steps = floor(mix(top, fast::max(4.0, top * 0.25), head_on));
    float layer = 1.0 / steps;
    float2 step_uv = (view_ts.xy / float2(fast::max(view_ts.z, 0.20000000298023223876953125))) * (depth * layer);
    float2 at = uv;
    float ray = 1.0;
    float2 param = at;
    float2 param_1 = dx;
    float2 param_2 = dy;
    float h = parallax_height(param, param_1, param_2, map_height, map_heightSmplr);
    float prev_h = h;
    float prev_ray = ray;
    for (int i = 0; i < 64; i++)
    {
        if ((float(i) >= steps) || (ray <= h))
        {
            break;
        }
        prev_h = h;
        prev_ray = ray;
        at -= step_uv;
        ray -= layer;
        float2 param_3 = at;
        float2 param_4 = dx;
        float2 param_5 = dy;
        h = parallax_height(param_3, param_4, param_5, map_height, map_heightSmplr);
    }
    float below = h - ray;
    float above = prev_h - prev_ray;
    float w = below / fast::max(below - above, 9.9999997473787516355514526367188e-06);
    return mix(at, at + step_uv, float2(w));
}

static inline __attribute__((always_inline))
float gbuffer_id_encode(thread const uint& id)
{
    return float(id) / 255.0;
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread const uint& id, thread float4& gbuffer_out_position, constant CameraUniforms& _79, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    gbuffer_out_position = float4(position - _79.u_camera_position.xyz, 1.0);
    gbuffer_out_normal = float4(normal, 0.0);
    gbuffer_out_albedo = float4(albedo, 1.0);
    gbuffer_out_material = float4(roughness, metallic, fast::clamp(ao, 0.0, 1.0), 1.0);
    gbuffer_out_emissive = float4(emissive, 1.0);
    uint param = id;
    gbuffer_out_id = float4(gbuffer_id_encode(param), 0.0, 0.0, 1.0);
}

static inline __attribute__((always_inline))
void gbuffer_write(thread const float3& position, thread const float3& normal, thread const float3& albedo, thread const float& metallic, thread const float& roughness, thread const float3& emissive, thread const float& ao, thread float4& gbuffer_out_position, constant CameraUniforms& _79, thread float4& gbuffer_out_normal, thread float4& gbuffer_out_albedo, thread float4& gbuffer_out_material, thread float4& gbuffer_out_emissive, thread float4& gbuffer_out_id)
{
    float3 param = position;
    float3 param_1 = normal;
    float3 param_2 = albedo;
    float param_3 = metallic;
    float param_4 = roughness;
    float3 param_5 = emissive;
    float param_6 = ao;
    uint param_7 = 1u;
    gbuffer_write(param, param_1, param_2, param_3, param_4, param_5, param_6, param_7, gbuffer_out_position, _79, gbuffer_out_normal, gbuffer_out_albedo, gbuffer_out_material, gbuffer_out_emissive, gbuffer_out_id);
}

fragment fs_out fs(fs_in in [[stage_in]], constant ModelMaterialData& _295 [[buffer(2)]], constant CameraUniforms& _79 [[buffer(3)]], texture2d<float> map_albedo [[texture(0)]], texture2d<float> map_normal [[texture(1)]], texture2d<float> map_roughness [[texture(2)]], texture2d<float> map_metallic [[texture(3)]], texture2d<float> map_ao [[texture(4)]], texture2d<float> map_alpha [[texture(5)]], texture2d<float> map_height [[texture(6)]], texture2d<float> map_emissive [[texture(7)]], sampler map_albedoSmplr [[sampler(0)]], sampler map_normalSmplr [[sampler(1)]], sampler map_roughnessSmplr [[sampler(2)]], sampler map_metallicSmplr [[sampler(3)]], sampler map_aoSmplr [[sampler(4)]], sampler map_alphaSmplr [[sampler(5)]], sampler map_heightSmplr [[sampler(6)]], sampler map_emissiveSmplr [[sampler(7)]], bool gl_FrontFacing [[front_facing]])
{
    fs_out out = {};
    float2 uv = in.v_uv * _295.u_uv_scale.xy;
    int flags = int(_295.u_factors.z + 0.5);
    float3 n = fast::normalize(in.v_normal);
    if (!gl_FrontFacing)
    {
        n = -n;
    }
    float3 t = fast::normalize(in.v_tangent.xyz);
    t = fast::normalize(t - (n * dot(n, t)));
    float3 b = cross(n, t) * in.v_tangent.w;
    float3 to_eye = _79.u_camera_position.xyz - in.v_position;
    float param = length(to_eye);
    float param_1 = _295.u_uv_scale.w;
    float depth = _295.u_factors.w * parallax_fade(param, param_1);
    if (depth > 9.9999997473787516355514526367188e-06)
    {
        float2 dx = dfdx(uv);
        float2 dy = dfdy(uv);
        float3 param_2 = t;
        float3 param_3 = b;
        float3 param_4 = n;
        float3 param_5 = fast::normalize(to_eye);
        float2 param_6 = uv;
        float3 param_7 = parallax_view(param_2, param_3, param_4, param_5);
        float param_8 = depth;
        float param_9 = _295.u_uv_scale.z;
        float2 param_10 = dx;
        float2 param_11 = dy;
        uv = parallax_offset(param_6, param_7, param_8, param_9, param_10, param_11, map_height, map_heightSmplr);
    }
    float3 albedo = _295.u_base_color.xyz;
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        float4 sampled = map_albedo.sample(map_albedoSmplr, uv);
        albedo = sampled.xyz;
        alpha = sampled.w;
    }
    if ((flags & 32) != 0)
    {
        alpha = map_alpha.sample(map_alphaSmplr, uv).x;
    }
    bool _428 = _295.u_base_color.w > 0.0;
    bool _435;
    if (_428)
    {
        _435 = alpha < _295.u_base_color.w;
    }
    else
    {
        _435 = _428;
    }
    if (_435)
    {
        discard_fragment();
    }
    albedo *= in.v_tint.xyz;
    if ((flags & 2) != 0)
    {
        float3 tn = (map_normal.sample(map_normalSmplr, uv).xyz * 2.0) - float3(1.0);
        n = fast::normalize(float3x3(float3(t), float3(b), float3(n)) * tn);
    }
    float roughness = _295.u_factors.x;
    if ((flags & 4) != 0)
    {
        roughness = map_roughness.sample(map_roughnessSmplr, uv).x;
    }
    float metallic = _295.u_factors.y;
    if ((flags & 8) != 0)
    {
        metallic = map_metallic.sample(map_metallicSmplr, uv).x;
    }
    float ao = 1.0;
    if ((flags & 16) != 0)
    {
        ao = map_ao.sample(map_aoSmplr, uv).x;
    }
    float3 emissive = float3(0.0);
    if (dot(_295.u_emissive.xyz, float3(1.0)) > 0.0)
    {
        emissive = _295.u_emissive.xyz * map_emissive.sample(map_emissiveSmplr, uv).xyz;
    }
    float3 param_12 = in.v_position;
    float3 param_13 = n;
    float3 param_14 = albedo;
    float param_15 = metallic;
    float param_16 = roughness;
    float3 param_17 = emissive;
    float param_18 = ao;
    gbuffer_write(param_12, param_13, param_14, param_15, param_16, param_17, param_18, out.gbuffer_out_position, _79, out.gbuffer_out_normal, out.gbuffer_out_albedo, out.gbuffer_out_material, out.gbuffer_out_emissive, out.gbuffer_out_id);
    return out;
}

