// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct ModelMaterialData
{
    float4 u_base_color;
    float4 u_factors;
    float4 u_uv_scale;
};

struct fs_out
{
    float4 o_mask [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
    float v_style [[user(locn1), flat]];
};

static inline __attribute__((always_inline))
float eye_distance(thread const float& depth, constant CameraUniforms& _18)
{
    float4 view = _18.u_inverse_projection * float4(0.0, 0.0, depth, 1.0);
    return (-view.z) / view.w;
}

fragment fs_out fs(fs_in in [[stage_in]], constant ModelMaterialData& _48 [[buffer(2)]], constant CameraUniforms& _18 [[buffer(3)]], texture2d<float> map_albedo [[texture(0)]], texture2d<float> map_alpha [[texture(5)]], texture2d<float> u_scene_depth [[texture(8)]], sampler map_albedoSmplr [[sampler(0)]], sampler map_alphaSmplr [[sampler(5)]], sampler u_scene_depthSmplr [[sampler(8)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float2 uv = in.v_uv * _48.u_uv_scale.xy;
    int flags = int(_48.u_factors.z + 0.5);
    float alpha = 1.0;
    if ((flags & 1) != 0)
    {
        alpha = map_albedo.sample(map_albedoSmplr, uv).w;
    }
    if ((flags & 32) != 0)
    {
        alpha = map_alpha.sample(map_alphaSmplr, uv).x;
    }
    bool _94 = _48.u_base_color.w > 0.0;
    bool _101;
    if (_94)
    {
        _101 = alpha < _48.u_base_color.w;
    }
    else
    {
        _101 = _94;
    }
    if (_101)
    {
        discard_fragment();
    }
    float scene = u_scene_depth.read(uint2(int2(gl_FragCoord.xy)), 0).x;
    float param = gl_FragCoord.z;
    float mine = eye_distance(param, _18);
    float param_1 = scene;
    float front = eye_distance(param_1, _18);
    float visible = float(mine <= ((front + 0.0500000007450580596923828125) + (front * 0.00999999977648258209228515625)));
    out.o_mask = float4(1.0, visible, (in.v_style + 0.5) / 4.0, 1.0);
    return out;
}

