// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SkyScatter
{
    float3 sun_r;
    float3 sun_m;
    float3 moon_r;
    float3 moon_m;
    float3 transmittance;
    float t_ground;
};

struct SkyUniforms
{
    float4 u_sky_sun;
    float4 u_sky_origin;
    float4 u_sky_rayleigh;
    float4 u_sky_mie;
    float4 u_sky_ground;
    float4 u_sky_params;
    float4 u_sky_moon;
    float4 u_sky_moon_params;
    float4 u_sky_moon_color;
};

struct FogUniforms
{
    float4 u_fog_density;
    float4 u_fog_color;
    float4 u_fog_params;
    float4 u_fog_sun;
    float4 u_fog_samples;
    float4 u_fog_moon;
    float4 u_fog_shafts;
    float4 u_fog_shaft_light;
    float4 u_fog_shaft_phase;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct fs_out
{
    float4 frag_color [[color(0)]];
};

struct fs_in
{
    float3 v_direction [[user(locn0)]];
};

static inline __attribute__((always_inline))
float3 sky_observer(constant SkyUniforms& _216)
{
    return float3(0.0, _216.u_sky_params.z + fast::max(_216.u_sky_origin.y, 1.0), 0.0);
}

static inline __attribute__((always_inline))
float2 sky_ray_sphere(thread const float3& o, thread const float3& d, thread const float& r)
{
    float b = dot(o, d);
    float c = dot(o, o) - (r * r);
    float disc = (b * b) - c;
    if (disc < 0.0)
    {
        return float2(-1.0);
    }
    float s = sqrt(disc);
    return float2((-b) - s, (-b) + s);
}

static inline __attribute__((always_inline))
float2 sky_view_horizon(constant SkyUniforms& _216)
{
    float h = fast::max(_216.u_sky_origin.y, 1.0);
    float r = _216.u_sky_params.z + h;
    float cos_beta = sqrt(h * ((2.0 * _216.u_sky_params.z) + h)) / r;
    float beta = acos(fast::clamp(cos_beta, 0.0, 1.0));
    return float2(3.1415927410125732421875 - beta, beta);
}

static inline __attribute__((always_inline))
float2 sky_view_uv(thread const float3& dir, thread const bool& ground, constant SkyUniforms& _216)
{
    float2 horizon = sky_view_horizon(_216);
    float zenith = acos(fast::clamp(dir.y, -1.0, 1.0));
    float half_texel = 0.00390625;
    float v;
    if (!ground)
    {
        float c = sqrt(fast::max(1.0 - (zenith / horizon.x), 0.0));
        v = fast::clamp(0.5 * (1.0 - c), half_texel, 0.5 - half_texel);
    }
    else
    {
        float c_1 = sqrt(fast::max((zenith - horizon.x) / horizon.y, 0.0));
        v = fast::clamp(0.5 + (0.5 * c_1), 0.5 + half_texel, 1.0 - half_texel);
    }
    float u = (precise::atan2(dir.z, dir.x) / 6.283185482025146484375) + 0.5;
    return float2(u, v);
}

static inline __attribute__((always_inline))
float sky_phase_rayleigh(thread const float& mu)
{
    return 0.0596831031143665313720703125 * (1.0 + (mu * mu));
}

static inline __attribute__((always_inline))
float sky_phase_mie(thread const float& mu, constant SkyUniforms& _216)
{
    float g = _216.u_sky_mie.z;
    float gg = g * g;
    return (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / ((2.0 + gg) * powr((1.0 + gg) - ((2.0 * g) * mu), 1.5));
}

static inline __attribute__((always_inline))
float3 sky_scatter_color(thread const float3& dir, thread const float3& sun_r, thread const float3& sun_m, thread const float3& moon_r, thread const float3& moon_m, constant SkyUniforms& _216)
{
    float mu = dot(dir, _216.u_sky_sun.xyz);
    float param = mu;
    float param_1 = mu;
    float3 color = ((sun_r * sky_phase_rayleigh(param)) + (sun_m * sky_phase_mie(param_1, _216))) * (_216.u_sky_sun.w * 4.0);
    if (_216.u_sky_moon.w > 0.0)
    {
        float mu_m = dot(dir, _216.u_sky_moon.xyz);
        float param_2 = mu_m;
        float param_3 = mu_m;
        color += ((_216.u_sky_moon_color.xyz * (_216.u_sky_moon.w * 4.0)) * ((moon_r * sky_phase_rayleigh(param_2)) + (moon_m * sky_phase_mie(param_3, _216))));
    }
    return color;
}

static inline __attribute__((always_inline))
float3 sky_sun_disk(thread const float3& dir, thread const float3& transmittance, constant SkyUniforms& _216)
{
    float3 to_sun = _216.u_sky_sun.xyz;
    if (dot(dir, to_sun) <= 0.0)
    {
        return float3(0.0);
    }
    float angle = length(cross(dir, to_sun));
    float disk = 1.0 - smoothstep(0.0037819999270141124725341796875, 0.004652000032365322113037109375, angle);
    if (disk <= 0.0)
    {
        return float3(0.0);
    }
    float x = fast::min(angle / 0.004652000032365322113037109375, 1.0);
    float limb = 1.0 - (0.60000002384185791015625 * (1.0 - sqrt(fast::max(1.0 - (x * x), 0.0))));
    return transmittance * (((_216.u_sky_sun.w * 500.0) * disk) * limb);
}

static inline __attribute__((always_inline))
float3 sky_moon_halo(thread const float3& dir, thread const float3& transmittance, constant SkyUniforms& _216)
{
    float c = fast::clamp(dot(dir, _216.u_sky_moon.xyz), -1.0, 1.0);
    bool _1026 = c <= 0.0;
    bool _1033;
    if (!_1026)
    {
        _1033 = _216.u_sky_moon.w <= 0.0;
    }
    else
    {
        _1033 = _1026;
    }
    if (_1033)
    {
        return float3(0.0);
    }
    float angle = sqrt(fast::max(2.0 * (1.0 - c), 0.0));
    return (transmittance * _216.u_sky_moon_color.xyz) * ((_216.u_sky_moon.w * 0.3499999940395355224609375) * exp((-angle) / 0.04500000178813934326171875));
}

static inline __attribute__((always_inline))
float sky_hash(thread float3& p)
{
    p = fract(p * float3(0.103100001811981201171875, 0.10300000011920928955078125, 0.097300000488758087158203125));
    p += float3(dot(p, p.yxz + float3(33.3300018310546875)));
    return fract((p.x + p.y) * p.z);
}

static inline __attribute__((always_inline))
float sky_value_noise(thread const float2& x)
{
    float2 i = floor(x);
    float2 f = fract(x);
    f = (f * f) * (float2(3.0) - (f * 2.0));
    float3 param = float3(i, 0.0);
    float _807 = sky_hash(param);
    float a = _807;
    float3 param_1 = float3(i + float2(1.0, 0.0), 0.0);
    float _816 = sky_hash(param_1);
    float b = _816;
    float3 param_2 = float3(i + float2(0.0, 1.0), 0.0);
    float _825 = sky_hash(param_2);
    float c = _825;
    float3 param_3 = float3(i + float2(1.0), 0.0);
    float _834 = sky_hash(param_3);
    float d = _834;
    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);
}

static inline __attribute__((always_inline))
float3 sky_moon_disk(thread const float3& dir, thread const float3& transmittance, constant SkyUniforms& _216)
{
    float3 m = _216.u_sky_moon.xyz;
    float c = dot(dir, m);
    float cr = _216.u_sky_moon_params.z;
    if (c <= cr)
    {
        return float3(0.0);
    }
    float3 side = cross(m, float3(0.0, 1.0, 0.0));
    if (dot(side, side) < 9.9999999747524270787835121154785e-07)
    {
        side = float3(1.0, 0.0, 0.0);
    }
    float3 right = fast::normalize(side);
    float3 up = cross(right, m);
    float radius = sqrt(fast::max(1.0 - (cr * cr), 9.9999999392252902907785028219223e-09));
    float2 q = float2(dot(dir, right), dot(dir, up)) / float2(radius);
    float rr = dot(q, q);
    if (rr >= 1.0)
    {
        return float3(0.0);
    }
    float edge = 1.0 - smoothstep(0.939999997615814208984375, 1.0, sqrt(rr));
    float3 n = ((right * q.x) + (up * q.y)) - (m * sqrt(1.0 - rr));
    float lit = fast::max(dot(n, _216.u_sky_sun.xyz), 0.0);
    float2 param = (q * 2.2000000476837158203125) + float2(3.099999904632568359375);
    float2 param_1 = (q * 6.0) + float2(11.69999980926513671875);
    float2 param_2 = (q * 15.0) + float2(5.30000019073486328125);
    float maria = ((sky_value_noise(param) * 0.60000002384185791015625) + (sky_value_noise(param_1) * 0.300000011920928955078125)) + (sky_value_noise(param_2) * 0.100000001490116119384765625);
    float albedo = mix(0.449999988079071044921875, 1.0, smoothstep(0.37999999523162841796875, 0.62000000476837158203125, maria));
    float limb = 0.75 + (0.25 * sqrt(1.0 - rr));
    float3 tint = mix(float3(1.0), _216.u_sky_moon_color.xyz, float3(0.3499999940395355224609375));
    float light = (lit * limb) + _216.u_sky_moon_params.y;
    return (transmittance * tint) * (((2.2000000476837158203125 * albedo) * light) * edge);
}

static inline __attribute__((always_inline))
float3 sky_hash3(thread const float3& p)
{
    float3 param = p;
    float _770 = sky_hash(param);
    float3 param_1 = p + float3(17.1299991607666015625);
    float _776 = sky_hash(param_1);
    float3 param_2 = p + float3(41.70999908447265625);
    float _782 = sky_hash(param_2);
    return float3(_770, _776, _782);
}

static inline __attribute__((always_inline))
float3 sky_stars(thread const float3& dir, thread const float3& transmittance, thread const float3& sky, constant SkyUniforms& _216)
{
    float fade = (1.0 - smoothstep(-0.14000000059604644775390625, 0.0350000001490116119384765625, _216.u_sky_sun.y)) * _216.u_sky_moon_params.w;
    bool _1071 = fade <= 0.0;
    bool _1078;
    if (!_1071)
    {
        _1078 = dir.y <= 0.0;
    }
    else
    {
        _1078 = _1071;
    }
    if (_1078)
    {
        return float3(0.0);
    }
    float3 p = dir * 180.0;
    float3 cell = floor(p);
    float3 param = cell;
    float _1092 = sky_hash(param);
    float h = _1092;
    if (h > 0.04500000178813934326171875)
    {
        return float3(0.0);
    }
    float3 param_1 = cell + float3(5.0);
    float3 at = (cell + float3(0.20000000298023223876953125)) + (sky_hash3(param_1) * 0.60000002384185791015625);
    float d = length(p - at);
    float core = exp(((-d) * d) * 60.0);
    float mag = (powr(h / 0.04500000178813934326171875, 6.0) * 3.5) + 0.119999997317790985107421875;
    float3 param_2 = cell + float3(9.0);
    float _1138 = sky_hash(param_2);
    float warm = _1138;
    float3 color = mix(float3(0.75, 0.85000002384185791015625, 1.0), float3(1.0, 0.85000002384185791015625, 0.64999997615814208984375), float3(warm));
    float lum = dot(sky, float3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875));
    float drown = exp((-lum) * 60.0);
    return (transmittance * color) * (((core * mag) * fade) * drown);
}

static inline __attribute__((always_inline))
float3 sky_lights(thread const float3& dir, thread const float3& transmittance, thread float3& color, constant SkyUniforms& _216)
{
    if (_216.u_sky_origin.w > 0.5)
    {
        float3 param = dir;
        float3 param_1 = transmittance;
        color += sky_sun_disk(param, param_1, _216);
    }
    if (_216.u_sky_moon_color.w > 0.5)
    {
        float3 sky = color;
        float3 param_2 = dir;
        float3 param_3 = transmittance;
        color += sky_moon_halo(param_2, param_3, _216);
        float3 param_4 = dir;
        float3 param_5 = transmittance;
        color += sky_moon_disk(param_4, param_5, _216);
        float3 param_6 = dir;
        float3 param_7 = transmittance;
        float3 param_8 = sky;
        color += sky_stars(param_6, param_7, param_8, _216);
    }
    return color;
}

static inline __attribute__((always_inline))
float3 sky_radiance_lut(thread const float3& dir, texture2d_array<float> lut, sampler lutSmplr, constant SkyUniforms& _216)
{
    float3 param = sky_observer(_216);
    float3 param_1 = dir;
    float param_2 = _216.u_sky_params.z;
    bool ground = sky_ray_sphere(param, param_1, param_2).x > 0.0;
    float3 param_3 = dir;
    bool param_4 = ground;
    float2 uv = sky_view_uv(param_3, param_4, _216);
    float3 _2059 = float3(uv, 0.0);
    float4 sun_r = lut.sample(lutSmplr, _2059.xy, uint(rint(_2059.z)), level(0.0));
    float3 _2066 = float3(uv, 1.0);
    float4 sun_m = lut.sample(lutSmplr, _2066.xy, uint(rint(_2066.z)), level(0.0));
    float3 _2073 = float3(uv, 2.0);
    float4 moon_r = lut.sample(lutSmplr, _2073.xy, uint(rint(_2073.z)), level(0.0));
    float4 moon_m = float4(0.0);
    if (_216.u_sky_moon.w > 0.0)
    {
        float3 _2086 = float3(uv, 3.0);
        moon_m = lut.sample(lutSmplr, _2086.xy, uint(rint(_2086.z)), level(0.0));
    }
    float3 transmittance = float3(sun_r.w, sun_m.w, moon_r.w);
    float3 param_5 = dir;
    float3 param_6 = sun_r.xyz;
    float3 param_7 = sun_m.xyz;
    float3 param_8 = moon_r.xyz;
    float3 param_9 = moon_m.xyz;
    float3 color = sky_scatter_color(param_5, param_6, param_7, param_8, param_9, _216);
    if (!ground)
    {
        float3 param_10 = dir;
        float3 param_11 = transmittance;
        float3 param_12 = color;
        float3 _2122 = sky_lights(param_10, param_11, param_12, _216);
        return _2122 * _216.u_sky_ground.w;
    }
    float3 _2132 = float3(uv, 4.0);
    float3 lit_ground = lut.sample(lutSmplr, _2132.xy, uint(rint(_2132.z)), level(0.0)).xyz;
    return (color + lit_ground) * _216.u_sky_ground.w;
}

static inline __attribute__((always_inline))
float fog_integral(thread const float& dy, thread const float& len, constant FogUniforms& _1220)
{
    float k = _1220.u_fog_density.y;
    float d0 = _1220.u_fog_density.x;
    float x = fast::max((k * dy) * len, -60.0);
    if (abs(x) < 9.9999997473787516355514526367188e-05)
    {
        return (d0 * len) * (1.0 - (0.5 * x));
    }
    return (d0 * (1.0 - exp(-x))) / (k * dy);
}

static inline __attribute__((always_inline))
float3 fog_horizon_dir(thread const float3& dir, constant SkyUniforms& _216)
{
    float2 xz = dir.xz;
    float horiz = length(xz);
    if (horiz < 9.9999997473787516355514526367188e-05)
    {
        xz = _216.u_sky_sun.xz;
        horiz = length(xz);
        if (horiz < 9.9999997473787516355514526367188e-05)
        {
            xz = float2(1.0, 0.0);
            horiz = 1.0;
        }
    }
    xz /= float2(horiz);
    return fast::normalize(float3(xz.x, fast::max(dir.y, 0.0199999995529651641845703125), xz.y));
}

static inline __attribute__((always_inline))
float2 sky_optical_depth(thread const float3& p, thread const float3& d, thread const float& len, thread const int& samples, constant SkyUniforms& _216)
{
    float step_len = len / float(samples);
    float2 depth = float2(0.0);
    float2 scale = float2(_216.u_sky_rayleigh.w, _216.u_sky_mie.w);
    for (int i = 0; i < samples; i++)
    {
        float3 s = p + (d * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(s) - _216.u_sky_params.z, 0.0);
        depth += (exp(float2(-h) / scale) * step_len);
    }
    return depth;
}

static inline __attribute__((always_inline))
float3 sky_extinction(thread const float2& depth, constant SkyUniforms& _216)
{
    return exp(-((_216.u_sky_rayleigh.xyz * depth.x) + (float3(_216.u_sky_mie.y) * depth.y)));
}

static inline __attribute__((always_inline))
SkyScatter sky_scatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, constant SkyUniforms& _216)
{
    float3 o = sky_observer(_216);
    float rg = _216.u_sky_params.z;
    float rt = _216.u_sky_params.w;
    float3 param = o;
    float3 param_1 = dir;
    float param_2 = rt;
    float2 atmo = sky_ray_sphere(param, param_1, param_2);
    float t_max = fast::max(atmo.y, 0.0);
    float3 param_3 = o;
    float3 param_4 = dir;
    float param_5 = rg;
    float2 ground = sky_ray_sphere(param_3, param_4, param_5);
    SkyScatter s;
    s.t_ground = -1.0;
    if (ground.x > 0.0)
    {
        s.t_ground = ground.x;
        t_max = ground.x;
    }
    float step_len = t_max / float(view_samples);
    float3 to_sun = _216.u_sky_sun.xyz;
    float2 scale = float2(_216.u_sky_rayleigh.w, _216.u_sky_mie.w);
    float3 sum_r = float3(0.0);
    float3 sum_m = float3(0.0);
    float2 depth_view = float2(0.0);
    bool moon_on = _216.u_sky_moon.w > 0.0;
    float3 to_moon = _216.u_sky_moon.xyz;
    float3 moon_r = float3(0.0);
    float3 moon_m = float3(0.0);
    for (int i = 0; i < view_samples; i++)
    {
        float3 p = o + (dir * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(p) - rg, 0.0);
        float2 dens = exp(float2(-h) / scale) * step_len;
        depth_view += dens;
        bool _431;
        if (moon_on)
        {
            float3 param_6 = p;
            float3 param_7 = to_moon;
            float param_8 = rg;
            _431 = sky_ray_sphere(param_6, param_7, param_8).x <= 0.0;
        }
        else
        {
            _431 = moon_on;
        }
        if (_431)
        {
            float3 param_9 = p;
            float3 param_10 = to_moon;
            float param_11 = rt;
            float2 moon_atmo = sky_ray_sphere(param_9, param_10, param_11);
            float3 param_12 = p;
            float3 param_13 = to_moon;
            float param_14 = fast::max(moon_atmo.y, 0.0);
            int param_15 = light_samples;
            float2 moon_depth = sky_optical_depth(param_12, param_13, param_14, param_15, _216);
            float2 param_16 = depth_view + moon_depth;
            float3 tm = sky_extinction(param_16, _216);
            moon_r += (tm * dens.x);
            moon_m += (tm * dens.y);
        }
        float3 param_17 = p;
        float3 param_18 = to_sun;
        float param_19 = rg;
        float2 sun_ground = sky_ray_sphere(param_17, param_18, param_19);
        if (sun_ground.x > 0.0)
        {
            continue;
        }
        float3 param_20 = p;
        float3 param_21 = to_sun;
        float param_22 = rt;
        float2 sun_atmo = sky_ray_sphere(param_20, param_21, param_22);
        float3 param_23 = p;
        float3 param_24 = to_sun;
        float param_25 = fast::max(sun_atmo.y, 0.0);
        int param_26 = light_samples;
        float2 depth_light = sky_optical_depth(param_23, param_24, param_25, param_26, _216);
        float2 param_27 = depth_view + depth_light;
        float3 t = sky_extinction(param_27, _216);
        sum_r += (t * dens.x);
        sum_m += (t * dens.y);
    }
    float2 param_28 = depth_view;
    s.transmittance = sky_extinction(param_28, _216);
    s.sun_r = sum_r * _216.u_sky_rayleigh.xyz;
    s.sun_m = sum_m * float3(_216.u_sky_mie.x);
    s.moon_r = moon_r * _216.u_sky_rayleigh.xyz;
    s.moon_m = moon_m * float3(_216.u_sky_mie.x);
    return s;
}

static inline __attribute__((always_inline))
float3 sky_inscatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _216)
{
    float3 param = dir;
    int param_1 = view_samples;
    int param_2 = light_samples;
    SkyScatter s = sky_scatter_n(param, param_1, param_2, _216);
    transmittance = s.transmittance;
    t_ground = s.t_ground;
    float3 param_3 = dir;
    float3 param_4 = s.sun_r;
    float3 param_5 = s.sun_m;
    float3 param_6 = s.moon_r;
    float3 param_7 = s.moon_m;
    return sky_scatter_color(param_3, param_4, param_5, param_6, param_7, _216);
}

static inline __attribute__((always_inline))
float3 fog_color(thread const float3& dir, constant SkyUniforms& _216, constant FogUniforms& _1220)
{
    float3 tint = _1220.u_fog_color.xyz;
    if (_1220.u_fog_color.w < 0.5)
    {
        return tint;
    }
    float3 param = dir;
    float3 param_1 = fog_horizon_dir(param, _216);
    int param_2 = int(_1220.u_fog_samples.x);
    int param_3 = int(_1220.u_fog_samples.y);
    float3 param_4;
    float param_5;
    float3 _1323 = sky_inscatter_n(param_1, param_2, param_3, param_4, param_5, _216);
    float3 transmittance = param_4;
    float t_ground = param_5;
    float3 radiance = _1323;
    return (tint * _216.u_sky_ground.w) * radiance;
}

static inline __attribute__((always_inline))
float3 fog_apply(thread const float3& color, thread const float3& relative, constant SkyUniforms& _216, constant FogUniforms& _1220)
{
    if (_1220.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _1220.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _1220.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _1220);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _1220))), 1.0 - _1220.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _1220.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _1220)));
    float sun = powr(fast::max(dot(dir, _216.u_sky_sun.xyz), 0.0), _1220.u_fog_sun.w);
    float moon = powr(fast::max(dot(dir, _216.u_sky_moon.xyz), 0.0), fast::max(_1220.u_fog_moon.w, 1.0));
    float3 glow = (_1220.u_fog_sun.xyz * sun) + (_1220.u_fog_moon.xyz * moon);
    float3 param_6 = dir;
    float3 fog = (fog_color(param_6, _216, _1220) * (1.0 - t)) + (glow * (1.0 - td));
    return (color * t) + fog;
}

static inline __attribute__((always_inline))
float3 fog_apply_sky(thread const float3& color, thread const float3& dir, constant SkyUniforms& _216, constant FogUniforms& _1220)
{
    float3 d = fast::normalize(dir);
    float3 param = color;
    float3 param_1 = d * _1220.u_fog_params.z;
    return fog_apply(param, param_1, _216, _1220);
}

static inline __attribute__((always_inline))
float2 godrays_fetch(thread const float2& uv, thread const float& dist, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    float2 size = float2(int2(godrays_resolved.get_width(), godrays_resolved.get_height()));
    float2 st = (uv * size) - float2(0.5);
    float2 cell = floor(st);
    float2 f = st - cell;
    int2 base = int2(cell);
    int2 top = int2(size) - int2(1);
    float d = fast::min(dist, 60000.0);
    float2 sum = float2(0.0);
    float weight = 0.0;
    float _1547;
    float _1560;
    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 2; i++)
        {
            float4 s = godrays_resolved.read(uint2(clamp(base + int2(i, j), int2(0), top)), 0);
            if (i == 0)
            {
                _1547 = 1.0 - f.x;
            }
            else
            {
                _1547 = f.x;
            }
            float bx = _1547;
            if (j == 0)
            {
                _1560 = 1.0 - f.y;
            }
            else
            {
                _1560 = f.y;
            }
            float by = _1560;
            float rel = abs(s.z - d) / fast::max(d, 1.0);
            float w = ((bx * by) / (0.001000000047497451305389404296875 + rel)) + 9.9999999747524270787835121154785e-07;
            sum += (s.xy * w);
            weight += w;
        }
    }
    return sum / float2(weight);
}

static inline __attribute__((always_inline))
float godrays_phase(thread const float& cosTheta, thread const float& g)
{
    float g2 = g * g;
    float denom = fast::max((1.0 + g2) - ((2.0 * g) * cosTheta), 9.9999997473787516355514526367188e-05);
    return (1.0 - g2) / ((12.56637096405029296875 * denom) * sqrt(denom));
}

static inline __attribute__((always_inline))
float godrays_phase2(thread const float& cosTheta, thread const float3& lobes)
{
    float param = cosTheta;
    float param_1 = lobes.x;
    float param_2 = cosTheta;
    float param_3 = lobes.y;
    return godrays_phase(param, param_1) + (godrays_phase(param_2, param_3) * lobes.z);
}

static inline __attribute__((always_inline))
float3 fog_apply_rays_at(thread const float3& color, thread const float3& relative, thread const float2& uv, thread const float& fetchDist, constant SkyUniforms& _216, constant FogUniforms& _1220, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    if (_1220.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _1220.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _1220.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _1220);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _1220))), 1.0 - _1220.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _1220.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _1220)));
    float2 param_6 = uv;
    float param_7 = fetchDist;
    float2 shaft = godrays_fetch(param_6, param_7, godrays_resolved, godrays_resolvedSmplr);
    float occlude = mix(1.0, shaft.y, _1220.u_fog_shafts.y);
    float sun = powr(fast::max(dot(dir, _216.u_sky_sun.xyz), 0.0), _1220.u_fog_sun.w);
    float moon = powr(fast::max(dot(dir, _216.u_sky_moon.xyz), 0.0), fast::max(_1220.u_fog_moon.w, 1.0));
    float3 glow = ((_1220.u_fog_sun.xyz * sun) + (_1220.u_fog_moon.xyz * moon)) * occlude;
    float3 param_8 = dir;
    float3 fog = (fog_color(param_8, _216, _1220) * (1.0 - t)) + (glow * (1.0 - td));
    float3 _1788;
    if (_1220.u_fog_shaft_light.w > 0.5)
    {
        _1788 = _216.u_sky_moon.xyz;
    }
    else
    {
        _1788 = _216.u_sky_sun.xyz;
    }
    float3 toLight = _1788;
    float param_9 = dot(dir, toLight);
    float3 param_10 = _1220.u_fog_shaft_phase.xyz;
    float phase = godrays_phase2(param_9, param_10);
    float3 rays = _1220.u_fog_shaft_light.xyz * ((phase * shaft.x) * _1220.u_fog_shafts.x);
    return ((color * t) + fog) + rays;
}

static inline __attribute__((always_inline))
float3 fog_apply_sky_rays(thread const float3& color, thread const float3& dir, thread const float2& uv, constant SkyUniforms& _216, constant FogUniforms& _1220, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    if (_1220.u_fog_shafts.w < 0.5)
    {
        float3 param = color;
        float3 param_1 = dir;
        return fog_apply_sky(param, param_1, _216, _1220);
    }
    float3 d = fast::normalize(dir);
    float3 param_2 = color;
    float3 param_3 = d * _1220.u_fog_params.z;
    float2 param_4 = uv;
    float param_5 = 60000.0;
    return fog_apply_rays_at(param_2, param_3, param_4, param_5, _216, _1220, godrays_resolved, godrays_resolvedSmplr);
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _1870;
    if (x < 0.07999999821186065673828125)
    {
        _1870 = x - ((6.25 * x) * x);
    }
    else
    {
        _1870 = 0.039999999105930328369140625;
    }
    float offset = _1870;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _1935 = tonemap_neutral(param);
    return _1935;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return powr(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(fs_in in [[stage_in]], constant CameraUniforms& _2163 [[buffer(3)]], constant SkyUniforms& _216 [[buffer(4)]], constant FogUniforms& _1220 [[buffer(5)]], texture2d_array<float> u_sky_view [[texture(1)]], texture2d<float> godrays_resolved [[texture(15)]], sampler u_sky_viewSmplr [[sampler(1)]], sampler godrays_resolvedSmplr [[sampler(15)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float3 dir = fast::normalize(in.v_direction);
    float3 param = dir;
    float3 color = fast::min(sky_radiance_lut(param, u_sky_view, u_sky_viewSmplr, _216), float3(65504.0));
    float3 param_1 = color;
    float3 param_2 = dir;
    float2 param_3 = gl_FragCoord.xy * _2163.u_resolution.zw;
    color = fog_apply_sky_rays(param_1, param_2, param_3, _216, _1220, godrays_resolved, godrays_resolvedSmplr);
    float3 param_4 = color;
    color = apply_tonemap(param_4);
    float3 param_5 = color;
    color = gamma_correct(param_5);
    out.frag_color = float4(color, 1.0);
    return out;
}

