// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct SkyUniforms
{
    float4 u_sky_sun;
    float4 u_sky_origin;
    float4 u_sky_rayleigh;
    float4 u_sky_mie;
    float4 u_sky_ground;
    float4 u_sky_params;
};

struct FogUniforms
{
    float4 u_fog_density;
    float4 u_fog_color;
    float4 u_fog_params;
    float4 u_fog_sun;
    float4 u_fog_samples;
};

struct fs_out
{
    float4 frag_color [[color(0)]];
};

struct fs_in
{
    float3 v_direction [[user(locn0)]];
};

static inline __attribute__((always_inline))
float3 sky_observer(constant SkyUniforms& _133)
{
    return float3(0.0, _133.u_sky_params.z + fast::max(_133.u_sky_origin.y, 1.0), 0.0);
}

static inline __attribute__((always_inline))
float2 sky_ray_sphere(thread const float3& o, thread const float3& d, thread const float& r)
{
    float b = dot(o, d);
    float c = dot(o, o) - (r * r);
    float disc = (b * b) - c;
    if (disc < 0.0)
    {
        return float2(-1.0);
    }
    float s = sqrt(disc);
    return float2((-b) - s, (-b) + s);
}

static inline __attribute__((always_inline))
float2 sky_optical_depth(thread const float3& p, thread const float3& d, thread const float& len, thread const int& samples, constant SkyUniforms& _133)
{
    float step_len = len / float(samples);
    float2 depth = float2(0.0);
    float2 scale = float2(_133.u_sky_rayleigh.w, _133.u_sky_mie.w);
    for (int i = 0; i < samples; i++)
    {
        float3 s = p + (d * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(s) - _133.u_sky_params.z, 0.0);
        depth += (exp(float2(-h) / scale) * step_len);
    }
    return depth;
}

static inline __attribute__((always_inline))
float3 sky_extinction(thread const float2& depth, constant SkyUniforms& _133)
{
    return exp(-((_133.u_sky_rayleigh.xyz * depth.x) + (float3(_133.u_sky_mie.y) * depth.y)));
}

static inline __attribute__((always_inline))
float3 sky_inscatter_n(thread const float3& dir, thread const int& view_samples, thread const int& light_samples, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _133)
{
    float3 o = sky_observer(_133);
    float rg = _133.u_sky_params.z;
    float rt = _133.u_sky_params.w;
    float3 param = o;
    float3 param_1 = dir;
    float param_2 = rt;
    float2 atmo = sky_ray_sphere(param, param_1, param_2);
    float t_max = fast::max(atmo.y, 0.0);
    float3 param_3 = o;
    float3 param_4 = dir;
    float param_5 = rg;
    float2 ground = sky_ray_sphere(param_3, param_4, param_5);
    t_ground = -1.0;
    if (ground.x > 0.0)
    {
        t_ground = ground.x;
        t_max = ground.x;
    }
    float step_len = t_max / float(view_samples);
    float3 to_sun = _133.u_sky_sun.xyz;
    float mu = dot(dir, to_sun);
    float g = _133.u_sky_mie.z;
    float gg = g * g;
    float phase_r = 0.0596831031143665313720703125 * (1.0 + (mu * mu));
    float phase_m = (0.119366206228733062744140625 * ((1.0 - gg) * (1.0 + (mu * mu)))) / ((2.0 + gg) * pow((1.0 + gg) - ((2.0 * g) * mu), 1.5));
    float2 scale = float2(_133.u_sky_rayleigh.w, _133.u_sky_mie.w);
    float3 sum_r = float3(0.0);
    float3 sum_m = float3(0.0);
    float2 depth_view = float2(0.0);
    for (int i = 0; i < view_samples; i++)
    {
        float3 p = o + (dir * ((float(i) + 0.5) * step_len));
        float h = fast::max(length(p) - rg, 0.0);
        float2 dens = exp(float2(-h) / scale) * step_len;
        depth_view += dens;
        float3 param_6 = p;
        float3 param_7 = to_sun;
        float param_8 = rg;
        float2 sun_ground = sky_ray_sphere(param_6, param_7, param_8);
        if (sun_ground.x > 0.0)
        {
            continue;
        }
        float3 param_9 = p;
        float3 param_10 = to_sun;
        float param_11 = rt;
        float2 sun_atmo = sky_ray_sphere(param_9, param_10, param_11);
        float3 param_12 = p;
        float3 param_13 = to_sun;
        float param_14 = fast::max(sun_atmo.y, 0.0);
        int param_15 = light_samples;
        float2 depth_light = sky_optical_depth(param_12, param_13, param_14, param_15, _133);
        float2 param_16 = depth_view + depth_light;
        float3 t = sky_extinction(param_16, _133);
        sum_r += (t * dens.x);
        sum_m += (t * dens.y);
    }
    float2 param_17 = depth_view;
    transmittance = sky_extinction(param_17, _133);
    return (((sum_r * _133.u_sky_rayleigh.xyz) * phase_r) + ((sum_m * float3(_133.u_sky_mie.x)) * phase_m)) * (_133.u_sky_sun.w * 4.0);
}

static inline __attribute__((always_inline))
float3 sky_inscatter(thread const float3& dir, thread float3& transmittance, thread float& t_ground, constant SkyUniforms& _133)
{
    float3 param = dir;
    int param_1 = int(_133.u_sky_params.x);
    int param_2 = int(_133.u_sky_params.y);
    float3 param_3;
    float param_4;
    float3 _497 = sky_inscatter_n(param, param_1, param_2, param_3, param_4, _133);
    transmittance = param_3;
    t_ground = param_4;
    return _497;
}

static inline __attribute__((always_inline))
float3 sky_sun_disk(thread const float3& dir, thread const float3& transmittance, constant SkyUniforms& _133)
{
    float3 to_sun = _133.u_sky_sun.xyz;
    if (dot(dir, to_sun) <= 0.0)
    {
        return float3(0.0);
    }
    float angle = length(cross(dir, to_sun));
    float disk = 1.0 - smoothstep(0.0037819999270141124725341796875, 0.004652000032365322113037109375, angle);
    if (disk <= 0.0)
    {
        return float3(0.0);
    }
    float x = fast::min(angle / 0.004652000032365322113037109375, 1.0);
    float limb = 1.0 - (0.60000002384185791015625 * (1.0 - sqrt(fast::max(1.0 - (x * x), 0.0))));
    return transmittance * (((_133.u_sky_sun.w * 500.0) * disk) * limb);
}

static inline __attribute__((always_inline))
float3 sky_transmittance_from(thread const float3& p, thread const float3& to_sun, constant SkyUniforms& _133)
{
    float3 param = p;
    float3 param_1 = to_sun;
    float param_2 = _133.u_sky_params.z;
    float2 ground = sky_ray_sphere(param, param_1, param_2);
    if (ground.x > 0.0)
    {
        return float3(0.0);
    }
    float3 param_3 = p;
    float3 param_4 = to_sun;
    float param_5 = _133.u_sky_params.w;
    float2 atmo = sky_ray_sphere(param_3, param_4, param_5);
    float3 param_6 = p;
    float3 param_7 = to_sun;
    float param_8 = fast::max(atmo.y, 0.0);
    int param_9 = int(_133.u_sky_params.y);
    float2 depth = sky_optical_depth(param_6, param_7, param_8, param_9, _133);
    float2 param_10 = depth;
    return sky_extinction(param_10, _133);
}

static inline __attribute__((always_inline))
float3 sky_radiance(thread const float3& dir, constant SkyUniforms& _133)
{
    float3 param = dir;
    float3 param_1;
    float param_2;
    float3 _563 = sky_inscatter(param, param_1, param_2, _133);
    float3 transmittance = param_1;
    float t_ground = param_2;
    float3 color = _563;
    if (t_ground < 0.0)
    {
        if (_133.u_sky_origin.w > 0.5)
        {
            float3 param_3 = dir;
            float3 param_4 = transmittance;
            color += sky_sun_disk(param_3, param_4, _133);
        }
        return color * _133.u_sky_ground.w;
    }
    float3 p = sky_observer(_133) + (dir * t_ground);
    float3 n = fast::normalize(p);
    float3 to_sun = _133.u_sky_sun.xyz;
    float3 param_5 = p;
    float3 param_6 = to_sun;
    float3 sun = sky_transmittance_from(param_5, param_6, _133) * ((_133.u_sky_sun.w * fast::max(dot(n, to_sun), 0.0)) / 3.1415927410125732421875);
    float3 mirrored = reflect(dir, n);
    float3 param_7 = mirrored;
    float3 param_8;
    float param_9;
    float3 _628 = sky_inscatter(param_7, param_8, param_9, _133);
    float3 up_transmittance = param_8;
    float up_ground = param_9;
    float3 ambient = _628 * 0.5;
    float3 ground = _133.u_sky_ground.xyz * (sun + ambient);
    return (color + (transmittance * ground)) * _133.u_sky_ground.w;
}

static inline __attribute__((always_inline))
float fog_integral(thread const float& dy, thread const float& len, constant FogUniforms& _653)
{
    float k = _653.u_fog_density.y;
    float d0 = _653.u_fog_density.x;
    float x = fast::max((k * dy) * len, -60.0);
    if (abs(x) < 9.9999997473787516355514526367188e-05)
    {
        return (d0 * len) * (1.0 - (0.5 * x));
    }
    return (d0 * (1.0 - exp(-x))) / (k * dy);
}

static inline __attribute__((always_inline))
float3 fog_horizon_dir(thread const float3& dir, constant SkyUniforms& _133)
{
    float2 xz = dir.xz;
    float horiz = length(xz);
    if (horiz < 9.9999997473787516355514526367188e-05)
    {
        xz = _133.u_sky_sun.xz;
        horiz = length(xz);
        if (horiz < 9.9999997473787516355514526367188e-05)
        {
            xz = float2(1.0, 0.0);
            horiz = 1.0;
        }
    }
    xz /= float2(horiz);
    return fast::normalize(float3(xz.x, fast::max(dir.y, 0.0199999995529651641845703125), xz.y));
}

static inline __attribute__((always_inline))
float3 fog_color(thread const float3& dir, constant SkyUniforms& _133, constant FogUniforms& _653)
{
    float3 tint = _653.u_fog_color.xyz;
    if (_653.u_fog_color.w < 0.5)
    {
        return tint;
    }
    float3 param = dir;
    float3 param_1 = fog_horizon_dir(param, _133);
    int param_2 = int(_653.u_fog_samples.x);
    int param_3 = int(_653.u_fog_samples.y);
    float3 param_4;
    float param_5;
    float3 _757 = sky_inscatter_n(param_1, param_2, param_3, param_4, param_5, _133);
    float3 transmittance = param_4;
    float t_ground = param_5;
    float3 radiance = _757;
    return (tint * _133.u_sky_ground.w) * radiance;
}

static inline __attribute__((always_inline))
float3 fog_apply(thread const float3& color, thread const float3& relative, constant SkyUniforms& _133, constant FogUniforms& _653)
{
    if (_653.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _653.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _653.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _653);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _653))), 1.0 - _653.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _653.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _653)));
    float sun = pow(fast::max(dot(dir, _133.u_sky_sun.xyz), 0.0), _653.u_fog_sun.w);
    float3 param_6 = dir;
    float3 fog = (fog_color(param_6, _133, _653) * (1.0 - t)) + ((_653.u_fog_sun.xyz * sun) * (1.0 - td));
    return (color * t) + fog;
}

static inline __attribute__((always_inline))
float3 fog_apply_sky(thread const float3& color, thread const float3& dir, constant SkyUniforms& _133, constant FogUniforms& _653)
{
    float3 d = fast::normalize(dir);
    float3 param = color;
    float3 param_1 = d * _653.u_fog_params.z;
    return fog_apply(param, param_1, _133, _653);
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _905;
    if (x < 0.07999999821186065673828125)
    {
        _905 = x - ((6.25 * x) * x);
    }
    else
    {
        _905 = 0.039999999105930328369140625;
    }
    float offset = _905;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _970 = tonemap_neutral(param);
    return _970;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(fs_in in [[stage_in]], constant SkyUniforms& _133 [[buffer(4)]], constant FogUniforms& _653 [[buffer(5)]])
{
    fs_out out = {};
    float3 dir = fast::normalize(in.v_direction);
    float3 param = dir;
    float3 color = fast::min(sky_radiance(param, _133), float3(65504.0));
    float3 param_1 = color;
    float3 param_2 = dir;
    color = fog_apply_sky(param_1, param_2, _133, _653);
    float3 param_3 = color;
    color = apply_tonemap(param_3);
    float3 param_4 = color;
    color = gamma_correct(param_4);
    out.frag_color = float4(color, 1.0);
    return out;
}

