// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float4 frag_color [[color(0)]];
};

struct fs_in
{
    float3 v_direction [[user(locn0)]];
};

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _38;
    if (x < 0.07999999821186065673828125)
    {
        _38 = x - ((6.25 * x) * x);
    }
    else
    {
        _38 = 0.039999999105930328369140625;
    }
    float offset = _38;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _104 = tonemap_neutral(param);
    return _104;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(fs_in in [[stage_in]], texturecube<float> u_skybox [[texture(0)]], sampler u_skyboxSmplr [[sampler(0)]])
{
    fs_out out = {};
    float3 color = u_skybox.sample(u_skyboxSmplr, fast::normalize(in.v_direction)).xyz;
    float3 param = color;
    color = apply_tonemap(param);
    float3 param_1 = color;
    color = gamma_correct(param_1);
    out.frag_color = float4(color, 1.0);
    return out;
}

