// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct FogUniforms
{
    float4 u_fog_density;
    float4 u_fog_params;
    float4 u_fog_shafts;
    float4 u_fog_shaft_light;
    float4 u_fog_shaft_phase;
    float4 u_fog_model;
    float4 u_fog_to_moon;
    float4 u_fog_sun_light;
    float4 u_fog_moon_light;
    float4 u_fog_ambient;
    float4 u_fog_albedo;
    float4 u_fog_aerial;
    float4 u_fog_aerial_extinction;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct fs_out
{
    float4 frag_color [[color(0)]];
};

struct fs_in
{
    float3 v_direction [[user(locn0)]];
};

static inline __attribute__((always_inline))
float fog_integral(thread const float& dy, thread const float& len, constant FogUniforms& _102)
{
    float k = _102.u_fog_density.y;
    float d0 = _102.u_fog_density.x;
    float x = fast::max((k * dy) * len, -60.0);
    if (abs(x) < 9.9999997473787516355514526367188e-05)
    {
        return (d0 * len) * (1.0 - (0.5 * x));
    }
    return (d0 * (1.0 - exp(-x))) / (k * dy);
}

static inline __attribute__((always_inline))
float phase_hg(thread const float& g, thread const float& mu)
{
    float gg = g * g;
    float base = fast::max((1.0 + gg) - ((2.0 * g) * mu), 9.9999997473787516355514526367188e-05);
    return (1.0 - gg) / ((12.56637096405029296875 * base) * sqrt(base));
}

static inline __attribute__((always_inline))
float fog_phase(thread const float& mu, constant FogUniforms& _102)
{
    float param = _102.u_fog_sun_light.w;
    float param_1 = mu;
    float forward = phase_hg(param, param_1);
    return mix(0.079577468335628509521484375, forward, _102.u_fog_to_moon.w);
}

static inline __attribute__((always_inline))
float3 fog_medium(thread const float3& dir, thread const float& lit_sun, thread const float& lit_moon, constant FogUniforms& _102)
{
    float param = dot(dir, _102.u_fog_model.xyz);
    float3 light = _102.u_fog_ambient.xyz + (_102.u_fog_sun_light.xyz * (fog_phase(param, _102) * lit_sun));
    if (_102.u_fog_moon_light.w > 0.5)
    {
        float param_1 = dot(dir, _102.u_fog_to_moon.xyz);
        light += (_102.u_fog_moon_light.xyz * (fog_phase(param_1, _102) * lit_moon));
    }
    return _102.u_fog_albedo.xyz * (light * _102.u_fog_albedo.w);
}

static inline __attribute__((always_inline))
float3 fog_height(thread const float3& color, thread const float3& dir, thread const float& len, thread const float& lit_sun, thread const float& lit_moon, thread const float3& rays, constant FogUniforms& _102)
{
    if (_102.u_fog_density.w < 0.5)
    {
        return color;
    }
    float cutoff = _102.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float dy = dir.y;
    float start = _102.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _102);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _102))), 1.0 - _102.u_fog_density.z);
    float3 param_4 = dir;
    float param_5 = lit_sun;
    float param_6 = lit_moon;
    return ((color * t) + (fog_medium(param_4, param_5, param_6, _102) * (1.0 - t))) + rays;
}

static inline __attribute__((always_inline))
float3 fog_apply_sky(thread const float3& color, thread const float3& dir, constant FogUniforms& _102)
{
    float3 d = fast::normalize(dir);
    float3 param = color;
    float3 param_1 = d;
    float param_2 = _102.u_fog_params.z;
    float param_3 = 1.0;
    float param_4 = 1.0;
    float3 param_5 = float3(0.0);
    return fog_height(param, param_1, param_2, param_3, param_4, param_5, _102);
}

static inline __attribute__((always_inline))
float2 godrays_fetch(thread const float2& uv, thread const float& dist, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    float2 size = float2(int2(godrays_resolved.get_width(), godrays_resolved.get_height()));
    float2 st = (uv * size) - float2(0.5);
    float2 cell = floor(st);
    float2 f = st - cell;
    int2 base = int2(cell);
    int2 top = int2(size) - int2(1);
    float d = fast::min(dist, 60000.0);
    float2 sum = float2(0.0);
    float weight = 0.0;
    float _378;
    float _391;
    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 2; i++)
        {
            float4 s = godrays_resolved.read(uint2(clamp(base + int2(i, j), int2(0), top)), 0);
            if (i == 0)
            {
                _378 = 1.0 - f.x;
            }
            else
            {
                _378 = f.x;
            }
            float bx = _378;
            if (j == 0)
            {
                _391 = 1.0 - f.y;
            }
            else
            {
                _391 = f.y;
            }
            float by = _391;
            float rel = abs(s.z - d) / fast::max(d, 1.0);
            float w = ((bx * by) / (0.001000000047497451305389404296875 + rel)) + 9.9999999747524270787835121154785e-07;
            sum += (s.xy * w);
            weight += w;
        }
    }
    return sum / float2(weight);
}

static inline __attribute__((always_inline))
float godrays_phase(thread const float& cosTheta, thread const float& g)
{
    float g2 = g * g;
    float denom = fast::max((1.0 + g2) - ((2.0 * g) * cosTheta), 9.9999997473787516355514526367188e-05);
    return (1.0 - g2) / ((12.56637096405029296875 * denom) * sqrt(denom));
}

static inline __attribute__((always_inline))
float godrays_phase2(thread const float& cosTheta, thread const float3& lobes)
{
    float param = cosTheta;
    float param_1 = lobes.x;
    float param_2 = cosTheta;
    float param_3 = lobes.y;
    return godrays_phase(param, param_1) + (godrays_phase(param_2, param_3) * lobes.z);
}

static inline __attribute__((always_inline))
float4 fog_shafts(thread const float3& dir, thread const float2& uv, thread const float& fetchDist, constant FogUniforms& _102, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    float2 param = uv;
    float param_1 = fetchDist;
    float2 shaft = godrays_fetch(param, param_1, godrays_resolved, godrays_resolvedSmplr);
    float lit = mix(1.0, shaft.y, _102.u_fog_shafts.y);
    float3 _497;
    if (_102.u_fog_shaft_light.w > 0.5)
    {
        _497 = _102.u_fog_to_moon.xyz;
    }
    else
    {
        _497 = _102.u_fog_model.xyz;
    }
    float3 toLight = _497;
    float param_2 = dot(dir, toLight);
    float3 param_3 = _102.u_fog_shaft_phase.xyz;
    float phase = godrays_phase2(param_2, param_3);
    return float4(lit, _102.u_fog_shaft_light.xyz * ((phase * shaft.x) * _102.u_fog_shafts.x));
}

static inline __attribute__((always_inline))
float3 fog_apply_sky_rays(thread const float3& color, thread const float3& dir, thread const float2& uv, constant FogUniforms& _102, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    if (_102.u_fog_shafts.w < 0.5)
    {
        float3 param = color;
        float3 param_1 = dir;
        return fog_apply_sky(param, param_1, _102);
    }
    float3 d = fast::normalize(dir);
    float3 param_2 = d;
    float2 param_3 = uv;
    float param_4 = 60000.0;
    float4 shafts = fog_shafts(param_2, param_3, param_4, _102, godrays_resolved, godrays_resolvedSmplr);
    bool moonKey = _102.u_fog_shaft_light.w > 0.5;
    float _565;
    if (moonKey)
    {
        _565 = 1.0;
    }
    else
    {
        _565 = shafts.x;
    }
    float lit_sun = _565;
    float _574;
    if (moonKey)
    {
        _574 = shafts.x;
    }
    else
    {
        _574 = 1.0;
    }
    float lit_moon = _574;
    float3 param_5 = color;
    float3 param_6 = d;
    float param_7 = _102.u_fog_params.z;
    float param_8 = lit_sun;
    float param_9 = lit_moon;
    float3 param_10 = shafts.yzw;
    return fog_height(param_5, param_6, param_7, param_8, param_9, param_10, _102);
}

fragment fs_out fs(fs_in in [[stage_in]], constant CameraUniforms& _619 [[buffer(3)]], constant FogUniforms& _102 [[buffer(5)]], texturecube<float> u_skybox [[texture(0)]], texture2d<float> godrays_resolved [[texture(15)]], sampler u_skyboxSmplr [[sampler(0)]], sampler godrays_resolvedSmplr [[sampler(15)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float3 dir = fast::normalize(in.v_direction);
    float3 color = u_skybox.sample(u_skyboxSmplr, dir).xyz;
    float3 param = color;
    float3 param_1 = dir;
    float2 param_2 = gl_FragCoord.xy * _619.u_resolution.zw;
    color = fog_apply_sky_rays(param, param_1, param_2, _102, godrays_resolved, godrays_resolvedSmplr);
    out.frag_color = float4(color, 1.0);
    return out;
}

