// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float frag_ao [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
};

fragment fs_out fs(fs_in in [[stage_in]], texture2d<float> ssao_noisy [[texture(0)]], sampler ssao_noisySmplr [[sampler(0)]])
{
    fs_out out = {};
    float2 texel = float2(1.0) / float2(int2(ssao_noisy.get_width(), ssao_noisy.get_height()));
    float total = 0.0;
    for (int x = -3; x <= 3; x++)
    {
        for (int y = -3; y <= 3; y++)
        {
            total += ssao_noisy.sample(ssao_noisySmplr, (in.v_uv + (float2(float(x), float(y)) * texel))).x;
        }
    }
    out.frag_ao = total / 49.0;
    return out;
}

