// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float frag_ao [[color(0)]];
};

struct fs_in
{
    float2 v_uv [[user(locn0)]];
};

fragment fs_out fs(fs_in in [[stage_in]], texture2d<float> ssao_noisy [[texture(0)]], sampler ssao_noisySmplr [[sampler(0)]])
{
    fs_out out = {};
    float2 texel = float2(1.0) / float2(int2(ssao_noisy.get_width(), ssao_noisy.get_height()));
    float2 _step = float2(texel.x, 0.0);
    float total = 0.0;
    for (int i = -3; i <= 3; i++)
    {
        total += ssao_noisy.sample(ssao_noisySmplr, (in.v_uv + (_step * float(i)))).x;
    }
    out.frag_ao = total / 7.0;
    return out;
}

