// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ToneMapUniforms
{
    float4 u_tm_exposure;
    float4 u_tm_local;
    float4 u_tm_grid;
    float4 u_tm_size;
    float4 u_tm_curve;
    float4 u_tm_in[3];
    float4 u_tm_out[3];
    float4 u_tm_adapt;
    float4 u_tm_meter;
    float4 u_tm_history;
    float4 u_tm_pass;
};

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

static inline __attribute__((always_inline))
float tonemap_ev(texture2d<float> exposure, sampler exposureSmplr, constant ToneMapUniforms& _133)
{
    if (_133.u_tm_exposure.y > 0.5)
    {
        return exposure.read(uint2(int2(0)), 0).x;
    }
    return _133.u_tm_exposure.x;
}

static inline __attribute__((always_inline))
float grid_base(thread const float2& uv, thread const float& level0, constant ToneMapUniforms& _133, texture2d<float> u_grid, sampler u_gridSmplr)
{
    float last = _133.u_tm_grid.w - 1.0;
    float z = fast::clamp(((level0 - _133.u_tm_grid.y) / _133.u_tm_grid.z) * last, 0.0, last);
    float z0 = floor(z);
    float z1 = fast::min(z0 + 1.0, last);
    float2 cell = fast::clamp(uv * float2(64.0, 32.0), float2(0.5), float2(63.5, 31.5));
    float width = 64.0 * _133.u_tm_grid.w;
    float2 a = u_grid.sample(u_gridSmplr, float2(((z0 * 64.0) + cell.x) / width, cell.y / 32.0)).xy;
    float2 b = u_grid.sample(u_gridSmplr, float2(((z1 * 64.0) + cell.x) / width, cell.y / 32.0)).xy;
    float2 s = mix(a, b, float2(z - z0));
    if (s.y < 9.9999997473787516355514526367188e-05)
    {
        return level0;
    }
    return s.x / s.y;
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _52;
    if (x < 0.07999999821186065673828125)
    {
        _52 = x - ((6.25 * x) * x);
    }
    else
    {
        _52 = 0.039999999105930328369140625;
    }
    float offset = _52;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _118 = tonemap_neutral(param);
    return _118;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(constant ToneMapUniforms& _133 [[buffer(2)]], texture2d<float> u_scene [[texture(0)]], texture2d<float> u_exposure [[texture(1)]], texture2d<float> u_grid [[texture(2)]], texture2d<float> u_base [[texture(3)]], sampler u_sceneSmplr [[sampler(0)]], sampler u_exposureSmplr [[sampler(1)]], sampler u_gridSmplr [[sampler(2)]], sampler u_baseSmplr [[sampler(3)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float4 hdr = u_scene.read(uint2(int2(gl_FragCoord.xy)), 0);
    float ev = tonemap_ev(u_exposure, u_exposureSmplr, _133);
    float3 color = hdr.xyz * exp2(ev);
    float level0 = log2(fast::max(dot(fast::max(color, float3(0.0)), float3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)), 9.9999999747524270787835121154785e-07));
    float2 uv = gl_FragCoord.xy / _133.u_tm_size.zw;
    float gaussian = u_base.sample(u_baseSmplr, uv).x + ev;
    float2 param = uv;
    float param_1 = level0;
    float base = mix(gaussian, grid_base(param, param_1, _133, u_grid, u_gridSmplr), _133.u_tm_grid.x);
    float mid = _133.u_tm_local.x;
    float _316;
    if (base > mid)
    {
        _316 = _133.u_tm_local.y;
    }
    else
    {
        _316 = _133.u_tm_local.z;
    }
    float contrast = _316;
    float target = ((contrast * (base - mid)) + (_133.u_tm_local.w * (level0 - base))) + mid;
    color *= exp2(target - level0);
    color *= _133.u_tm_exposure.w;
    float3 param_2 = color;
    color = apply_tonemap(param_2);
    float3 param_3 = color;
    out.fragment_color = float4(gamma_correct(param_3), hdr.w);
    return out;
}

