// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ToneMapUniforms
{
    float4 u_tm_exposure;
    float4 u_tm_local;
    float4 u_tm_grid;
    float4 u_tm_size;
    float4 u_tm_curve;
    float4 u_tm_in[3];
    float4 u_tm_out[3];
    float4 u_tm_adapt;
    float4 u_tm_meter;
    float4 u_tm_history;
    float4 u_tm_pass;
};

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

static inline __attribute__((always_inline))
float tonemap_ev(texture2d<float> exposure, sampler exposureSmplr, constant ToneMapUniforms& _126)
{
    if (_126.u_tm_exposure.y > 0.5)
    {
        return exposure.read(uint2(int2(0)), 0).x;
    }
    return _126.u_tm_exposure.x;
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _45;
    if (x < 0.07999999821186065673828125)
    {
        _45 = x - ((6.25 * x) * x);
    }
    else
    {
        _45 = 0.039999999105930328369140625;
    }
    float offset = _45;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _111 = tonemap_neutral(param);
    return _111;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(constant ToneMapUniforms& _126 [[buffer(2)]], texture2d<float> u_scene [[texture(0)]], texture2d<float> u_exposure [[texture(1)]], sampler u_sceneSmplr [[sampler(0)]], sampler u_exposureSmplr [[sampler(1)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float4 hdr = u_scene.read(uint2(int2(gl_FragCoord.xy)), 0);
    float ev = tonemap_ev(u_exposure, u_exposureSmplr, _126);
    float3 color = hdr.xyz * exp2(ev);
    color *= _126.u_tm_exposure.w;
    float3 param = color;
    color = apply_tonemap(param);
    float3 param_1 = color;
    out.fragment_color = float4(gamma_correct(param_1), hdr.w);
    return out;
}

