// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ToneMapUniforms
{
    float4 u_tm_exposure;
    float4 u_tm_local;
    float4 u_tm_grid;
    float4 u_tm_size;
    float4 u_tm_curve;
    float4 u_tm_in[3];
    float4 u_tm_out[3];
    float4 u_tm_adapt;
    float4 u_tm_meter;
    float4 u_tm_history;
    float4 u_tm_pass;
};

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

static inline __attribute__((always_inline))
float tonemap_ev(texture2d<float> exposure, sampler exposureSmplr, constant ToneMapUniforms& _133)
{
    if (_133.u_tm_exposure.y > 0.5)
    {
        return exposure.read(uint2(int2(0)), 0).x;
    }
    return _133.u_tm_exposure.x;
}

static inline __attribute__((always_inline))
float grid_base(thread const float2& uv, thread const float& level0, constant ToneMapUniforms& _133, texture2d<float> u_grid, sampler u_gridSmplr)
{
    float last = _133.u_tm_grid.w - 1.0;
    float z = fast::clamp(((level0 - _133.u_tm_grid.y) / _133.u_tm_grid.z) * last, 0.0, last);
    float z0 = floor(z);
    float z1 = fast::min(z0 + 1.0, last);
    float2 cell = fast::clamp(uv * float2(64.0, 32.0), float2(0.5), float2(63.5, 31.5));
    float width = 64.0 * _133.u_tm_grid.w;
    float2 a = u_grid.sample(u_gridSmplr, float2(((z0 * 64.0) + cell.x) / width, cell.y / 32.0)).xy;
    float2 b = u_grid.sample(u_gridSmplr, float2(((z1 * 64.0) + cell.x) / width, cell.y / 32.0)).xy;
    float2 s = mix(a, b, float2(z - z0));
    if (s.y < 9.9999997473787516355514526367188e-05)
    {
        return level0;
    }
    return s.x / s.y;
}

static inline __attribute__((always_inline))
float3 tonemap_aces_fit(thread const float3& v)
{
    float3 a = (v * (v + float3(0.02457859925925731658935546875))) - float3(9.0537003416102379560470581054688e-05);
    float3 b = (v * ((v * 0.98372900485992431640625) + float3(0.4329510033130645751953125))) + float3(0.23808099329471588134765625);
    return a / b;
}

static inline __attribute__((always_inline))
float3 tonemap_aces(thread const float3& color)
{
    float3 v = float3(dot(float3(0.59719002246856689453125, 0.354579985141754150390625, 0.048229999840259552001953125), color), dot(float3(0.075999997556209564208984375, 0.908339977264404296875, 0.0156599991023540496826171875), color), dot(float3(0.0284000001847743988037109375, 0.13382999598979949951171875, 0.837769985198974609375), color));
    float3 param = v;
    v = tonemap_aces_fit(param);
    float3 o = float3(dot(float3(1.60475003719329833984375, -0.5310800075531005859375, -0.0736699998378753662109375), v), dot(float3(-0.10208000242710113525390625, 1.108129978179931640625, -0.00604999996721744537353515625), v), dot(float3(-0.00326999998651444911956787109375, -0.07276000082492828369140625, 1.0760200023651123046875), v));
    return fast::clamp(o, float3(0.0), float3(1.0));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    return tonemap_aces(param);
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return pow(color, float3(0.4545454680919647216796875));
}

fragment fs_out fs(constant ToneMapUniforms& _133 [[buffer(2)]], texture2d<float> u_scene [[texture(0)]], texture2d<float> u_exposure [[texture(1)]], texture2d<float> u_grid [[texture(2)]], texture2d<float> u_base [[texture(3)]], sampler u_sceneSmplr [[sampler(0)]], sampler u_exposureSmplr [[sampler(1)]], sampler u_gridSmplr [[sampler(2)]], sampler u_baseSmplr [[sampler(3)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    float4 hdr = u_scene.read(uint2(int2(gl_FragCoord.xy)), 0);
    float ev = tonemap_ev(u_exposure, u_exposureSmplr, _133);
    float3 color = hdr.xyz * exp2(ev);
    float level0 = log2(fast::max(dot(fast::max(color, float3(0.0)), float3(0.2125999927520751953125, 0.715200006961822509765625, 0.072200000286102294921875)), 9.9999999747524270787835121154785e-07));
    float2 uv = gl_FragCoord.xy / _133.u_tm_size.zw;
    float gaussian = u_base.sample(u_baseSmplr, uv).x + ev;
    float2 param = uv;
    float param_1 = level0;
    float base = mix(gaussian, grid_base(param, param_1, _133, u_grid, u_gridSmplr), _133.u_tm_grid.x);
    float mid = _133.u_tm_local.x;
    float _319;
    if (base > mid)
    {
        _319 = _133.u_tm_local.y;
    }
    else
    {
        _319 = _133.u_tm_local.z;
    }
    float contrast = _319;
    float target = ((contrast * (base - mid)) + (_133.u_tm_local.w * (level0 - base))) + mid;
    color *= exp2(target - level0);
    color *= _133.u_tm_exposure.w;
    float3 param_2 = color;
    color = apply_tonemap(param_2);
    float3 param_3 = color;
    out.fragment_color = float4(gamma_correct(param_3), hdr.w);
    return out;
}

