// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float4 frag_stats [[color(0)]];
};

fragment fs_out fs(texture2d<float> u_coarse [[texture(0)]], sampler u_coarseSmplr [[sampler(0)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    int2 origin = int2(gl_FragCoord.xy) * int2(8);
    float sum = 0.0;
    float peak = -64.0;
    for (int y = 0; y < 8; y++)
    {
        for (int x = 0; x < 8; x++)
        {
            float2 v = u_coarse.read(uint2((origin + int2(x, y))), 0).xy;
            sum += v.x;
            peak = fast::max(peak, v.y);
        }
    }
    out.frag_stats = float4(sum / 64.0, peak, 0.0, 1.0);
    return out;
}

