// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ToneMapUniforms
{
    float4 u_tm_exposure;
    float4 u_tm_local;
    float4 u_tm_grid;
    float4 u_tm_size;
    float4 u_tm_curve;
    float4 u_tm_in[3];
    float4 u_tm_out[3];
    float4 u_tm_adapt;
    float4 u_tm_meter;
    float4 u_tm_history;
    float4 u_tm_pass;
};

struct fs_out
{
    float4 frag_exposure [[color(0)]];
};

fragment fs_out fs(constant ToneMapUniforms& _60 [[buffer(2)]], texture2d<float> u_stats [[texture(0)]], texture2d<float> u_previous [[texture(1)]], sampler u_statsSmplr [[sampler(0)]], sampler u_previousSmplr [[sampler(1)]])
{
    fs_out out = {};
    float peak = -64.0;
    for (int y = 0; y < 4; y++)
    {
        for (int x = 0; x < 8; x++)
        {
            peak = fast::max(peak, u_stats.read(uint2(int2(x, y)), 0).y);
        }
    }
    float lux = _60.u_tm_meter.z;
    float ev = _60.u_tm_exposure.x + (_60.u_tm_adapt.x * (_60.u_tm_adapt.w - log2(fast::max(lux, 9.9999997473787516355514526367188e-06))));
    float over = (peak + ev) - (_60.u_tm_local.x + _60.u_tm_meter.x);
    if (over > 0.0)
    {
        ev -= (over * _60.u_tm_meter.y);
    }
    ev = fast::clamp(ev, _60.u_tm_adapt.y, _60.u_tm_adapt.z);
    float shown = ev;
    if (_60.u_tm_history.z > 0.5)
    {
        float last = u_previous.read(uint2(int2(0)), 0).x;
        float _128;
        if (ev > last)
        {
            _128 = _60.u_tm_history.x;
        }
        else
        {
            _128 = _60.u_tm_history.y;
        }
        float blend = _128;
        shown = mix(last, ev, blend);
    }
    out.frag_exposure = float4(shown, ev, lux, 1.0);
    return out;
}

