// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct ToneMapUniforms
{
    float4 u_tm_exposure;
    float4 u_tm_local;
    float4 u_tm_grid;
    float4 u_tm_size;
    float4 u_tm_curve;
    float4 u_tm_in[3];
    float4 u_tm_out[3];
    float4 u_tm_adapt;
    float4 u_tm_meter;
    float4 u_tm_history;
    float4 u_tm_pass;
};

struct fs_out
{
    float4 frag_grid [[color(0)]];
};

static inline __attribute__((always_inline))
int2 tonemap_luma_size(constant ToneMapUniforms& _34)
{
    return int2(_34.u_tm_size.xy + float2(0.5));
}

static inline __attribute__((always_inline))
void tonemap_cell_span(thread const int2& cell, thread const int2& luma, thread int2& lo, thread int2& hi)
{
    lo = (cell * luma) / int2(64, 32);
    hi = max((((cell + int2(1)) * luma) / int2(64, 32)), (lo + int2(1)));
    hi = min(hi, (lo + int2(16)));
}

static inline __attribute__((always_inline))
float tonemap_ev(texture2d<float> exposure, sampler exposureSmplr, constant ToneMapUniforms& _34)
{
    if (_34.u_tm_exposure.y > 0.5)
    {
        return exposure.read(uint2(int2(0)), 0).x;
    }
    return _34.u_tm_exposure.x;
}

fragment fs_out fs(constant ToneMapUniforms& _34 [[buffer(2)]], texture2d<float> u_luma [[texture(0)]], texture2d<float> u_exposure [[texture(1)]], sampler u_lumaSmplr [[sampler(0)]], sampler u_exposureSmplr [[sampler(1)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    int2 p = int2(gl_FragCoord.xy);
    float slice = float(p.x / 64);
    int2 cell = int2(p.x % 64, p.y);
    int2 luma = tonemap_luma_size(_34);
    int2 param = cell;
    int2 param_1 = luma;
    int2 param_2;
    int2 param_3;
    tonemap_cell_span(param, param_1, param_2, param_3);
    int2 lo = param_2;
    int2 hi = param_3;
    float ev = tonemap_ev(u_exposure, u_exposureSmplr, _34);
    float last = _34.u_tm_grid.w - 1.0;
    float2 sum = float2(0.0);
    float n = 0.0;
    for (int y = lo.y; y < hi.y; y++)
    {
        for (int x = lo.x; x < hi.x; x++)
        {
            float v = u_luma.read(uint2(clamp(int2(x, y), int2(0), luma - int2(1))), 0).x + ev;
            float z = fast::clamp(((v - _34.u_tm_grid.y) / _34.u_tm_grid.z) * last, 0.0, last);
            float w = fast::max(1.0 - abs(z - slice), 0.0);
            sum += float2(w * v, w);
            n += 1.0;
        }
    }
    out.frag_grid = float4(sum / float2(fast::max(n, 1.0)), 0.0, 1.0);
    return out;
}

