// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct WaterUniforms
{
    float4x4 u_world;
    float4 u_plane;
    float4 u_absorption;
    float4 u_ripple;
    float4 u_flow;
    float4 u_extra;
    float4 u_body;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

struct vs_out
{
    float3 v_world [[user(locn0)]];
    float3 v_local [[user(locn1)]];
    float2 v_uv [[user(locn2)]];
    float4 v_plane [[user(locn3)]];
    float4 v_absorption [[user(locn4)]];
    float4 v_ripple [[user(locn5)]];
    float4 v_flow [[user(locn6)]];
    float4 v_extra [[user(locn7)]];
    float4 v_body [[user(locn8)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 a_position [[attribute(0)]];
    float2 a_uv [[attribute(1)]];
};

vertex vs_out vs(vs_in in [[stage_in]], constant WaterUniforms& _13 [[buffer(2)]], constant CameraUniforms& _75 [[buffer(3)]])
{
    vs_out out = {};
    float4 world = _13.u_world * float4(in.a_position, 1.0);
    out.v_world = world.xyz;
    out.v_local = in.a_position;
    out.v_uv = in.a_uv;
    out.v_plane = _13.u_plane;
    out.v_absorption = _13.u_absorption;
    out.v_ripple = _13.u_ripple;
    out.v_flow = _13.u_flow;
    out.v_extra = _13.u_extra;
    out.v_body = _13.u_body;
    out.gl_Position = _75.u_projection_view * world;
    return out;
}

