// generated by tools/shaders.php — do not edit
#pragma clang diagnostic ignored "-Wmissing-prototypes"
#pragma clang diagnostic ignored "-Wmissing-braces"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

template<typename T, size_t Num>
struct spvUnsafeArray
{
    T elements[Num ? Num : 1];
    
    thread T& operator [] (size_t pos) thread
    {
        return elements[pos];
    }
    constexpr const thread T& operator [] (size_t pos) const thread
    {
        return elements[pos];
    }
    
    device T& operator [] (size_t pos) device
    {
        return elements[pos];
    }
    constexpr const device T& operator [] (size_t pos) const device
    {
        return elements[pos];
    }
    
    constexpr const constant T& operator [] (size_t pos) const constant
    {
        return elements[pos];
    }
    
    threadgroup T& operator [] (size_t pos) threadgroup
    {
        return elements[pos];
    }
    constexpr const threadgroup T& operator [] (size_t pos) const threadgroup
    {
        return elements[pos];
    }
};

struct FogUniforms
{
    float4 u_fog_density;
    float4 u_fog_color;
    float4 u_fog_params;
    float4 u_fog_sun;
    float4 u_fog_samples;
    float4 u_fog_moon;
    float4 u_fog_shafts;
    float4 u_fog_shaft_light;
    float4 u_fog_shaft_phase;
};

struct PointGpu
{
    float4 position_radius;
    float4 color_intensity;
    float4 source_shadow;
};

struct LightUniforms
{
    float4 u_sun_direction;
    float4 u_sun_color;
    float4 u_ibl;
    float4x4 u_light_space[5];
    float4 u_splits;
    float4 u_shadow;
    float4 u_points_head;
    PointGpu u_points[64];
    float4x4 u_point_face[24];
    float4 u_moon_direction;
    float4 u_moon_color;
    float4 u_night_ambient;
};

struct CameraUniforms
{
    float4x4 u_projection;
    float4x4 u_view;
    float4x4 u_projection_view;
    float4x4 u_inverse_projection;
    float4x4 u_inverse_projection_view;
    float4 u_camera_position;
    float4 u_resolution;
};

constant spvUnsafeArray<float, 5> _590 = spvUnsafeArray<float, 5>({ 0.00120000005699694156646728515625, 0.001700000022538006305694580078125, 0.00179999996908009052276611328125, 0.0005000000237487256526947021484375, 0.00120000005699694156646728515625 });

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

struct fs_in
{
    float3 v_world [[user(locn0)]];
    float3 v_local [[user(locn1)]];
    float4 v_plane [[user(locn3)]];
    float4 v_absorption [[user(locn4)]];
    float4 v_ripple [[user(locn5)]];
    float4 v_flow [[user(locn6)]];
    float4 v_extra [[user(locn7)]];
    float4 v_body [[user(locn8)]];
};

static inline __attribute__((always_inline))
float water_slope(thread const float2& dir, thread const float2& p, thread const float& k, thread const float& phase)
{
    float theta = (dot(dir, p) * k) + phase;
    float fw = length(float2(dfdx(theta), dfdy(theta)));
    float atten = 1.0 - smoothstep(1.0, 2.7999999523162841796875, fw);
    return cos(theta) * atten;
}

static inline __attribute__((always_inline))
float3 ripple_normal(thread const float3& planeN, thread const float3& world, thread const float& time, thread float4& v_ripple, thread float4& v_flow)
{
    float wavelength = fast::max(v_ripple.x, 0.0500000007450580596923828125);
    float amp = v_ripple.z;
    float2 flow = v_flow.xy;
    float fl = length(flow);
    float2 dir = float2(0.86000001430511474609375, 0.5099999904632568359375);
    if (fl > 0.001000000047497451305389404296875)
    {
        dir = flow / float2(fl);
    }
    float2 side = float2(-dir.y, dir.x);
    float k = 6.283185482025146484375 / wavelength;
    float phase = (time * v_ripple.y) * 6.283185482025146484375;
    float2 p = world.xz;
    float2 a = dir;
    float2 b = fast::normalize((dir * 0.449999988079071044921875) + side);
    float2 c = fast::normalize((side * 0.800000011920928955078125) - (dir * 0.300000011920928955078125));
    float2 slope = float2(0.0);
    float2 param = a;
    float2 param_1 = p;
    float param_2 = k;
    float param_3 = phase;
    slope += ((a * water_slope(param, param_1, param_2, param_3)) * amp);
    float2 param_4 = b;
    float2 param_5 = p;
    float param_6 = k * 1.730000019073486328125;
    float param_7 = phase * 0.709999978542327880859375;
    slope += ((b * water_slope(param_4, param_5, param_6, param_7)) * (amp * 0.449999988079071044921875));
    float2 param_8 = c;
    float2 param_9 = p;
    float param_10 = k * 0.569999992847442626953125;
    float param_11 = phase * 1.2000000476837158203125;
    slope += ((c * water_slope(param_8, param_9, param_10, param_11)) * (amp * 0.2800000011920928955078125));
    float3 T = float3(1.0, 0.0, 0.0) - (planeN * planeN.x);
    if (dot(T, T) < 9.9999997473787516355514526367188e-05)
    {
        T = float3(0.0, 0.0, 1.0) - (planeN * planeN.z);
    }
    T = fast::normalize(T);
    float3 B = fast::normalize(cross(planeN, T));
    float gT = dot(T.xz, slope);
    float gB = dot(B.xz, slope);
    return fast::normalize((planeN - (T * gT)) - (B * gB));
}

static inline __attribute__((always_inline))
int csm_index(thread const float& depth, thread const float4& splits)
{
    int shadow_index = 0;
    if (depth < splits.x)
    {
        shadow_index = 1;
    }
    if (depth < splits.y)
    {
        shadow_index = 2;
    }
    if (depth < splits.z)
    {
        shadow_index = 3;
    }
    if (depth < splits.w)
    {
        shadow_index = 4;
    }
    return shadow_index;
}

static inline __attribute__((always_inline))
float2 uv_from_ndc(thread const float2& ndc)
{
    return float2((ndc.x * 0.5) + 0.5, 0.5 - (ndc.y * 0.5));
}

static inline __attribute__((always_inline))
float shadow_gather(texture2d_array<float> shadowmap, sampler shadowmapSmplr, thread const float3& world_position, thread const float3& normal, thread const float3& light_dir, thread const float4x4& light_space, thread const int& shadow_index, thread const float& min_bias)
{
    float4 clip = light_space * float4(world_position, 1.0);
    if (clip.w <= 0.0)
    {
        return 0.0;
    }
    float3 proj = clip.xyz / float3(clip.w);
    float2 param = proj.xy;
    float2 uv = uv_from_ndc(param);
    float current_depth = proj.z;
    if (current_depth > 1.0)
    {
        return 0.0;
    }
    float bias0 = fast::max(min_bias * (1.0 - dot(normal, light_dir)), min_bias);
    float shadow = 0.0;
    int taps = 0;
    float3 texel = float3(1.0) / float3(int3(shadowmap.get_width(), shadowmap.get_height(), shadowmap.get_array_size()));
    for (int x = -1; x <= 1; x++)
    {
        for (int y = -1; y <= 1; y++)
        {
            float2 sample_uv = uv + (float2(float(x), float(y)) * texel.xy);
            bool _521 = sample_uv.x < 0.0;
            bool _528;
            if (!_521)
            {
                _528 = sample_uv.x > 1.0;
            }
            else
            {
                _528 = _521;
            }
            bool _535;
            if (!_528)
            {
                _535 = sample_uv.y < 0.0;
            }
            else
            {
                _535 = _528;
            }
            bool _542;
            if (!_535)
            {
                _542 = sample_uv.y > 1.0;
            }
            else
            {
                _542 = _535;
            }
            if (_542)
            {
                continue;
            }
            float3 _553 = float3(sample_uv, float(shadow_index));
            float closest = shadowmap.sample(shadowmapSmplr, _553.xy, uint(rint(_553.z))).x;
            shadow += float((current_depth - bias0) > closest);
            taps++;
        }
    }
    if (taps == 0)
    {
        return 0.0;
    }
    return fast::clamp(shadow / float(taps), 0.0, 1.0);
}

static inline __attribute__((always_inline))
float shadow_sample(texture2d_array<float> shadowmap, sampler shadowmapSmplr, thread const float3& world_position, thread const float3& normal, thread const float3& light_dir, thread const float4x4& light_space, thread const int& shadow_index)
{
    float3 param = world_position;
    float3 param_1 = normal;
    float3 param_2 = light_dir;
    float4x4 param_3 = light_space;
    int param_4 = shadow_index;
    float param_5 = _590[shadow_index];
    return shadow_gather(shadowmap, shadowmapSmplr, param, param_1, param_2, param_3, param_4, param_5);
}

static inline __attribute__((always_inline))
float3 tonemap_neutral(thread float3& color)
{
    float x = fast::min(color.x, fast::min(color.y, color.z));
    float _172;
    if (x < 0.07999999821186065673828125)
    {
        _172 = x - ((6.25 * x) * x);
    }
    else
    {
        _172 = 0.039999999105930328369140625;
    }
    float offset = _172;
    color -= float3(offset);
    float peak = fast::max(color.x, fast::max(color.y, color.z));
    if (peak < 0.7599999904632568359375)
    {
        return color;
    }
    float newPeak = 1.0 - (0.057599999010562896728515625 / ((peak + 0.23999999463558197021484375) - 0.7599999904632568359375));
    color *= (newPeak / peak);
    float g = 1.0 - (1.0 / ((0.1500000059604644775390625 * (peak - newPeak)) + 1.0));
    return mix(color, float3(newPeak), float3(g));
}

static inline __attribute__((always_inline))
float3 apply_tonemap(thread const float3& color)
{
    float3 param = color;
    float3 _238 = tonemap_neutral(param);
    return _238;
}

static inline __attribute__((always_inline))
float3 gamma_correct(thread const float3& color)
{
    return powr(color, float3(0.4545454680919647216796875));
}

static inline __attribute__((always_inline))
float distribution_GGX(thread const float& NdotH, thread const float& roughness)
{
    float alpha = roughness * roughness;
    float alphaSqr = alpha * alpha;
    float denom = ((NdotH * NdotH) * (alphaSqr - 1.0)) + 1.0;
    float D = alphaSqr / ((3.1415927410125732421875 * denom) * denom);
    return D;
}

static inline __attribute__((always_inline))
float geometry_smith_ggx_correlated(thread const float& NdotL, thread const float& NdotV, thread const float& roughness)
{
    float a = roughness * roughness;
    float a2 = a * a;
    float gv = NdotL * sqrt(a2 + (((1.0 - a2) * NdotV) * NdotV));
    float gl = NdotV * sqrt(a2 + (((1.0 - a2) * NdotL) * NdotL));
    return ((2.0 * NdotL) * NdotV) / fast::max(gv + gl, 9.9999999747524270787835121154785e-07);
}

static inline __attribute__((always_inline))
float3 fresnel_schlick(thread const float3& F0, thread const float& cosTheta)
{
    return F0 + ((float3(1.0) - F0) * powr(1.0 - cosTheta, 5.0));
}

static inline __attribute__((always_inline))
float3 pbr_specular(thread const float3& N, thread const float3& V, thread const float3& H, thread const float3& L, thread const float3& F0, thread const float& roughness, thread float3& fresnel)
{
    float NdotH = fast::max(9.9999997473787516355514526367188e-06, dot(N, H));
    float NdotV = fast::max(dot(N, V), 0.0);
    float NdotL = fast::max(dot(N, L), 0.0);
    float VdotH = fast::max(9.9999997473787516355514526367188e-06, dot(V, H));
    if ((NdotV <= 0.0) || (NdotL <= 0.0))
    {
        fresnel = float3(0.0);
        return float3(0.0);
    }
    float param = NdotH;
    float param_1 = roughness;
    float D = distribution_GGX(param, param_1);
    float param_2 = NdotL;
    float param_3 = NdotV;
    float param_4 = roughness;
    float G = geometry_smith_ggx_correlated(param_2, param_3, param_4);
    float3 param_5 = F0;
    float param_6 = VdotH;
    fresnel = fresnel_schlick(param_5, param_6);
    float denom = fast::max((4.0 * NdotV) * NdotL, 9.9999999747524270787835121154785e-07);
    return ((fresnel * D) * G) / float3(denom);
}

static inline __attribute__((always_inline))
float point_atten(thread const float& dist, thread const float& radius)
{
    float d = fast::clamp(dist / fast::max(radius, 9.9999997473787516355514526367188e-05), 0.0, 1.0);
    float window = fast::clamp(1.0 - (((d * d) * d) * d), 0.0, 1.0);
    window *= window;
    return window / ((dist * dist) + 1.0);
}

static inline __attribute__((always_inline))
float3 water_sphere_l(thread const float3& toLight, thread const float3& V, thread const float3& N, thread const float& sourceRadius)
{
    float3 R = reflect(-V, N);
    float3 centerToRay = (R * dot(toLight, R)) - toLight;
    float rayDist = length(centerToRay);
    float3 closest = toLight;
    if (rayDist > 9.9999997473787516355514526367188e-05)
    {
        closest = toLight + (centerToRay * fast::clamp(sourceRadius / rayDist, 0.0, 1.0));
    }
    return fast::normalize(closest);
}

static inline __attribute__((always_inline))
int point_face_index(thread const float3& dir)
{
    float3 a = abs(dir);
    bool _1268 = a.x >= a.y;
    bool _1276;
    if (_1268)
    {
        _1276 = a.x >= a.z;
    }
    else
    {
        _1276 = _1268;
    }
    if (_1276)
    {
        return (dir.x >= 0.0) ? 0 : 1;
    }
    if (a.y >= a.z)
    {
        return (dir.y >= 0.0) ? 2 : 3;
    }
    return (dir.z >= 0.0) ? 4 : 5;
}

static inline __attribute__((always_inline))
float3 encoded_linear(thread const float3& display)
{
    return powr(fast::max(display, float3(0.0)), float3(2.2000000476837158203125));
}

static inline __attribute__((always_inline))
float3 radiance_linear(thread const float3& radiance)
{
    float3 param = radiance;
    float3 param_1 = apply_tonemap(param);
    float3 param_2 = gamma_correct(param_1);
    return encoded_linear(param_2);
}

static inline __attribute__((always_inline))
float fog_integral(thread const float& dy, thread const float& len, constant FogUniforms& _834)
{
    float k = _834.u_fog_density.y;
    float d0 = _834.u_fog_density.x;
    float x = fast::max((k * dy) * len, -60.0);
    if (abs(x) < 9.9999997473787516355514526367188e-05)
    {
        return (d0 * len) * (1.0 - (0.5 * x));
    }
    return (d0 * (1.0 - exp(-x))) / (k * dy);
}

static inline __attribute__((always_inline))
float3 water_fog(thread const float3& color, thread const float3& relative, constant FogUniforms& _834, constant LightUniforms& _960)
{
    if (_834.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _834.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _834.u_fog_params.x;
    float param = dy;
    float param_1 = len;
    float optical = fog_integral(param, param_1, _834);
    float param_2 = dy;
    float param_3 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_2, param_3, _834))), 1.0 - _834.u_fog_density.z);
    float param_4 = dy;
    float param_5 = fast::min(len, start + _834.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_4, param_5, _834)));
    float3 sunDir = fast::normalize(-_960.u_sun_direction.xyz);
    float sun = powr(fast::max(dot(dir, sunDir), 0.0), fast::max(_834.u_fog_sun.w, 1.0));
    float3 moonDir = fast::normalize(-_960.u_moon_direction.xyz);
    float moon = powr(fast::max(dot(dir, moonDir), 0.0), fast::max(_834.u_fog_moon.w, 1.0));
    float3 param_6 = _834.u_fog_sun.xyz;
    float3 param_7 = _834.u_fog_moon.xyz;
    float3 glow = (radiance_linear(param_6) * sun) + (radiance_linear(param_7) * moon);
    float3 param_8 = _834.u_fog_color.xyz;
    float3 fog = (radiance_linear(param_8) * (1.0 - t)) + (glow * (1.0 - td));
    return (color * t) + fog;
}

static inline __attribute__((always_inline))
float2 godrays_fetch(thread const float2& uv, thread const float& dist, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr)
{
    float2 size = float2(int2(godrays_resolved.get_width(), godrays_resolved.get_height()));
    float2 st = (uv * size) - float2(0.5);
    float2 cell = floor(st);
    float2 f = st - cell;
    int2 base = int2(cell);
    int2 top = int2(size) - int2(1);
    float d = fast::min(dist, 60000.0);
    float2 sum = float2(0.0);
    float weight = 0.0;
    float _713;
    float _726;
    for (int j = 0; j < 2; j++)
    {
        for (int i = 0; i < 2; i++)
        {
            float4 s = godrays_resolved.read(uint2(clamp(base + int2(i, j), int2(0), top)), 0);
            if (i == 0)
            {
                _713 = 1.0 - f.x;
            }
            else
            {
                _713 = f.x;
            }
            float bx = _713;
            if (j == 0)
            {
                _726 = 1.0 - f.y;
            }
            else
            {
                _726 = f.y;
            }
            float by = _726;
            float rel = abs(s.z - d) / fast::max(d, 1.0);
            float w = ((bx * by) / (0.001000000047497451305389404296875 + rel)) + 9.9999999747524270787835121154785e-07;
            sum += (s.xy * w);
            weight += w;
        }
    }
    return sum / float2(weight);
}

static inline __attribute__((always_inline))
float godrays_phase(thread const float& cosTheta, thread const float& g)
{
    float g2 = g * g;
    float denom = fast::max((1.0 + g2) - ((2.0 * g) * cosTheta), 9.9999997473787516355514526367188e-05);
    return (1.0 - g2) / ((12.56637096405029296875 * denom) * sqrt(denom));
}

static inline __attribute__((always_inline))
float godrays_phase2(thread const float& cosTheta, thread const float3& lobes)
{
    float param = cosTheta;
    float param_1 = lobes.x;
    float param_2 = cosTheta;
    float param_3 = lobes.y;
    return godrays_phase(param, param_1) + (godrays_phase(param_2, param_3) * lobes.z);
}

static inline __attribute__((always_inline))
float3 water_fog_rays(thread const float3& color, thread const float3& relative, thread const float2& uv, texture2d<float> godrays_resolved, sampler godrays_resolvedSmplr, constant FogUniforms& _834, constant LightUniforms& _960, texture2d<float> u_bed, sampler u_bedSmplr)
{
    if (_834.u_fog_shafts.w < 0.5)
    {
        float3 param = color;
        float3 param_1 = relative;
        return water_fog(param, param_1, _834, _960);
    }
    if (_834.u_fog_density.w < 0.5)
    {
        return color;
    }
    float len = length(relative);
    if (len < 0.001000000047497451305389404296875)
    {
        return color;
    }
    float cutoff = _834.u_fog_params.y;
    if ((cutoff > 0.0) && (len > cutoff))
    {
        return color;
    }
    float3 dir = relative / float3(len);
    float dy = dir.y;
    float start = _834.u_fog_params.x;
    float param_2 = dy;
    float param_3 = len;
    float optical = fog_integral(param_2, param_3, _834);
    float param_4 = dy;
    float param_5 = fast::min(len, start);
    float t = fast::max(exp(-(optical - fog_integral(param_4, param_5, _834))), 1.0 - _834.u_fog_density.z);
    float param_6 = dy;
    float param_7 = fast::min(len, start + _834.u_fog_params.w);
    float td = exp(-(optical - fog_integral(param_6, param_7, _834)));
    float4 bed = u_bed.sample(u_bedSmplr, uv);
    float _1128;
    if (bed.w >= 0.5)
    {
        _1128 = length(bed.xyz);
    }
    else
    {
        _1128 = 60000.0;
    }
    float bedDist = _1128;
    float2 param_8 = uv;
    float param_9 = bedDist;
    float2 shaft = godrays_fetch(param_8, param_9, godrays_resolved, godrays_resolvedSmplr);
    shaft.x *= fast::clamp(len / fast::max(bedDist, 0.001000000047497451305389404296875), 0.0, 1.0);
    float occlude = mix(1.0, shaft.y, _834.u_fog_shafts.y);
    float3 sunDir = fast::normalize(-_960.u_sun_direction.xyz);
    float sun = powr(fast::max(dot(dir, sunDir), 0.0), fast::max(_834.u_fog_sun.w, 1.0));
    float3 moonDir = fast::normalize(-_960.u_moon_direction.xyz);
    float moon = powr(fast::max(dot(dir, moonDir), 0.0), fast::max(_834.u_fog_moon.w, 1.0));
    float3 param_10 = _834.u_fog_sun.xyz;
    float3 param_11 = _834.u_fog_moon.xyz;
    float3 glow = ((radiance_linear(param_10) * sun) + (radiance_linear(param_11) * moon)) * occlude;
    float3 param_12 = _834.u_fog_color.xyz;
    float3 fog = (radiance_linear(param_12) * (1.0 - t)) + (glow * (1.0 - td));
    float3 toLight = (_834.u_fog_shaft_light.w > 0.5) ? moonDir : sunDir;
    float param_13 = dot(dir, toLight);
    float3 param_14 = _834.u_fog_shaft_phase.xyz;
    float phase = godrays_phase2(param_13, param_14);
    float3 param_15 = _834.u_fog_shaft_light.xyz * ((phase * shaft.x) * _834.u_fog_shafts.x);
    float3 rays = radiance_linear(param_15);
    return ((color * t) + fog) + rays;
}

fragment fs_out fs(fs_in in [[stage_in]], constant CameraUniforms& _1565 [[buffer(3)]], constant LightUniforms& _960 [[buffer(4)]], constant FogUniforms& _834 [[buffer(5)]], texture2d<float> u_scene [[texture(0)]], texture2d<float> u_bed [[texture(1)]], texture2d<float> u_mirror [[texture(2)]], texturecube<float> u_prefilter [[texture(7)]], texture2d_array<float> shadowmap [[texture(11)]], texture2d<float> point_tiles [[texture(13)]], texture2d_array<float> point_shadow [[texture(14)]], texture2d<float> godrays_resolved [[texture(15)]], sampler u_sceneSmplr [[sampler(0)]], sampler u_bedSmplr [[sampler(1)]], sampler u_mirrorSmplr [[sampler(2)]], sampler u_prefilterSmplr [[sampler(7)]], sampler shadowmapSmplr [[sampler(11)]], sampler point_tilesSmplr [[sampler(13)]], sampler point_shadowSmplr [[sampler(14)]], sampler godrays_resolvedSmplr [[sampler(15)]], float4 gl_FragCoord [[position]])
{
    fs_out out = {};
    bool _1530 = in.v_flow.w > 0.5;
    bool _1542;
    if (_1530)
    {
        _1542 = dot(in.v_local.xz, in.v_local.xz) > 0.25;
    }
    else
    {
        _1542 = _1530;
    }
    if (_1542)
    {
        discard_fragment();
    }
    float3 planeN = fast::normalize(in.v_plane.xyz);
    float3 param = planeN;
    float3 param_1 = in.v_world;
    float param_2 = in.v_extra.y;
    float3 N = ripple_normal(param, param_1, param_2, in.v_ripple, in.v_flow);
    float3 V = fast::normalize(_1565.u_camera_position.xyz - in.v_world);
    float facing = fast::max(dot(planeN, V), 0.0);
    float fresnel = mix(0.039999999105930328369140625, 0.2800000011920928955078125, powr(1.0 - facing, 5.0));
    float rough = fast::clamp(in.v_ripple.w, 0.0199999995529651641845703125, 1.0);
    float2 pixel = gl_FragCoord.xy / fast::max(_1565.u_resolution.xy, float2(1.0));
    float2 slide = N.xz * in.v_flow.z;
    float2 refrUv = fast::clamp(pixel + slide, float2(0.0), float2(1.0));
    float4 bedSample = u_bed.sample(u_bedSmplr, refrUv);
    float3 bed = bedSample.xyz + _1565.u_camera_position.xyz;
    float thickness = 6.0;
    float side = dot(planeN, bed) + in.v_plane.w;
    if ((bedSample.w > 0.5) && (side < 0.0))
    {
        thickness = fast::max(distance(in.v_world, bed), 0.0);
    }
    float3 transmit = exp(((-in.v_absorption.xyz) * in.v_absorption.w) * thickness);
    float3 L = fast::normalize(-_960.u_sun_direction.xyz);
    float3 Lm = fast::normalize(-_960.u_moon_direction.xyz);
    bool moonKey = _960.u_moon_color.w > 0.5;
    float keyVis = 1.0;
    if (_960.u_shadow.y > 0.5)
    {
        float viewZ = (_1565.u_view * float4(in.v_world, 1.0)).z;
        float param_3 = viewZ;
        float4 param_4 = _960.u_splits;
        int cascade = csm_index(param_3, param_4);
        float3 _1695;
        if (moonKey)
        {
            _1695 = _960.u_moon_direction.xyz;
        }
        else
        {
            _1695 = _960.u_sun_direction.xyz;
        }
        float3 keyDir = _1695;
        float3 param_5 = in.v_world;
        float3 param_6 = N;
        float3 param_7 = fast::normalize(keyDir);
        float4x4 param_8 = _960.u_light_space[cascade];
        int param_9 = cascade;
        keyVis = 1.0 - shadow_sample(shadowmap, shadowmapSmplr, param_5, param_6, param_7, param_8, param_9);
    }
    float sunVis = moonKey ? 1.0 : keyVis;
    float moonVis = moonKey ? keyVis : 1.0;
    float ndotl = fast::max(dot(N, L), 0.0);
    float maxLodBody = fast::max(_960.u_ibl.x - 1.0, 0.0);
    float3 skyAmbient = u_prefilter.sample(u_prefilterSmplr, float3(0.0, 1.0, 0.0), level(maxLodBody)).xyz + _960.u_night_ambient.xyz;
    float3 sunIn = ((_960.u_sun_color.xyz * _960.u_sun_direction.w) * fast::max(L.y, 0.0)) * sunVis;
    float3 moonIn = ((_960.u_moon_color.xyz * _960.u_moon_direction.w) * fast::max(Lm.y, 0.0)) * moonVis;
    float3 bodyRadiance = in.v_body.xyz * (((sunIn + moonIn) / float3(3.1415927410125732421875)) + skyAmbient);
    float3 param_10 = bodyRadiance;
    float3 param_11 = apply_tonemap(param_10);
    float3 body = gamma_correct(param_11);
    float clear = exp((-in.v_body.w) * thickness);
    float3 refr = mix(body, u_scene.sample(u_sceneSmplr, refrUv).xyz * transmit, float3(clear));
    refr *= (1.0 + ((0.3499999940395355224609375 * powr(ndotl, 6.0)) * sunVis));
    float2 mirrorUv = pixel + (slide * 0.64999997615814208984375);
    float inside = 1.0;
    bool _1836 = mirrorUv.x < 0.0;
    bool _1843;
    if (!_1836)
    {
        _1843 = mirrorUv.y < 0.0;
    }
    else
    {
        _1843 = _1836;
    }
    bool _1850;
    if (!_1843)
    {
        _1850 = mirrorUv.x > 1.0;
    }
    else
    {
        _1850 = _1843;
    }
    bool _1857;
    if (!_1850)
    {
        _1857 = mirrorUv.y > 1.0;
    }
    else
    {
        _1857 = _1850;
    }
    if (_1857)
    {
        inside = 0.0;
    }
    float3 mirror = u_mirror.sample(u_mirrorSmplr, fast::clamp(mirrorUv, float2(0.0), float2(1.0))).xyz;
    float3 R = fast::normalize(reflect(-V, N));
    float3 skyR = fast::normalize(float3(R.x, fast::max(R.y, 0.449999988079071044921875), R.z));
    float maxLod = fast::max(_960.u_ibl.x - 1.0, 0.0);
    float3 ibl = u_prefilter.sample(u_prefilterSmplr, skyR, level(fast::max(rough, 0.550000011920928955078125) * maxLod)).xyz;
    ibl += _960.u_night_ambient.xyz;
    float3 param_12 = ibl;
    float3 param_13 = apply_tonemap(param_12);
    ibl = gamma_correct(param_13);
    float mirrorWeight = (in.v_extra.x * inside) * (1.0 - rough);
    float3 reflected = mix(ibl, mirror, float3(mirrorWeight));
    float3 spec = float3(0.0);
    float3 F0 = float3(0.0199999995529651641845703125);
    float3 H = fast::normalize(V + L);
    float3 param_14 = N;
    float3 param_15 = V;
    float3 param_16 = H;
    float3 param_17 = L;
    float3 param_18 = F0;
    float param_19 = rough;
    float3 param_20;
    float3 _1945 = pbr_specular(param_14, param_15, param_16, param_17, param_18, param_19, param_20);
    float3 fres = param_20;
    float3 sunSpec = _1945;
    float3 radiance = _960.u_sun_color.xyz * _960.u_sun_direction.w;
    spec += (((sunSpec * radiance) * ndotl) * sunVis);
    if (_960.u_moon_direction.w > 0.0)
    {
        float3 H_1 = fast::normalize(V + Lm);
        float3 param_21 = N;
        float3 param_22 = V;
        float3 param_23 = H_1;
        float3 param_24 = Lm;
        float3 param_25 = F0;
        float param_26 = rough;
        float3 param_27;
        float3 _1988 = pbr_specular(param_21, param_22, param_23, param_24, param_25, param_26, param_27);
        float3 fres_1 = param_27;
        float3 moonSpec = _1988;
        float3 radiance_1 = _960.u_moon_color.xyz * _960.u_moon_direction.w;
        spec += (((moonSpec * radiance_1) * fast::max(dot(N, Lm), 0.0)) * moonVis);
    }
    int pointCount = int(_960.u_points_head.x + 0.5);
    if (pointCount > 0)
    {
        float2 px = fast::min(pixel * _1565.u_resolution.xy, _1565.u_resolution.xy - float2(1.0));
        int tilePx = int(_960.u_points_head.y + 0.5);
        int2 tile = int2(px) / int2(max(tilePx, 1));
        int tilesX = max(int(_960.u_points_head.z + 0.5), 1);
        int stride = int(_960.u_points_head.w + 0.5);
        tile.x = clamp(tile.x, 0, tilesX - 1);
        int row = tile.y * stride;
        int n = int((point_tiles.read(uint2(int2(tile.x, row)), 0).x * 255.0) + 0.5);
        float3 param_47;
        for (int i = 0; i < 8; i++)
        {
            if (i >= n)
            {
                break;
            }
            int li = int((point_tiles.read(uint2(int2(tile.x, (row + 1) + i)), 0).x * 255.0) + 0.5);
            if ((li < 0) || (li >= pointCount))
            {
                continue;
            }
            float4 pr = _960.u_points[li].position_radius;
            float3 toLight = pr.xyz - in.v_world;
            float dist = length(toLight);
            if (dist >= pr.w)
            {
                continue;
            }
            float3 Lc = toLight / float3(fast::max(dist, 9.9999997473787516355514526367188e-05));
            float4 src = _960.u_points[li].source_shadow;
            float param_28 = dist;
            float param_29 = pr.w;
            float3 radiance_2 = (_960.u_points[li].color_intensity.xyz * _960.u_points[li].color_intensity.w) * point_atten(param_28, param_29);
            float3 param_30 = toLight;
            float3 param_31 = V;
            float3 param_32 = N;
            float param_33 = src.x;
            float3 Ls = water_sphere_l(param_30, param_31, param_32, param_33);
            float vis = 1.0;
            if (src.y >= 0.0)
            {
                int slot = int(src.y + 0.5);
                float3 shifted = in.v_world + (N * src.z);
                float3 fromLight = shifted - pr.xyz;
                float3 param_34 = fromLight;
                int face = point_face_index(param_34);
                int layer = (slot * 6) + face;
                float3 param_35 = shifted;
                float3 param_36 = N;
                float3 param_37 = fast::normalize(fromLight);
                float4x4 param_38 = _960.u_point_face[layer];
                int param_39 = layer;
                float param_40 = src.w;
                vis = 1.0 - shadow_gather(point_shadow, point_shadowSmplr, param_35, param_36, param_37, param_38, param_39, param_40);
            }
            float3 H_2 = fast::normalize(V + Ls);
            float3 param_41 = N;
            float3 param_42 = V;
            float3 param_43 = H_2;
            float3 param_44 = Ls;
            float3 param_45 = F0;
            float param_46 = rough;
            float3 _2242 = pbr_specular(param_41, param_42, param_43, param_44, param_45, param_46, param_47);
            float3 fres_2 = param_47;
            float3 one = _2242;
            spec += (((one * radiance_2) * fast::max(dot(N, Lc), 0.0)) * vis);
        }
    }
    float3 param_48 = mix(refr, reflected, float3(fresnel));
    float3 param_49 = spec;
    float3 color = encoded_linear(param_48) + radiance_linear(param_49);
    float3 param_50 = color;
    float3 param_51 = in.v_world - _1565.u_camera_position.xyz;
    float2 param_52 = gl_FragCoord.xy * _1565.u_resolution.zw;
    color = water_fog_rays(param_50, param_51, param_52, godrays_resolved, godrays_resolvedSmplr, _834, _960, u_bed, u_bedSmplr);
    float3 param_53 = color;
    out.fragment_color = float4(gamma_correct(param_53), 1.0);
    return out;
}

