// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct Vg
{
    float4 view;
    float4 inner;
    float4 outer;
    float4 scissorExt;
    float4 scissor0;
    float4 scissor1;
    float4 paint0;
    float4 paint1;
    float4 extent;
    float4 stroke;
};

struct vs_out
{
    float2 vPos [[user(locn0)]];
    float2 vUv [[user(locn1)]];
    float4 vShape [[user(locn2)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float2 aPos [[attribute(0)]];
    float2 aUv [[attribute(1)]];
    float4 aShape [[attribute(2)]];
};

vertex vs_out vs(vs_in in [[stage_in]], constant Vg& _26 [[buffer(2)]])
{
    vs_out out = {};
    out.vPos = in.aPos;
    out.vUv = in.aUv;
    out.vShape = in.aShape;
    float2 vp = _26.view.xy;
    out.gl_Position = float4(((2.0 * in.aPos.x) / vp.x) - 1.0, 1.0 - ((2.0 * in.aPos.y) / vp.y), 0.0, 1.0);
    return out;
}

