// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float4 fragColor [[color(0)]];
};

struct fs_in
{
    float3 vPos [[user(locn0)]];
    float4 vColor [[user(locn1)]];
};

fragment fs_out fs(fs_in in [[stage_in]])
{
    fs_out out = {};
    float shade = 0.449999988079071044921875 + (0.550000011920928955078125 * fast::clamp((in.vPos.y * 0.119999997317790985107421875) + 0.550000011920928955078125, 0.0, 1.0));
    out.fragColor = float4(in.vColor.xyz * shade, 1.0);
    return out;
}

