// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float4 FragColor [[color(0)]];
};

struct fs_in
{
    float2 vUv [[user(locn0)]];
};

fragment fs_out fs(fs_in in [[stage_in]], texture2d_array<float> uArray [[texture(0)]], sampler uArraySmplr [[sampler(0)]])
{
    fs_out out = {};
    float3 _23 = float3(in.vUv, 1.0);
    out.FragColor = float4(uArray.sample(uArraySmplr, _23.xy, uint(rint(_23.z))).xyz, 1.0);
    return out;
}

