// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct DcaParams
{
    float4x4 projectionView;
};

struct vs_out
{
    float4 vColor [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 aPos [[attribute(0)]];
    float3 aNormal [[attribute(1)]];
    float4 aModel0 [[attribute(2)]];
    float4 aModel1 [[attribute(3)]];
    float4 aModel2 [[attribute(4)]];
    float4 aModel3 [[attribute(5)]];
    float4 aColor [[attribute(6)]];
};

vertex vs_out vs(vs_in in [[stage_in]], constant DcaParams& _72 [[buffer(2)]])
{
    vs_out out = {};
    float4x4 model = float4x4(float4(in.aModel0), float4(in.aModel1), float4(in.aModel2), float4(in.aModel3));
    out.vColor = float4(in.aColor.xyz + (in.aNormal * 0.0), in.aColor.w);
    out.gl_Position = (_72.projectionView * model) * float4(in.aPos, 1.0);
    return out;
}

