// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct DepthParams
{
    float4x4 projectionView;
    float4 color;
    float4 place;
};

struct vs_out
{
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 aPos [[attribute(0)]];
};

vertex vs_out vs(vs_in in [[stage_in]], constant DepthParams& _19 [[buffer(2)]])
{
    vs_out out = {};
    float3 p = float3((in.aPos.xy * _19.place.w) + _19.place.xy, _19.place.z);
    out.gl_Position = _19.projectionView * float4(p, 1.0);
    return out;
}

