// generated by tools/shaders.php — do not edit
#version 330 core

layout(location = 0) in vec3 aPos;
out vec2 vUv;
layout(location = 1) in vec2 aUv;

void main()
{
    gl_Position = vec4(aPos, 1.0);
    vUv = aUv;
}

