// generated by tools/shaders.php — do not edit
#version 330 core

uniform vec4 QuadParams[1];
layout(location = 0) out vec4 FragColor;
in vec2 vUv;

void main()
{
    FragColor = vec4(vUv, QuadParams[0].z, 1.0);
}

