// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct QuadParams
{
    float4 color;
};

struct fs_out
{
    float4 FragColor [[color(0)]];
};

fragment fs_out fs(constant QuadParams& _12 [[buffer(2)]])
{
    fs_out out = {};
    out.FragColor = _12.color;
    return out;
}

