// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float4 outColor [[color(0)]];
};

struct fs_in
{
    float4 vColor [[user(locn0), flat]];
};

fragment fs_out fs(fs_in in [[stage_in]])
{
    fs_out out = {};
    out.outColor = in.vColor;
    return out;
}

