// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct vs_out
{
    float2 vUv [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 aPos [[attribute(0)]];
};

vertex vs_out vs(vs_in in [[stage_in]])
{
    vs_out out = {};
    out.vUv = (in.aPos.xy * 0.5) + float2(0.5);
    out.gl_Position = float4(in.aPos.x, in.aPos.y, 0.0, 1.0);
    return out;
}

