// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct vs_out
{
    float4 pcolor [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct vs_in
{
    float3 position [[attribute(0)]];
    float3 color [[attribute(1)]];
};

vertex vs_out vs(vs_in in [[stage_in]])
{
    vs_out out = {};
    out.pcolor = float4(in.color, 1.0);
    out.gl_Position = float4(in.position, 1.0);
    return out;
}

