// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct fs_out
{
    float4 fragment_color [[color(0)]];
};

struct fs_in
{
    float4 pcolor [[user(locn0)]];
};

fragment fs_out fs(fs_in in [[stage_in]])
{
    fs_out out = {};
    out.fragment_color = in.pcolor;
    return out;
}

