// generated by tools/shaders.php — do not edit
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct QuadParams
{
    float4 color;
};

struct fs_out
{
    float4 FragColor [[color(0)]];
};

struct fs_in
{
    float2 vUv [[user(locn0)]];
};

fragment fs_out fs(fs_in in [[stage_in]], constant QuadParams& _16 [[buffer(2)]])
{
    fs_out out = {};
    out.FragColor = float4(in.vUv, _16.color.z, 1.0);
    return out;
}

